import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { WebSocketServer } from 'ws';
import { TikTokLiveConnection, WebcastEvent } from 'tiktok-live-connector';

const require=createRequire(import.meta.url);
const { WebcastPushConnection }=require('tiktok-live-connector-legacy');
const PORT=Number(process.env.PORT||8787),ACCESS_KEY=String(process.env.CAOS_CONNECTOR_KEY||'').trim(),MAX_CLIENTS=Math.max(1,Number(process.env.CAOS_MAX_CLIENTS||25));
const __filename=fileURLToPath(import.meta.url),ROOT=path.resolve(path.dirname(__filename),'..');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'};
const WATCHDOG_INTERVAL_MS=30000,PROBE_AFTER_MS=70000,HARD_STALE_MS=150000,PROBE_TIMEOUT_MS=8000;

function currentVersion(){try{return String(JSON.parse(fs.readFileSync(path.join(ROOT,'version.json'),'utf8')).version||'0.0.0')}catch{return'0.0.0'}}
function patchSharedVersion(html){const v=currentVersion();return html.replace(/Caos Live v\d+\.\d+\.\d+/g,`Caos Live v${v}`).replace(/Caos Admin v\d+\.\d+\.\d+/g,`Caos Admin v${v}`).replace(/VERSÃO v\d+\.\d+\.\d+/g,`VERSÃO v${v}`).replace(/PAINEL v\d+\.\d+\.\d+/g,`PAINEL v${v}`).replace(/(<div class=\"version\">)v\d+\.\d+\.\d+/g,`$1v${v}`).replace(/(<div class=\"version\">PAINEL )v\d+\.\d+\.\d+/g,`$1v${v}`).replace(/const VERSION='\d+\.\d+\.\d+'/g,`const VERSION='${v}'`)}
function patchGameHtml(html){return patchSharedVersion(html)}
function patchAdminHtml(html){return patchSharedVersion(html)}
function serveFile(res,file){fs.readFile(file,(err,data)=>{if(err){res.writeHead(404,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});return res.end('Not found')}const ext=path.extname(file).toLowerCase();let body=data;if(ext==='.html'){const html=data.toString('utf8'),name=path.basename(file);body=Buffer.from(name==='painel.html'?patchAdminHtml(html):name==='index.html'?patchGameHtml(html):patchSharedVersion(html),'utf8')}res.writeHead(200,{'content-type':MIME[ext]||'application/octet-stream','cache-control':'no-store'});res.end(body)})}
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent((req.url||'/').split('?')[0]);if(pathname==='/health'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({ok:true,service:'caos-cloud-connector',version:currentVersion(),clients:wss.clients.size}))}if(pathname==='/'||pathname==='/admin'||pathname==='/admin-latest'||pathname==='/painel.html')return serveFile(res,path.join(ROOT,'painel.html'));if(pathname==='/jogo')return serveFile(res,path.join(ROOT,'index.html'));const file=path.resolve(ROOT,pathname.replace(/^\/+/,''));if(!file.startsWith(ROOT)){res.writeHead(403);return res.end('Forbidden')}serveFile(res,file)});

const wss=new WebSocketServer({server});
const observers=new Map();
function safeSend(ws,p){if(ws.readyState===ws.OPEN)ws.send(JSON.stringify(p))}
function dbg(ws,event,data={}){safeSend(ws,{type:'debug',event,...data,at:Date.now()})}
function observe(ws,username=''){const u=String(username||'').trim().replace(/^@/,'').toLowerCase();if(!u)return false;unobserve(ws);let set=observers.get(u);if(!set)observers.set(u,set=new Set());set.add(ws);ws.__caosObserve=u;safeSend(ws,{type:'observe',ok:true,username:u});return true}
function unobserve(ws){const u=ws.__caosObserve;if(!u)return;const set=observers.get(u);set?.delete(ws);if(set&&!set.size)observers.delete(u);delete ws.__caosObserve}
function relay(ws,s,p){const payload={...p,liveUser:s?.username||p.liveUser||''};safeSend(ws,payload);const u=String(s?.username||'').toLowerCase();for(const obs of observers.get(u)||[]){if(obs!==ws)safeSend(obs,payload)}}
function deepValue(obj,keys,depth=0,seen=new Set()){if(!obj||typeof obj!=='object'||depth>5||seen.has(obj))return'';seen.add(obj);for(const k of keys){const v=obj[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number'&&Number.isFinite(v))return String(v)}for(const v of Object.values(obj)){if(v&&typeof v==='object'){const found=deepValue(v,keys,depth+1,seen);if(found)return found}}return''}
function deepImageUrl(obj,depth=0,seen=new Set()){if(!obj||typeof obj!=='object'||depth>7||seen.has(obj))return'';seen.add(obj);const preferred=['giftPictureUrl','gift_picture_url','giftImage','gift_image','icon','image','picture','giftIcon','gift_icon'];for(const k of preferred){const v=obj[k];if(typeof v==='string'&&/^https?:\/\//i.test(v))return v;if(v&&typeof v==='object'){const urls=v.urlList||v.url_list||v.urls;if(Array.isArray(urls)){const hit=urls.find(x=>typeof x==='string'&&/^https?:\/\//i.test(x));if(hit)return hit}const nested=deepImageUrl(v,depth+1,seen);if(nested)return nested}}const directLists=[obj.urlList,obj.url_list,obj.urls];for(const list of directLists){if(Array.isArray(list)){const hit=list.find(x=>typeof x==='string'&&/^https?:\/\//i.test(x));if(hit)return hit}}for(const [k,v] of Object.entries(obj)){if(/avatar|profile|user/i.test(k))continue;if(typeof v==='string'&&/^https?:\/\//i.test(v)&&/\.(?:png|jpe?g|webp)(?:\?|$)/i.test(v))return v;if(v&&typeof v==='object'){const found=deepImageUrl(v,depth+1,seen);if(found)return found}}return''}
function getUser(data={}){return deepValue(data,['uniqueId','unique_id','uniqueID','userName','username','displayId','nickname','nickName'])||'viewer'}
function getComment(data={}){return deepValue(data,['comment','content','text','message','msg'])||''}
function normalizeGift(data={}){const user=getUser(data),gift=data.giftName||data.extendedGiftInfo?.name||data.gift?.name||deepValue(data,['giftName','gift_name'])||`gift-${data.giftId||'unknown'}`,count=Number(data.repeatCount||data.repeat_count||data.count||1)||1,repeatEnd=data.repeatEnd??data.repeat_end??true,giftType=Number(data.giftType??data.gift_type??data.extendedGiftInfo?.type??0)||0,diamondRaw=data.diamondCount??data.diamond_count??data.extendedGiftInfo?.diamondCount??data.extendedGiftInfo?.diamond_count??deepValue(data,['diamondCount','diamond_count','diamondCost','diamond_cost'])??0,diamondCount=Number(diamondRaw)||0,icon=deepImageUrl(data);return{type:'gift',user,gift,count,giftId:data.giftId||data.gift_id||null,diamondCount,repeatEnd,giftType,icon}}
function catalogGift(g={}){const id=g.id??g.giftId??g.gift_id??g.gift?.id??null,name=g.name??g.giftName??g.gift_name??g.gift?.name??`gift-${id??'unknown'}`,diamondCount=Number(g.diamondCount??g.diamond_count??g.diamondCost??g.cost??g.gift?.diamondCount??0)||0,type=Number(g.type??g.giftType??g.gift_type??0)||0;const icon=g.icon?.urlList?.[0]||g.icon?.url_list?.[0]||g.image?.urlList?.[0]||g.image?.url_list?.[0]||g.iconUrl||g.imageUrl||deepImageUrl(g)||'';return{id:id==null?null:String(id),name:String(name),diamondCount,type,icon:String(icon||''),isCombo:!!(g.isCombo??g.combo??type===1)}}
function normalizeCatalog(raw,live){let list=Array.isArray(raw)?raw:raw?.gifts||raw?.giftList||raw?.availableGifts||[];if(!Array.isArray(list)&&Array.isArray(live?.availableGifts))list=live.availableGifts;if(!Array.isArray(list))list=[];const seen=new Set();return list.map(catalogGift).filter(g=>{const k=g.id||g.name.toLowerCase();if(!k||seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>(a.diamondCount-b.diamondCount)||a.name.localeCompare(b.name))}
async function fetchGiftCatalog(username,existingLive=null){const u=String(username||'').trim().replace(/^@/,'');if(!u)throw Error('Informe o @ da Live para capturar presentes.');let live=existingLive,owned=false;if(!live||typeof live.fetchAvailableGifts!=='function'){live=new TikTokLiveConnection(u,{enableExtendedGiftInfo:false,processInitialData:false,fetchRoomInfoOnConnect:true});owned=true}try{if(typeof live.fetchAvailableGifts!=='function')throw Error('Esta versão do Connector não expõe fetchAvailableGifts().');if(owned)await live.connect();let raw;try{raw=await live.fetchAvailableGifts()}catch(e){const msg=String(e?.message||e);if(/roomid/i.test(msg)&&!owned){const fresh=new TikTokLiveConnection(u,{enableExtendedGiftInfo:false,processInitialData:false,fetchRoomInfoOnConnect:true});try{await fresh.connect();raw=await fresh.fetchAvailableGifts()}finally{try{fresh.removeAllListeners?.();await fresh.disconnect?.()}catch{}}}else throw e}const gifts=normalizeCatalog(raw,live);if(!gifts.length)throw Error('TikTok não retornou presentes para esta sala.');return gifts}finally{if(owned){try{live.removeAllListeners?.();await live.disconnect?.()}catch{}}}}
function isSigningPaywall(e){const s=String(e?.message||e||'').toLowerCase();return s.includes('business plan')||s.includes('fetchwebcastsignature')||(s.includes('eulerstream')&&s.includes('sign'))}
function clearReconnect(s){if(s.reconnectTimer){clearTimeout(s.reconnectTimer);s.reconnectTimer=null}}
function clearWatchdog(s){if(s.watchdogTimer){clearInterval(s.watchdogTimer);s.watchdogTimer=null}}
function touchLive(s,kind='event'){s.lastEventAt=Date.now();s.lastSignal=kind;s.probeFailures=0}
function markConnected(s){clearReconnect(s);s.reconnectAttempt=0;s.lastConnectedAt=Date.now();touchLive(s,'connected')}
async function closeLive(s,preserveTarget=false){if(s.live){try{s.live.removeAllListeners?.()}catch{}try{await s.live.disconnect?.()}catch{}}s.live=null;if(!preserveTarget){s.username='';s.wantedUsername=''}s.connecting=false;s.mode=''}
function scheduleReconnect(ws,s,reason='conexão TikTok encerrada'){if(s.manualStop||!s.wantedUsername||s.connecting||s.reconnectTimer||ws.readyState!==ws.OPEN)return;const attempt=Math.min(8,(s.reconnectAttempt||0)+1);s.reconnectAttempt=attempt;const delay=Math.min(15000,1200*Math.pow(1.65,attempt-1));safeSend(ws,{type:'status',status:'reconnecting',username:s.wantedUsername,attempt,delay:Math.round(delay),reason});dbg(ws,'RECONEXÃO AGENDADA',{username:s.wantedUsername,attempt,delay:Math.round(delay),reason});s.reconnectTimer=setTimeout(async()=>{s.reconnectTimer=null;if(s.manualStop||ws.readyState!==ws.OPEN||!s.wantedUsername)return;const u=s.wantedUsername;await closeLive(s,true);await connectLive(ws,s,u,true)},delay)}
async function hardReconnect(ws,s,reason='watchdog'){if(s.manualStop||s.connecting||s.reconnectTimer||!s.wantedUsername||ws.readyState!==ws.OPEN)return;const u=s.wantedUsername;safeSend(ws,{type:'status',status:'zombie',username:u,reason});dbg(ws,'SESSÃO ZUMBI DETECTADA',{username:u,reason,eventAge:Date.now()-(s.lastEventAt||0),mode:s.mode});await closeLive(s,true);scheduleReconnect(ws,s,reason)}
async function probeTikTok(ws,s){if(!s.live||s.manualStop||s.connecting||s.probeBusy)return;const age=Date.now()-(s.lastEventAt||s.lastConnectedAt||Date.now());const connectedFlag=typeof s.live.isConnected==='boolean'?s.live.isConnected:true;if(!connectedFlag){await hardReconnect(ws,s,'isConnected=false');return}if(age<PROBE_AFTER_MS)return;s.probeBusy=true;try{let liveState=true;if(typeof s.live.fetchIsLive==='function'){liveState=await Promise.race([Promise.resolve(s.live.fetchIsLive()),new Promise((_,reject)=>setTimeout(()=>reject(new Error('probe timeout')),PROBE_TIMEOUT_MS))]);s.lastProbeAt=Date.now();s.lastProbeOkAt=Date.now();s.probeFailures=0;if(liveState===false){safeSend(ws,{type:'status',status:'offline',username:s.wantedUsername,reason:'TikTok informou Live offline'});return}}if(age>=HARD_STALE_MS){await hardReconnect(ws,s,`sem eventos por ${Math.round(age/1000)}s`)}else dbg(ws,'WATCHDOG TIKTOK OK',{username:s.wantedUsername,eventAge:age,mode:s.mode})}catch(e){s.probeFailures=(s.probeFailures||0)+1;dbg(ws,'WATCHDOG TIKTOK FALHOU',{detail:String(e?.message||e).slice(0,160),failures:s.probeFailures,eventAge:age});if(s.probeFailures>=2||age>=HARD_STALE_MS)await hardReconnect(ws,s,'probe TikTok falhou')}finally{s.probeBusy=false}}
function startWatchdog(ws,s){clearWatchdog(s);s.watchdogTimer=setInterval(()=>probeTikTok(ws,s),WATCHDOG_INTERVAL_MS)}
function emitLike(ws,s,data,mode){touchLive(s,'like-passive');const user=getUser(data),count=Math.max(1,Number(data.likeCount||data.count||data.totalLikeCount||deepValue(data,['likeCount','like_count'])||1)||1);s.passiveLikeCount=(s.passiveLikeCount||0)+count;const now=Date.now();if(now-(s.lastLikeDebugAt||0)>=2000){const pending=s.passiveLikeCount;s.passiveLikeCount=0;s.lastLikeDebugAt=now;dbg(ws,'LIKE PASSIVO',{user,count:pending,mode,passive:true})}}
function emitChat(ws,s,data,mode){touchLive(s,'chat');const user=getUser(data),comment=getComment(data);dbg(ws,'CHAT RECEBIDO',{user,mode,comment:comment.slice(0,80)});relay(ws,s,{type:'chat',user,comment,mode})}
function emitFollow(ws,s,data,mode){touchLive(s,'follow');const user=getUser(data);dbg(ws,'FOLLOW RECEBIDO',{user,mode});relay(ws,s,{type:'follow',user,mode})}
function emitShare(ws,s,data,mode){touchLive(s,'share');const user=getUser(data);dbg(ws,'SHARE RECEBIDO',{user,mode});relay(ws,s,{type:'share',user,mode})}
function attachModern(ws,s,live){live.on(WebcastEvent.GIFT,d=>{touchLive(s,'gift');const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,giftId:g.giftId,diamonds:g.diamondCount,hasIcon:!!g.icon,mode:'modern'});if(g.giftType===1&&g.repeatEnd===false)return;relay(ws,s,g)});live.on(WebcastEvent.LIKE,d=>emitLike(ws,s,d,'modern'));const chatHandler=d=>emitChat(ws,s,d,'modern');live.on(WebcastEvent.CHAT,chatHandler);if(WebcastEvent.CHAT!=='chat')live.on('chat',chatHandler);live.on('comment',chatHandler);const followHandler=d=>emitFollow(ws,s,d,'modern'),shareHandler=d=>emitShare(ws,s,d,'modern');if(WebcastEvent.FOLLOW)live.on(WebcastEvent.FOLLOW,followHandler);else live.on('follow',followHandler);if(WebcastEvent.SHARE)live.on(WebcastEvent.SHARE,shareHandler);else live.on('share',shareHandler);live.on('disconnected',()=>{if(s.live!==live||s.manualStop)return;relay(ws,s,{type:'status',status:'disconnected',reason:'tiktok'});scheduleReconnect(ws,s,'TikTok desconectou')});live.on('error',e=>dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'modern'}))}
function attachLegacy(ws,s,live){live.on('gift',d=>{touchLive(s,'gift');const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,giftId:g.giftId,diamonds:g.diamondCount,hasIcon:!!g.icon,mode:'legacy'});if(g.giftType===1&&g.repeatEnd===false)return;relay(ws,s,g)});live.on('like',d=>emitLike(ws,s,d,'legacy'));live.on('chat',d=>emitChat(ws,s,d,'legacy'));live.on('comment',d=>emitChat(ws,s,d,'legacy'));live.on('follow',d=>emitFollow(ws,s,d,'legacy'));live.on('share',d=>emitShare(ws,s,d,'legacy'));live.on('disconnected',()=>{if(s.live!==live||s.manualStop)return;relay(ws,s,{type:'status',status:'disconnected',reason:'tiktok'});scheduleReconnect(ws,s,'TikTok desconectou')});live.on('error',e=>dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'legacy'}))}
async function tryLegacy(ws,s,u){safeSend(ws,{type:'status',status:'fallback',username:u});const live=new WebcastPushConnection(u,{processInitialData:false,fetchRoomInfoOnConnect:true,enableExtendedGiftInfo:false,enableWebsocketUpgrade:true,requestPollingIntervalMs:1000});s.live=live;s.mode='legacy';attachLegacy(ws,s,live);try{const info=await live.connect();s.connecting=false;markConnected(s);safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'legacy'});return true}catch(e){s.connecting=false;await closeLive(s,true);safeSend(ws,{type:'error',message:`Fallback falhou: ${String(e?.message||e).slice(0,220)}`});scheduleReconnect(ws,s,'fallback falhou');return false}}
async function connectLive(ws,s,u,reconnecting=false){u=String(u||'').trim().replace(/^@/,'');if(!u)return safeSend(ws,{type:'error',message:'Informe o @usuario da LIVE.'});if(s.connecting)return;clearReconnect(s);s.manualStop=false;s.connecting=true;s.username=u;s.wantedUsername=u;safeSend(ws,{type:'status',status:reconnecting?'reconnecting':'checking',username:u,attempt:s.reconnectAttempt||0});const live=new TikTokLiveConnection(u,{enableExtendedGiftInfo:false,processInitialData:false,fetchRoomInfoOnConnect:true});s.live=live;s.mode='modern';attachModern(ws,s,live);try{const info=await live.connect();s.connecting=false;markConnected(s);safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'modern'})}catch(e){try{live.removeAllListeners?.();await live.disconnect?.()}catch{}s.live=null;if(isSigningPaywall(e))return tryLegacy(ws,s,u);s.connecting=false;safeSend(ws,{type:'error',message:String(e?.message||e).slice(0,260)});scheduleReconnect(ws,s,'falha ao reconectar')}}
wss.on('connection',ws=>{if(wss.clients.size>MAX_CLIENTS){safeSend(ws,{type:'error',message:'Servidor temporariamente lotado.'});return ws.close(1013,'busy')}const s={authenticated:!ACCESS_KEY,live:null,username:'',wantedUsername:'',connecting:false,mode:'',manualStop:false,reconnectTimer:null,reconnectAttempt:0,lastConnectedAt:0,lastEventAt:0,lastSignal:'',watchdogTimer:null,probeBusy:false,probeFailures:0,lastProbeAt:0,lastProbeOkAt:0,passiveLikeCount:0,lastLikeDebugAt:0};startWatchdog(ws,s);safeSend(ws,{type:'bridge',status:'ready',authRequired:Boolean(ACCESS_KEY)});ws.on('message',async raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='auth'){s.authenticated=!ACCESS_KEY||String(m.key||'')===ACCESS_KEY;return safeSend(ws,{type:'auth',ok:s.authenticated})}if(!s.authenticated)return safeSend(ws,{type:'error',message:'Chave do Caos Connector inválida.'});if(m.type==='connect'){s.manualStop=false;await connectLive(ws,s,m.username)}if(m.type==='disconnect'){s.manualStop=true;clearReconnect(s);await closeLive(s);safeSend(ws,{type:'status',status:'disconnected',manual:true})}if(m.type==='observe'){if(!observe(ws,m.username))safeSend(ws,{type:'observe',ok:false,message:'Informe o @ para observar.'})}if(m.type==='giftcatalog'){try{const u=String(m.username||s.username||'').replace(/^@/,'');const live=s.live&&String(s.username).toLowerCase()===u.toLowerCase()?s.live:null;safeSend(ws,{type:'gift_catalog_status',status:'capturing',username:u});const gifts=await fetchGiftCatalog(u,live);safeSend(ws,{type:'gift_catalog',username:u,capturedAt:Date.now(),gifts})}catch(e){safeSend(ws,{type:'gift_catalog_error',message:String(e?.message||e).slice(0,260)})}}if(m.type==='ping')safeSend(ws,{type:'pong',at:Date.now(),mode:s.mode,username:s.username,reconnecting:Boolean(s.reconnectTimer),attempt:s.reconnectAttempt||0,tiktokConnected:Boolean(s.live&&(typeof s.live.isConnected!=='boolean'||s.live.isConnected)),eventAgeMs:s.lastEventAt?Date.now()-s.lastEventAt:null,lastSignal:s.lastSignal||null,probeFailures:s.probeFailures||0})});ws.on('close',()=>{unobserve(ws);s.manualStop=true;clearReconnect(s);clearWatchdog(s);closeLive(s)})});
server.listen(PORT,'0.0.0.0',()=>console.log(`CAOS CLOUD CONNECTOR v${currentVersion()} zombie-watchdog online :${PORT}`));
