import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { WebSocketServer } from 'ws';
import { TikTokLiveConnection, WebcastEvent } from 'tiktok-live-connector';

const require = createRequire(import.meta.url);
const { WebcastPushConnection } = require('tiktok-live-connector-legacy');
const PORT=Number(process.env.PORT||8787),ACCESS_KEY=String(process.env.CAOS_CONNECTOR_KEY||'').trim(),MAX_CLIENTS=Math.max(1,Number(process.env.CAOS_MAX_CLIENTS||25));
const __filename=fileURLToPath(import.meta.url),ROOT=path.resolve(path.dirname(__filename),'..');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'};
function currentVersion(){try{return String(JSON.parse(fs.readFileSync(path.join(ROOT,'version.json'),'utf8')).version||'0.0.0')}catch{return'0.0.0'}}
function patchSharedVersion(html){const v=currentVersion();return html.replace(/Caos Live v\d+\.\d+\.\d+/g,`Caos Live v${v}`).replace(/Caos Admin v\d+\.\d+\.\d+/g,`Caos Admin v${v}`).replace(/VERSÃO v\d+\.\d+\.\d+/g,`VERSÃO v${v}`).replace(/PAINEL v\d+\.\d+\.\d+/g,`PAINEL v${v}`).replace(/const VERSION='\d+\.\d+\.\d+'/g,`const VERSION='${v}'`)}
function patchAdminHtml(html){const v=currentVersion();return patchSharedVersion(html)
.replace('<header class="top"><h1>CAOS <b>ADMIN</b></h1><a href="index.html">ABRIR JOGO</a></header>',`<header class="top"><div><h1>CAOS <b>ADMIN</b></h1><div style="display:inline-block;margin-top:6px;padding:4px 8px;border:1px solid #343b63;border-radius:999px;background:#0c1020;color:#aeb8df;font-size:10px;font-weight:900">VERSÃO v${v}</div></div><a href="index.html">ABRIR JOGO</a></header>`)
.replace('PRESET: 1 ROSA → ESPECTRO','PRESET: 1 CURTIDA → ESCUDO 30s').replace('value="Rosa" placeholder="Presente"','value="Curtida" placeholder="Evento"')
.replace("$('presetRose').onclick=()=>{rules.push({id:Date.now()+'-rose',gift:'Rosa',count:1,action:'spawn',mob:'wraith',value:1,cooldown:2});saveRules();$('liveStatus').textContent='Preset criado: 1 Rosa/Rose → 1 Espectro.'};","$('presetRose').onclick=()=>{rules=rules.filter(r=>norm(r.gift)!=='curtida');rules.push({id:Date.now()+'-like',gift:'Curtida',count:1,action:'invincible',mob:'wraith',value:30,cooldown:0});saveRules();$('liveEnabled').checked=true;localStorage.setItem(ENABLED_KEY,'1');$('liveStatus').textContent='Preset criado: 1 Curtida → Escudo por 30s.';};")
.replace("loadRules();cloudState('Cloud desconectado.');","loadRules();rules=rules.filter(r=>norm(r.gift)!=='curtida');rules.push({id:'default-like-shield-30',gift:'Curtida',count:1,action:'invincible',mob:'wraith',value:30,cooldown:0});$('liveEnabled').checked=true;localStorage.setItem(ENABLED_KEY,'1');saveRules();cloudState('Cloud desconectado.');")
.replace("if(d.type==='status'){if(d.status==='connecting')cloudState('Conectando à LIVE de @'+d.username+'...');if(d.status==='connected')","if(d.type==='debug'){const txt='📟 '+d.event+(d.user?' · @'+d.user:'')+(d.count?' · +'+d.count:'')+(d.mode?' · '+d.mode:'');$('liveStatus').textContent=txt;add(txt);return}if(d.type==='status'){if(d.status==='checking')cloudState('🔎 Verificando @'+d.username+' e procurando uma LIVE ativa...');if(d.status==='fallback')cloudState('🔄 Tentando modo gratuito legado...');if(d.status==='connecting')cloudState('📡 Conta localizada. Entrando na LIVE de @'+d.username+'...');if(d.status==='connected')")
.replace("cloudState('Solicitando conexão com @'+u+'...')","cloudState('🔎 Procurando @'+u+' no TikTok...')").replace("if(d.type==='error')cloudState('Erro: '+d.message,'err')","if(d.type==='error'){cloudState('❌ '+d.message,'err');$('liveStatus').textContent='Falha: '+d.message;add('TikTok: '+d.message)}")}
function serveFile(res,file){fs.readFile(file,(err,data)=>{if(err){res.writeHead(404,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});return res.end('Not found')}const ext=path.extname(file).toLowerCase();let body=data;if(ext==='.html'){const html=data.toString('utf8');body=Buffer.from(path.basename(file)==='painel.html'?patchAdminHtml(html):patchSharedVersion(html),'utf8')}res.writeHead(200,{'content-type':MIME[ext]||'application/octet-stream','cache-control':'no-store'});res.end(body)})}
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent((req.url||'/').split('?')[0]);if(pathname==='/health'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({ok:true,service:'caos-cloud-connector',version:currentVersion(),clients:wss.clients.size}))}if(pathname==='/'||pathname==='/admin')return serveFile(res,path.join(ROOT,'painel.html'));if(pathname==='/jogo')return serveFile(res,path.join(ROOT,'index.html'));const file=path.resolve(ROOT,pathname.replace(/^\/+/,''));if(!file.startsWith(ROOT)){res.writeHead(403);return res.end('Forbidden')}serveFile(res,file)});
const wss=new WebSocketServer({server});function safeSend(ws,p){if(ws.readyState===ws.OPEN)ws.send(JSON.stringify(p))}function dbg(ws,event,data={}){safeSend(ws,{type:'debug',event,...data,at:Date.now()})}
function normalizeGift(data={}){const user=data.user?.uniqueId||data.user?.unique_id||data.uniqueId||data.nickname||'viewer',gift=data.giftName||data.extendedGiftInfo?.name||data.gift?.name||`gift-${data.giftId||'unknown'}`,count=Number(data.repeatCount||data.repeat_count||data.count||1)||1,repeatEnd=data.repeatEnd??data.repeat_end??true,giftType=Number(data.giftType??data.gift_type??data.extendedGiftInfo?.type??0)||0;return{type:'gift',user,gift,count,giftId:data.giftId||data.gift_id||null,repeatEnd,giftType}}
function isSigningPaywall(e){const s=String(e?.message||e||'').toLowerCase();return s.includes('business plan')||s.includes('fetchwebcastsignature')||(s.includes('eulerstream')&&s.includes('sign'))}
async function closeLive(s){if(!s.live)return;try{s.live.removeAllListeners?.()}catch{}try{await s.live.disconnect?.()}catch{}s.live=null;s.username='';s.connecting=false;s.mode=''}
function emitLike(ws,data,mode){const user=data.user?.uniqueId||data.uniqueId||data.nickname||'viewer',count=Math.max(1,Number(data.likeCount||data.count||data.totalLikeCount||1)||1);dbg(ws,'LIKE RECEBIDO',{user,count,mode});safeSend(ws,{type:'gift',user,gift:'Curtida',count,giftId:`tiktok-like-${mode}`,repeatEnd:true,giftType:0})}
function attachModern(ws,live){live.on(WebcastEvent.GIFT,d=>{const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,mode:'modern'});if(g.giftType===1&&g.repeatEnd===false)return;safeSend(ws,g)});live.on(WebcastEvent.LIKE,d=>emitLike(ws,d,'modern'));live.on(WebcastEvent.CHAT,d=>{const user=d.user?.uniqueId||d.uniqueId||'viewer';dbg(ws,'CHAT RECEBIDO',{user,mode:'modern'});safeSend(ws,{type:'chat',user,comment:d.comment||''})});live.on('disconnected',()=>safeSend(ws,{type:'status',status:'disconnected'}));live.on('error',e=>dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'modern'}))}
function attachLegacy(ws,live){live.on('gift',d=>{const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,mode:'legacy'});if(g.giftType===1&&g.repeatEnd===false)return;safeSend(ws,g)});live.on('like',d=>emitLike(ws,d,'legacy'));live.on('chat',d=>{const user=d.uniqueId||'viewer';dbg(ws,'CHAT RECEBIDO',{user,mode:'legacy'});safeSend(ws,{type:'chat',user,comment:d.comment||''})});live.on('disconnected',()=>safeSend(ws,{type:'status',status:'disconnected'}));live.on('error',e=>dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'legacy'}))}
async function tryLegacy(ws,s,u,modernError){safeSend(ws,{type:'status',status:'fallback',username:u});const live=new WebcastPushConnection(u,{processInitialData:false,fetchRoomInfoOnConnect:true,enableExtendedGiftInfo:false,enableWebsocketUpgrade:true,requestPollingIntervalMs:1000});s.live=live;s.mode='legacy';attachLegacy(ws,live);try{const info=await live.connect();s.connecting=false;dbg(ws,'LIVE CONECTADA',{mode:'legacy'});safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'legacy'});return true}catch(e){s.connecting=false;await closeLive(s);safeSend(ws,{type:'error',message:`Fallback falhou: ${String(e?.message||e).slice(0,220)}`});return false}}
async function connectLive(ws,s,u){u=String(u||'').trim().replace(/^@/,'');if(!u)return safeSend(ws,{type:'error',message:'Informe o @usuario da LIVE.'});if(s.connecting)return safeSend(ws,{type:'error',message:'Conexão já em andamento.'});await closeLive(s);s.connecting=true;s.username=u;safeSend(ws,{type:'status',status:'checking',username:u});const live=new TikTokLiveConnection(u,{enableExtendedGiftInfo:false,processInitialData:false,fetchRoomInfoOnConnect:true});s.live=live;s.mode='modern';attachModern(ws,live);safeSend(ws,{type:'status',status:'connecting',username:u});try{const info=await live.connect();s.connecting=false;dbg(ws,'LIVE CONECTADA',{mode:'modern'});safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'modern'})}catch(e){try{live.removeAllListeners?.();await live.disconnect?.()}catch{}s.live=null;if(isSigningPaywall(e))return tryLegacy(ws,s,u,e);s.connecting=false;await closeLive(s);safeSend(ws,{type:'error',message:String(e?.message||e).slice(0,260)})}}
wss.on('connection',ws=>{if(wss.clients.size>MAX_CLIENTS){safeSend(ws,{type:'error',message:'Servidor temporariamente lotado.'});return ws.close(1013,'busy')}const s={authenticated:!ACCESS_KEY,live:null,username:'',connecting:false,mode:''};safeSend(ws,{type:'bridge',status:'ready',authRequired:Boolean(ACCESS_KEY)});ws.on('message',async raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='auth'){s.authenticated=!ACCESS_KEY||String(m.key||'')===ACCESS_KEY;return safeSend(ws,{type:'auth',ok:s.authenticated})}if(!s.authenticated)return safeSend(ws,{type:'error',message:'Chave do Caos Connector inválida.'});if(m.type==='connect')await connectLive(ws,s,m.username);if(m.type==='disconnect'){await closeLive(s);safeSend(ws,{type:'status',status:'disconnected'})}if(m.type==='ping')safeSend(ws,{type:'pong',at:Date.now(),mode:s.mode})});ws.on('close',()=>closeLive(s))});server.listen(PORT,'0.0.0.0',()=>console.log(`CAOS CLOUD CONNECTOR v${currentVersion()} diagnostics online :${PORT}`));