import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { WebSocketServer } from 'ws';
import { TikTokLiveConnection, WebcastEvent } from 'tiktok-live-connector';

const require=createRequire(import.meta.url);
const { WebcastPushConnection }=require('tiktok-live-connector-legacy');
const PORT=Number(process.env.PORT||8787),ACCESS_KEY=String(process.env.CAOS_CONNECTOR_KEY||'').trim(),MAX_CLIENTS=Math.max(1,Number(process.env.CAOS_MAX_CLIENTS||25));
const __filename=fileURLToPath(import.meta.url),ROOT=path.resolve(path.dirname(__filename),'..');
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'};

function currentVersion(){try{return String(JSON.parse(fs.readFileSync(path.join(ROOT,'version.json'),'utf8')).version||'0.0.0')}catch{return'0.0.0'}}
function patchSharedVersion(html){const v=currentVersion();return html.replace(/Caos Live v\d+\.\d+\.\d+/g,`Caos Live v${v}`).replace(/Caos Admin v\d+\.\d+\.\d+/g,`Caos Admin v${v}`).replace(/VERSÃO v\d+\.\d+\.\d+/g,`VERSÃO v${v}`).replace(/PAINEL v\d+\.\d+\.\d+/g,`PAINEL v${v}`).replace(/(<div class=\"version\">)v\d+\.\d+\.\d+/g,`$1v${v}`).replace(/(<div class=\"version\">PAINEL )v\d+\.\d+\.\d+/g,`$1v${v}`).replace(/const VERSION='\d+\.\d+\.\d+'/g,`const VERSION='${v}'`)}

function patchGameHtml(html){return patchSharedVersion(html)}


function patchAdminHtml(html){const v=currentVersion();let out=patchSharedVersion(html);const rep=(a,b)=>{if(out.includes(a))out=out.replace(a,b)};
 // v0.9.6 — Teste de Habilidades agora é nativo no painel.html
 if(!out.includes('id="skillTestSelect"')) rep('<h2>PROGRESSÃO</h2><div class="grid">','<h2>🧪 TESTE DE HABILIDADES</h2><div style="padding:13px;border:1px solid #283052;border-radius:15px;background:#080d19"><p class="hint" style="margin-top:0">Ative habilidades diretamente para testar sem depender do sorteio de level.</p><div class="tools" style="grid-template-columns:1fr 90px"><select id="skillTestSelect"><option value="speed">🥾 Passos de Guerra</option><option value="medic">🩹 Kit Médico</option><option value="rapid">⚡ Rajada Rápida</option><option value="regen">💚 Regeneração</option><option value="xp">✨ Instinto de Caça</option><option value="blood">🩸 Sanguinário</option><option value="flash">☀️ Flash de Luz</option><option value="arc">⚡ Arco Voltaico</option><option value="pact">◈ Pacto do Abismo · SECRETA</option></select><select id="skillTestLevel"><option value="1">LV1</option><option value="2">LV2</option><option value="3">LV3</option><option value="4">LV4</option><option value="5">LV5</option></select></div><div class="grid" style="margin-top:9px"><button id="skillApply" class="purple">ATIVAR SELECIONADA<small>aplica o nível escolhido</small></button><button id="skillAll" class="gold">ATIVAR TODAS<small>todas no LV escolhido</small></button><button id="skillReset" class="danger">RESETAR HABILIDADES<small>volta tudo para LV0</small></button><button id="skillMax" class="good">TODAS NO MÁXIMO<small>LV5 · secreta permanece LV1</small></button></div><div id="skillStateList" class="net" style="margin-top:10px;text-align:left">Skills do jogo: aguardando estado...</div></div><h2>PROGRESSÃO</h2><div class="grid">');
 rep("$('autoState').textContent=d.autoMode?'ON':'OFF'", "$('autoState').textContent=d.autoMode?'ON':'OFF';if($('skillStateList')&&d.skillLv){const names={speed:'Passos',medic:'Kit',rapid:'Rajada',regen:'Regen',xp:'XP',blood:'Sanguinário',flash:'Flash',arc:'Arco',pact:'Pacto'};$('skillStateList').textContent='Ativas: '+(Object.entries(d.skillLv).filter(([k,v])=>v>0).map(([k,v])=>(names[k]||k)+' LV'+v).join(' · ')||'nenhuma')}");
 rep("document.querySelectorAll('[data-speed]').forEach", "if($('skillTestSelect')){$('skillTestSelect').onchange=()=>{$('skillTestLevel').disabled=$('skillTestSelect').value==='pact';if($('skillTestSelect').value==='pact')$('skillTestLevel').value='1'};$('skillApply').onclick=()=>send({command:'skilltest',skill:$('skillTestSelect').value,level:+$('skillTestLevel').value||1},'🧪 Skill '+$('skillTestSelect').selectedOptions[0].textContent+' LV'+$('skillTestLevel').value);$('skillAll').onclick=()=>send({command:'skilltestall',level:+$('skillTestLevel').value||1},'🧪 Todas as skills LV'+$('skillTestLevel').value);$('skillMax').onclick=()=>send({command:'skilltestall',level:5},'🧪 Todas as skills no máximo');$('skillReset').onclick=()=>send({command:'skillreset'},'🧪 Habilidades resetadas')}document.querySelectorAll('[data-speed]').forEach");

 // v0.9.3 — telemetria de horda no painel
 rep('<div><span>MOBS</span><b id="mobs">—</b></div><div><span>ESTADO</span>','<div><span>MOBS</span><b id="mobs">—</b></div><div><span>HORDA</span><b id="hordeState">—</b></div><div><span>PROGRESSO</span><b id="hordeProgress">—</b></div><div><span>EXTRAS LIVE</span><b id="liveExtras">—</b></div><div><span>ESTADO</span>');
 rep("$('mobs').textContent=d.mobs;$('gameState').textContent","$('mobs').textContent=d.mobs;if($('hordeState'))$('hordeState').textContent=d.horde||1;if($('hordeProgress'))$('hordeProgress').textContent=(d.hordeKilled||0)+'/'+(d.hordeTarget||15);if($('liveExtras'))$('liveExtras').textContent=d.liveExtraMobs||0;$('gameState').textContent");

 rep('<header class="top"><h1>CAOS <b>ADMIN</b></h1><a href="index.html">ABRIR JOGO</a></header>',`<header class="top"><div><h1>CAOS <b>ADMIN</b></h1><div style="display:inline-block;margin-top:6px;padding:4px 8px;border:1px solid #343b63;border-radius:999px;background:#0c1020;color:#aeb8df;font-size:10px;font-weight:900">VERSÃO v${v}</div></div><a href="index.html">ABRIR JOGO</a></header>`);
 rep('PRESET: 1 ROSA → ESPECTRO','TESTE: 10 CURTIDAS → ESCUDO 3s');
 rep('<button class="good" data-cmd="auto" data-value="true">🤖 AUTO INTELIGENTE ON<small>anda e desvia dos mobs</small></button><button class="blue" data-cmd="auto" data-value="false">🕹 AUTO OFF<small>volta ao controle manual</small></button>','<button class="good" data-cmd="auto" data-value="true">🤖 AUTO INTELIGENTE ON<small>anda, desvia e escolhe skills</small></button><button class="blue" data-cmd="auto" data-value="false">🕹 AUTO OFF<small>volta ao controle manual</small></button><button class="good" data-cmd="horde" data-value="true">🌊 HORDAS ON<small>spawn normal + comentários mob</small></button><button class="purple" data-cmd="horde" data-value="false">🧪 SÓ MOB DO CHAT<small>desliga o spawn automático</small></button>');
 rep('<div class="switchRow"><input id="liveEnabled" type="checkbox"><label for="liveEnabled">Ativar ações automáticas de presentes</label></div>','<div class="switchRow"><input id="liveEnabled" type="checkbox"><label for="liveEnabled">Ativar ações automáticas de presentes</label></div><div style="margin:12px 0;padding:13px;border:1px solid #283052;border-radius:15px;background:#080d19"><b style="font-size:12px">CONTROLE DE MOBS DO CHAT · ANTI-LAG</b><p class="hint">Escolha pelo tamanho da LIVE. Você não precisa entender cooldown ou limite.</p><div class="grid" style="margin-top:10px"><button id="mobPresetLow" class="good">🟢 POUCOS ESPECTADORES<small>até ~50 · quase sem trava</small></button><button id="mobPresetMedium" class="blue">🟡 MÉDIO ESPECTADORES<small>restrição moderada</small></button><button id="mobPresetHigh" class="purple">🔴 MUITOS ESPECTADORES<small>proteção forte</small></button><button id="mobPresetMax" class="gold">⚡ LIBERAÇÃO MÁXIMA<small>sem trava por pessoa · horda OFF</small></button></div><div id="mobPresetStatus" class="net" style="margin-top:9px">Perfil atual: poucos espectadores</div><details style="margin-top:10px"><summary style="cursor:pointer;color:#aeb8df;font-size:11px;font-weight:900">⚙️ AVANÇADO</summary><div class="tools" style="grid-template-columns:1fr 1fr;margin-top:10px"><input id="mobCooldownInput" type="number" min="0" step="0.1" value="0.4" placeholder="Cooldown por pessoa (s)"><input id="mobLimitInput" type="number" min="1" max="100" value="20" placeholder="Mobs por 10s"></div><button id="mobAdvancedSave" class="btn" style="width:100%;margin-top:8px">SALVAR LIMITES MANUAIS</button></details></div>');
 // v0.10.3 — FPS toggle + sincronizacao LIVE sem tocar no nucleo do jogo
 rep('<div class="grid actionGrid">','<button id="fpsModeToggle" class="modeToggle" type="button" data-on="true" style="margin:0 0 12px"><span class="modeInfo"><span class="modeIcon">📊</span><span><b>MOSTRAR FPS</b><small>exibe ou oculta o contador no jogo</small></span></span><span class="modeRight"><span class="modeBadge">ON</span><span class="toggleTrack"><span class="toggleKnob"></span></span></span></button><div class="grid actionGrid">');
 rep("$('connect').onclick=()=>{retry=0;connect(false)};","window.caosAdminSend=send;$('connect').onclick=()=>{retry=0;connect(false)};");
 if(!out.includes('data-caos-admin-telemetry-v0103')){
   out=out.replace('</body>',`<script data-caos-admin-telemetry-v0103>
(()=>{
'use strict';
const fps=document.getElementById('fpsModeToggle'),liveBadge=document.getElementById('liveBadge'),status=document.getElementById('status');
let fpsOn=true,lastLive=null;try{fpsOn=localStorage.getItem('caos-show-fps')!=='0'}catch{}
function drawFps(){if(!fps)return;fps.dataset.on=fpsOn?'true':'false';fps.classList.toggle('isOn',fpsOn);const b=fps.querySelector('.modeBadge');if(b)b.textContent=fpsOn?'ON':'OFF'}
function send(data,label){if(typeof window.caosAdminSend==='function')return window.caosAdminSend(data,label);return false}
function syncFps(){drawFps();send({command:'fps',value:fpsOn},'📊 FPS '+(fpsOn?'ON':'OFF'))}
function liveNow(){const t=(liveBadge?.textContent||'').toUpperCase();return t.includes('LIVE CONECTADA')}
function syncLive(force=false){const on=liveNow();if(force||on!==lastLive){lastLive=on;send({command:'live-status',value:on},'📡 LIVE '+(on?'CONECTADA':'DESCONECTADA'))}}
if(fps){fps.onclick=()=>{fpsOn=!fpsOn;try{localStorage.setItem('caos-show-fps',fpsOn?'1':'0')}catch{}syncFps()};drawFps()}
if(liveBadge)new MutationObserver(()=>syncLive(false)).observe(liveBadge,{childList:true,subtree:true,characterData:true});
if(status)new MutationObserver(()=>{if((status.textContent||'').includes('CONECTADO AO JOGO')){setTimeout(()=>{syncFps();syncLive(true)},150)}}).observe(status,{childList:true,subtree:true,characterData:true});
setTimeout(()=>{syncFps();syncLive(true)},800);
})();
<\/script></body>`);
 }
 rep("let rules=[];const cooldowns=new Map();","let rules=[];const cooldowns=new Map();let liveLikeTotal=0,likeShieldProgress=0,likeShieldCooldownUntil=0,pendingShieldOwner='';const mobCommentLastByUser=new Map();let mobCommentWindow=[];let MOB_USER_COOLDOWN=400,MAX_MOB_COMMENTS_10S=20;const MOB_PROFILE_KEY='chaos-mob-profile-v1';");
 rep("function processGift(evt){","function setMobProfile(name,cooldownMs,limit,forceHordeOff=false){MOB_USER_COOLDOWN=Math.max(0,cooldownMs);MAX_MOB_COMMENTS_10S=Math.max(1,limit);localStorage.setItem(MOB_PROFILE_KEY,JSON.stringify({name,cooldownMs:MOB_USER_COOLDOWN,limit:MAX_MOB_COMMENTS_10S}));if($('mobCooldownInput'))$('mobCooldownInput').value=(MOB_USER_COOLDOWN/1000).toFixed(MOB_USER_COOLDOWN%1000?1:0);if($('mobLimitInput'))$('mobLimitInput').value=MAX_MOB_COMMENTS_10S;if($('mobPresetStatus'))$('mobPresetStatus').textContent='Perfil atual: '+name+' · '+(MOB_USER_COOLDOWN?MOB_USER_COOLDOWN/1000+'s por pessoa':'sem trava por pessoa')+' · até '+MAX_MOB_COMMENTS_10S+' mobs/10s';if(forceHordeOff)send({command:'horde',value:false},'🧪 Hordas desligadas automaticamente para '+name);add('Perfil MOB: '+name+' · '+MOB_USER_COOLDOWN+'ms · '+MAX_MOB_COMMENTS_10S+'/10s')}function loadMobProfile(){try{const p=JSON.parse(localStorage.getItem(MOB_PROFILE_KEY)||'null');if(p)setMobProfile(p.name||'personalizado',+p.cooldownMs||0,+p.limit||20,false);else setMobProfile('poucos espectadores',400,20,false)}catch{setMobProfile('poucos espectadores',400,20,false)}}function processLike(evt){const count=Math.max(1,+evt?.count||1),user='@'+String(evt?.user||'viewer').replace(/^@/,'');const before=liveLikeTotal;liveLikeTotal+=count;const oldMark=Math.floor(before/100),newMark=Math.floor(liveLikeTotal/100);if(newMark>oldMark){pendingShieldOwner=user;add('❤️ MARCO '+(newMark*100)+' · '+user)}const now=Date.now();if(now<likeShieldCooldownUntil){add('❤️ '+user+' +'+count+' · total '+liveLikeTotal+' · recarga');return}likeShieldProgress+=count;add('❤️ '+user+' +'+count+' · '+likeShieldProgress+'/10 · total '+liveLikeTotal);if(likeShieldProgress>=10){const owner=pendingShieldOwner;send({command:'invincible',seconds:3,user:owner||undefined},'🛡 Escudo 3s'+(owner?' · '+owner:''));likeShieldProgress=0;likeShieldCooldownUntil=now+13000;if(owner)pendingShieldOwner=''}}function spawnCommentMob(user){const now=Date.now(),key=String(user||'@viewer').toLowerCase();mobCommentWindow=mobCommentWindow.filter(t=>now-t<10000);if(MOB_USER_COOLDOWN>0&&now-(mobCommentLastByUser.get(key)||0)<MOB_USER_COOLDOWN){add('⏳ '+user+' aguardando recarga do MOB');return false}if(mobCommentWindow.length>=MAX_MOB_COMMENTS_10S){add('🛑 Anti-lag segurou novos MOBs · limite '+MAX_MOB_COMMENTS_10S+'/10s');$('liveStatus').textContent='🛑 Anti-lag ativo · aguardando a arena respirar';return false}mobCommentLastByUser.set(key,now);mobCommentWindow.push(now);return send({command:'spawn',amount:1,label:user},'👾 '+user+' entrou como MOB')}function processGift(evt){");
 rep("if(d.type==='gift'){processGift({gift:d.gift,count:d.count,user:'@'+(d.user||'viewer'),giftId:d.giftId});cloudState('🎁 @'+(d.user||'viewer')+' enviou '+d.count+'× '+d.gift,'ok')}","if(d.type==='like'){processLike(d);cloudState('❤️ @'+(d.user||'viewer')+' +'+d.count+' likes · total '+liveLikeTotal,'ok')}if(d.type==='gift'){processGift({gift:d.gift,count:d.count,user:'@'+(d.user||'viewer'),giftId:d.giftId});cloudState('🎁 @'+(d.user||'viewer')+' enviou '+d.count+'× '+d.gift,'ok')}");
 rep("if(d.type==='chat')$('liveStatus').textContent='💬 @'+(d.user||'viewer')+': '+(d.comment||'');","if(d.type==='chat'){const u='@'+String(d.user||'viewer').replace(/^@/,''),c=String(d.comment||'').trim();$('liveStatus').textContent='💬 '+u+': '+c;add('💬 '+u+': '+c);if(c.toLocaleLowerCase('pt-BR')==='mob')spawnCommentMob(u)}");
 rep("loadRules();cloudState('Cloud desconectado.');","loadRules();loadMobProfile();cloudState('Cloud desconectado.');$('mobPresetLow')?.addEventListener('click',()=>setMobProfile('poucos espectadores',400,20,false));$('mobPresetMedium')?.addEventListener('click',()=>setMobProfile('médio espectadores',1500,15,false));$('mobPresetHigh')?.addEventListener('click',()=>setMobProfile('muitos espectadores',3000,10,true));$('mobPresetMax')?.addEventListener('click',()=>setMobProfile('liberação máxima',0,25,true));$('mobAdvancedSave')?.addEventListener('click',()=>setMobProfile('personalizado',Math.max(0,+$('mobCooldownInput').value||0)*1000,Math.max(1,+$('mobLimitInput').value||20),false));");
 return out;
}

function serveFile(res,file){fs.readFile(file,(err,data)=>{if(err){res.writeHead(404,{'content-type':'text/plain; charset=utf-8','cache-control':'no-store'});return res.end('Not found')}const ext=path.extname(file).toLowerCase();let body=data;if(ext==='.html'){const html=data.toString('utf8'),name=path.basename(file);body=Buffer.from(name==='painel.html'?patchAdminHtml(html):name==='index.html'?patchGameHtml(html):patchSharedVersion(html),'utf8')}res.writeHead(200,{'content-type':MIME[ext]||'application/octet-stream','cache-control':'no-store'});res.end(body)})}
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent((req.url||'/').split('?')[0]);if(pathname==='/health'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({ok:true,service:'caos-cloud-connector',version:currentVersion(),clients:wss.clients.size}))}if(pathname==='/'||pathname==='/admin'||pathname==='/admin-latest'||pathname==='/painel.html')return serveFile(res,path.join(ROOT,'painel.html'));if(pathname==='/jogo')return serveFile(res,path.join(ROOT,'index.html'));const file=path.resolve(ROOT,pathname.replace(/^\/+/,''));if(!file.startsWith(ROOT)){res.writeHead(403);return res.end('Forbidden')}serveFile(res,file)});

const wss=new WebSocketServer({server});
function safeSend(ws,p){if(ws.readyState===ws.OPEN)ws.send(JSON.stringify(p))}
function dbg(ws,event,data={}){safeSend(ws,{type:'debug',event,...data,at:Date.now()})}
function deepValue(obj,keys,depth=0,seen=new Set()){if(!obj||typeof obj!=='object'||depth>5||seen.has(obj))return'';seen.add(obj);for(const k of keys){const v=obj[k];if(typeof v==='string'&&v.trim())return v.trim();if(typeof v==='number'&&Number.isFinite(v))return String(v)}for(const v of Object.values(obj)){if(v&&typeof v==='object'){const found=deepValue(v,keys,depth+1,seen);if(found)return found}}return''}
function getUser(data={}){return deepValue(data,['uniqueId','unique_id','uniqueID','userName','username','displayId','nickname','nickName'])||'viewer'}
function getComment(data={}){return deepValue(data,['comment','content','text','message','msg'])||''}
function normalizeGift(data={}){const user=getUser(data),gift=data.giftName||data.extendedGiftInfo?.name||data.gift?.name||deepValue(data,['giftName','gift_name'])||`gift-${data.giftId||'unknown'}`,count=Number(data.repeatCount||data.repeat_count||data.count||1)||1,repeatEnd=data.repeatEnd??data.repeat_end??true,giftType=Number(data.giftType??data.gift_type??data.extendedGiftInfo?.type??0)||0;return{type:'gift',user,gift,count,giftId:data.giftId||data.gift_id||null,repeatEnd,giftType}}
function isSigningPaywall(e){const s=String(e?.message||e||'').toLowerCase();return s.includes('business plan')||s.includes('fetchwebcastsignature')||(s.includes('eulerstream')&&s.includes('sign'))}
async function closeLive(s){if(!s.live)return;try{s.live.removeAllListeners?.()}catch{}try{await s.live.disconnect?.()}catch{}s.live=null;s.username='';s.connecting=false;s.mode=''}
function emitLike(ws,data,mode){const user=getUser(data),count=Math.max(1,Number(data.likeCount||data.count||data.totalLikeCount||deepValue(data,['likeCount','like_count'])||1)||1);dbg(ws,'LIKE RECEBIDO',{user,count,mode});safeSend(ws,{type:'like',user,count,mode})}
function emitChat(ws,data,mode){const user=getUser(data),comment=getComment(data);dbg(ws,'CHAT RECEBIDO',{user,mode,comment:comment.slice(0,80)});safeSend(ws,{type:'chat',user,comment})}
function attachModern(ws,live){live.on(WebcastEvent.GIFT,d=>{const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,mode:'modern'});if(g.giftType===1&&g.repeatEnd===false)return;safeSend(ws,g)});live.on(WebcastEvent.LIKE,d=>emitLike(ws,d,'modern'));const chatHandler=d=>emitChat(ws,d,'modern');live.on(WebcastEvent.CHAT,chatHandler);if(WebcastEvent.CHAT!=='chat')live.on('chat',chatHandler);live.on('comment',chatHandler);live.on('disconnected',()=>safeSend(ws,{type:'status',status:'disconnected'}));live.on('error',e=>dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'modern'}))}
function attachLegacy(ws,live){live.on('gift',d=>{const g=normalizeGift(d);dbg(ws,'GIFT RECEBIDO',{user:g.user,count:g.count,gift:g.gift,mode:'legacy'});if(g.giftType===1&&g.repeatEnd===false)return;safeSend(ws,g)});live.on('like',d=>emitLike(ws,d,'legacy'));live.on('chat',d=>emitChat(ws,d,'legacy'));live.on('comment',d=>emitChat(ws,d,'legacy'));live.on('disconnected',()=>safeSend(ws,{type:'status',status:'disconnected'}));live.on('error',e=>dbg(ws,'ERRO TIKTOK',{detail:String(e?.message||e).slice(0,180),mode:'legacy'}))}
async function tryLegacy(ws,s,u){safeSend(ws,{type:'status',status:'fallback',username:u});const live=new WebcastPushConnection(u,{processInitialData:false,fetchRoomInfoOnConnect:true,enableExtendedGiftInfo:false,enableWebsocketUpgrade:true,requestPollingIntervalMs:1000});s.live=live;s.mode='legacy';attachLegacy(ws,live);try{const info=await live.connect();s.connecting=false;safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'legacy'});return true}catch(e){s.connecting=false;await closeLive(s);safeSend(ws,{type:'error',message:`Fallback falhou: ${String(e?.message||e).slice(0,220)}`});return false}}
async function connectLive(ws,s,u){u=String(u||'').trim().replace(/^@/,'');if(!u)return safeSend(ws,{type:'error',message:'Informe o @usuario da LIVE.'});if(s.connecting)return;s.connecting=true;s.username=u;safeSend(ws,{type:'status',status:'checking',username:u});const live=new TikTokLiveConnection(u,{enableExtendedGiftInfo:false,processInitialData:false,fetchRoomInfoOnConnect:true});s.live=live;s.mode='modern';attachModern(ws,live);try{const info=await live.connect();s.connecting=false;safeSend(ws,{type:'status',status:'connected',username:u,roomId:info?.roomId||null,mode:'modern'})}catch(e){try{live.removeAllListeners?.();await live.disconnect?.()}catch{}s.live=null;if(isSigningPaywall(e))return tryLegacy(ws,s,u);s.connecting=false;safeSend(ws,{type:'error',message:String(e?.message||e).slice(0,260)})}}
wss.on('connection',ws=>{if(wss.clients.size>MAX_CLIENTS){safeSend(ws,{type:'error',message:'Servidor temporariamente lotado.'});return ws.close(1013,'busy')}const s={authenticated:!ACCESS_KEY,live:null,username:'',connecting:false,mode:''};safeSend(ws,{type:'bridge',status:'ready',authRequired:Boolean(ACCESS_KEY)});ws.on('message',async raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return}if(m.type==='auth'){s.authenticated=!ACCESS_KEY||String(m.key||'')===ACCESS_KEY;return safeSend(ws,{type:'auth',ok:s.authenticated})}if(!s.authenticated)return safeSend(ws,{type:'error',message:'Chave do Caos Connector inválida.'});if(m.type==='connect')await connectLive(ws,s,m.username);if(m.type==='disconnect'){await closeLive(s);safeSend(ws,{type:'status',status:'disconnected'})}if(m.type==='ping')safeSend(ws,{type:'pong',at:Date.now(),mode:s.mode})});ws.on('close',()=>closeLive(s))});
server.listen(PORT,'0.0.0.0',()=>console.log(`CAOS CLOUD CONNECTOR v${currentVersion()} mob traffic presets online :${PORT}`));