(()=>{'use strict';
if(window.CaosNecromancerCompanion)return;
const RUNTIME_MARKER='CAOS_NECROMANCER_V0_3';
function apply(source){
 if(typeof source!=='string'||source.includes(RUNTIME_MARKER))return source;
 if(!source.includes("function onKill(e,owner='p1'){")||!source.includes('function command(d){')||!source.includes('function drawEnemy(e,p){'))return source;
 const inject=`/*${RUNTIME_MARKER}*/
let necroEnabled=false,necroSummons=[],necroSeq=0,necroKillMeter=0,necroSoulLevel=1,necroSoulXp=0,necroSoulPoints=0,necroSoulKills=0;
let necroConfig={maxSummons:3,everyKills:25,hpScale:5,damageScale:.55,aggroPct:12};
let necroUpgrades={life:0,damage:0,regen:0,armor:0},necroHudReady=false,necroLastHudAt=0;
function necroClamp(v,a,b){return Math.max(a,Math.min(b,v))}
function necroXpNeed(){return Math.max(1,Math.round(18*Math.pow(1.28,Math.max(0,necroSoulLevel-1))))}
function necroBonuses(){return{life:1+necroUpgrades.life*.10,damage:1+necroUpgrades.damage*.08,regen:necroUpgrades.regen*.35,armor:Math.min(.65,necroUpgrades.armor*.04)}}
function necroEnsureHud(){if(necroHudReady)return;const stage=$('stage');if(!stage)return;necroHudReady=true;const wrap=document.createElement('div');wrap.id='necroHud';wrap.style.cssText='position:absolute;z-index:7;left:12px;bottom:74px;font:900 10px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#d1fae5;pointer-events:auto';wrap.innerHTML='<button id="necroHudBtn" style="border:1px solid #2f6f55;background:#0b1511;color:#d1fae5;border-radius:10px;padding:7px 9px;font-weight:950">☠ 0</button><div id="necroPanel" style="display:none;margin-top:6px;width:210px;padding:9px;border:1px solid #315f4d;border-radius:12px;background:#08100def"><div style="font-size:9px;letter-spacing:.12em;color:#a7f3d0">NECROMANTE</div><div id="necroPanelStats" style="margin:6px 0 8px;color:#d1fae5;font-size:9px;line-height:1.45"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px"><button data-necro-up="life">VIDA</button><button data-necro-up="damage">DANO</button><button data-necro-up="regen">REGEN</button><button data-necro-up="armor">ARMOR</button></div></div>';stage.appendChild(wrap);const panel=wrap.querySelector('#necroPanel'),btn=wrap.querySelector('#necroHudBtn');btn.onclick=()=>panel.style.display=panel.style.display==='none'?'block':'none';for(const b of panel.querySelectorAll('[data-necro-up]')){b.style.cssText='padding:6px;border:1px solid #315f4d;border-radius:8px;background:#0b1511;color:#d1fae5;font-size:8px;font-weight:950';b.onclick=()=>necroSpend(b.dataset.necroUp,1)}}
function necroRefreshHud(force=false){const now=performance.now();if(!force&&now<necroLastHudAt)return;necroLastHudAt=now+250;necroEnsureHud();const btn=$('necroHudBtn'),stats=$('necroPanelStats');if(btn)btn.textContent='☠ '+necroSoulPoints+' · '+necroSummons.length+'/'+necroConfig.maxSummons;if(stats)stats.innerHTML=(necroEnabled?'ATIVO':'DESATIVADO')+' · Alma Nv '+necroSoulLevel+'<br>XP '+Math.floor(necroSoulXp)+'/'+necroXpNeed()+' · Kills '+necroSoulKills+'<br>Vida +'+(necroUpgrades.life*10)+'% · Dano +'+(necroUpgrades.damage*8)+'%<br>Regen '+(necroUpgrades.regen*.35).toFixed(2)+'/s · Armor '+(necroUpgrades.armor*4)+'%'}
function necroRecalc(s,heal=false){const b=necroBonuses(),old=s.max||1,ratio=necroClamp((s.hp||old)/old,0,1),baseMax=Math.max(20,(s.necroSourceMax||20)*necroConfig.hpScale+(player.maxLife||100)*.65);s.max=Math.round(baseMax*b.life);s.hp=heal?s.max:Math.max(1,Math.round(s.max*ratio));s.necroDamage=Math.max(1,((s.necroSourceDamage||1)*necroConfig.damageScale+(player.damage||1)*.30)*b.damage);return s}
function necroRaiseFromEnemy(e,{forced=false,nearPlayer=false}={}){if(!e||(!necroEnabled&&!forced)||necroSummons.length>=necroConfig.maxSummons)return null;const now=performance.now(),bossMob=!!types[e.type]?.boss,slot=necroSummons.length,angle=(slot/Math.max(1,necroConfig.maxSummons))*Math.PI*2-Math.PI/2,spawnDist=nearPlayer?110+slot*8:0,spawnX=nearPlayer?player.x+Math.cos(angle)*spawnDist:e.x,spawnY=nearPlayer?player.y+Math.sin(angle)*spawnDist:e.y,s={id:'necro-'+(++necroSeq),type:e.type,tier:e.tier??0,evolution:e.evolution||1,r:e.r||14,speed:e.speed||types[e.type]?.s||70,x:spawnX,y:spawnY,hp:1,max:1,damage:e.damage||1,xp:0,dead:false,t:e.t||0,seed:e.seed||Math.random()*99,attackAt:0,attackFlash:0,facing:e.facing||'down',skinVariant:e.skinVariant||0,aiPhase:e.aiPhase||0,mvx:0,mvy:0,speedMul:1,necroAlly:true,necroSourceMax:Math.max(1,e.max||e.hp||types[e.type]?.h||20),necroSourceDamage:Math.max(1,e.damage||types[e.type]?.d||1),necroBoss:bossMob,necroKills:0,necroNextAttack:now+350,necroLastDamageAt:0,necroBorn:now,necroDuelTarget:null};necroRecalc(s,true);necroSummons.push(s);toast('☠ ERGA-SE · '+(types[e.type]?.name||'SOMBRA'));necroRefreshHud(true);return s}
function necroNaturalRaise(e,owner){if(!necroEnabled||owner==='necro'||necroSummons.length>=necroConfig.maxSummons)return;if(types[e.type]?.boss){necroRaiseFromEnemy(e);return}necroKillMeter++;if(necroKillMeter>=necroConfig.everyKills){necroKillMeter=0;necroRaiseFromEnemy(e)}}
function necroShadowById(id){return necroSummons.find(s=>!s.dead&&s.id===id)||null}
function necroReleaseDuel(s){const e=s?.necroDuelTarget;if(e&&e.necroDuelShadowId===s.id)delete e.necroDuelShadowId;if(s)s.necroDuelTarget=null}
function necroBindDuel(s,e){if(!s||!e||s.dead||e.dead)return false;const holder=necroShadowById(e.necroDuelShadowId);if(holder&&holder!==s)return false;necroReleaseDuel(s);s.necroDuelTarget=e;e.necroDuelShadowId=s.id;return true}
function necroNearestEnemy(s){const locked=s.necroDuelTarget;if(locked&&!locked.dead&&locked.hp>0)return locked;if(locked)necroReleaseDuel(s);let best=null,bd=720*720;for(const e of enemies){if(e.dead)continue;const holder=necroShadowById(e.necroDuelShadowId);if(holder&&holder!==s)continue;const dx=e.x-s.x,dy=e.y-s.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=e}}return best}
function necroEnemyTarget(e){if(!e||!e.necroDuelShadowId)return null;const s=necroShadowById(e.necroDuelShadowId);if(!s){delete e.necroDuelShadowId;return null}return s}
function necroRecordKill(s,e){if(s.necroDuelTarget===e)necroReleaseDuel(s);s.necroKills++;necroSoulKills++;necroSoulXp+=types[e.type]?.boss?5:e.tier===2?3:e.tier===1?2:1;while(necroSoulXp>=necroXpNeed()){necroSoulXp-=necroXpNeed();necroSoulLevel++;necroSoulPoints++;toast('☠ ALMA NV '+necroSoulLevel+' · +1 PONTO')}necroRefreshHud(true)}
function necroDamageShadow(s,raw){if(!s||s.dead)return;const amount=Math.max(1,(Number(raw)||0)*(1-necroBonuses().armor));s.hp=Math.max(0,s.hp-amount);s.necroLastDamageAt=performance.now();if(s.hp<=0){s.dead=true;necroReleaseDuel(s);toast('☠ UMA SOMBRA CAIU')}}
function necroSpend(key,levels=1,free=false){if(!Object.prototype.hasOwnProperty.call(necroUpgrades,key))return false;let n=Math.max(1,Math.min(20,+levels||1)),spent=0;while(n-->0&&(free||necroSoulPoints>0)){if(!free)necroSoulPoints--;necroUpgrades[key]++;spent++}if(spent){for(const s of necroSummons)if(!s.dead)necroRecalc(s,false);necroRefreshHud(true)}return spent>0}
function necroSeparateSummons(){for(let i=0;i<necroSummons.length;i++){const a=necroSummons[i];if(a.dead)continue;for(let j=i+1;j<necroSummons.length;j++){const b=necroSummons[j];if(b.dead)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r+10;if(d>=min)continue;if(d<.01){const ang=((i+1)*2.17+(j+1)*1.31)%(Math.PI*2);dx=Math.cos(ang);dy=Math.sin(ang);d=1}const push=(min-d)*.52,nx=dx/d,ny=dy/d;a.x-=nx*push;a.y-=ny*push;b.x+=nx*push;b.y+=ny*push}}}
function updateNecromancer(dt){necroEnsureHud();if(!necroEnabled&&necroSummons.length===0){necroRefreshHud();return}const now=performance.now(),bonus=necroBonuses();for(const s of necroSummons){if(s.dead)continue;s.t+=dt;if(bonus.regen>0&&now-s.necroLastDamageAt>1800)s.hp=Math.min(s.max,s.hp+bonus.regen*dt);const target=necroNearestEnemy(s);if(target){const dx=target.x-s.x,dy=target.y-s.y,d=Math.hypot(dx,dy)||1;s.facing=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');const contact=s.r+target.r+14;if(d>contact){const sp=Math.min(145,Math.max(68,s.speed*.78));s.x+=dx/d*sp*dt;s.y+=dy/d*sp*dt;s.speedMul=1}else{s.speedMul=0;necroBindDuel(s,target);if(now>=s.necroNextAttack){s.necroNextAttack=now+(s.necroBoss?520:680);hurtEnemy(target,s.necroDamage,'necro');target.attackFlash=.12;if(target.hp<=0&&!target.dead){target.dead=true;necroRecordKill(s,target);onKill(target,'necro')}}}}else{const seq=Number(String(s.id).replace('necro-',''))||1,a=seq*Math.PI*.75,tx=player.x+Math.cos(a)*105,ty=player.y+Math.sin(a)*105,dx=tx-s.x,dy=ty-s.y,d=Math.hypot(dx,dy)||1;if(d>22){s.x+=dx/d*75*dt;s.y+=dy/d*75*dt}}}
 necroSeparateSummons();
 for(const e of enemies){if(e.dead)continue;const s=necroEnemyTarget(e);if(!s)continue;const d=Math.hypot(e.x-s.x,e.y-s.y),reach=e.r+s.r+16;if(d<=reach&&now>=(e.necroNextDuelAttack||0)){e.necroNextDuelAttack=now+(types[e.type]?.boss?620:820);necroDamageShadow(s,e.damage)}}
 necroSummons=necroSummons.filter(s=>!s.dead);necroRefreshHud()}
function drawNecromancer(){if(!necroSummons.length)return;for(const s of necroSummons){const p=world(s.x,s.y);drawEnemy(s,p)}}
function necroForcedRaise(d){necroEnabled=true;const qty=Math.max(1,Math.min(12,+d.amount||1));for(let i=0;i<qty&&necroSummons.length<necroConfig.maxSummons;i++){const before=enemies.length,tier=d.tier==='2'||d.tier===2||d.tier==='corrupted'?2:d.tier==='1'||d.tier===1||d.tier==='elite'?1:null,mob=String(d.mob||'');if(mob==='colossus'||mob==='voidlord')boss(mob,tier);else spawn(mob||null,tier);if(enemies.length>before){const e=enemies[enemies.length-1];necroRaiseFromEnemy(e,{forced:true,nearPlayer:true});e.dead=true}}enemies=enemies.filter(e=>!e.dead);necroSeparateSummons();necroRefreshHud(true)}
function necromancerCommand(d){const c=d?.command;if(!c||!String(c).startsWith('necro_'))return false;if(c==='necro_config'){if(Object.prototype.hasOwnProperty.call(d,'enabled'))necroEnabled=!!d.enabled;necroConfig.maxSummons=Math.max(1,Math.min(12,+d.maxSummons||necroConfig.maxSummons));necroConfig.everyKills=Math.max(1,Math.min(250,+d.everyKills||necroConfig.everyKills));necroConfig.hpScale=Math.max(1,Math.min(20,+d.hpScale||necroConfig.hpScale));necroConfig.damageScale=Math.max(.1,Math.min(5,+d.damageScale||necroConfig.damageScale));necroConfig.aggroPct=Math.max(0,Math.min(100,Number.isFinite(+d.aggroPct)?+d.aggroPct:necroConfig.aggroPct));if(d.clear){for(const s of necroSummons)necroReleaseDuel(s);necroSummons=[]}while(necroSummons.length>necroConfig.maxSummons){const s=necroSummons.pop();necroReleaseDuel(s)}for(const s of necroSummons)necroRecalc(s,false);toast('☠ NECROMANTE · '+(necroEnabled?'ATIVO':'DESATIVADO'))}else if(c==='necro_raise')necroForcedRaise(d);else if(c==='necro_toggle'){necroEnabled=!!d.value}else if(c==='necro_clear'){for(const s of necroSummons)necroReleaseDuel(s);necroSummons=[]}else if(c==='necro_points'){necroSoulPoints+=Math.max(1,Math.min(100,+d.amount||1))}else if(c==='necro_upgrade')necroSpend(String(d.upgrade||'life'),Math.max(1,Math.min(20,+d.levels||1)),true);necroRefreshHud(true);return true}
window.__caosNecromancer={skinSource:'game-mob-renderer',fx:'off',snapshot:()=>({enabled:necroEnabled,skinSource:'game-mob-renderer',fx:'off',config:{...necroConfig},summons:necroSummons.map(s=>({id:s.id,type:s.type,tier:s.tier,hp:s.hp,max:s.max,damage:s.necroDamage,kills:s.necroKills,boss:s.necroBoss,x:s.x,y:s.y,duel:!!s.necroDuelTarget})),soulLevel:necroSoulLevel,soulXp:necroSoulXp,soulXpNeed:necroXpNeed(),soulPoints:necroSoulPoints,totalKills:necroSoulKills,upgrades:{...necroUpgrades}})};
`;
 let out=source.replace('function command(d){',inject+'function command(d){');
 out=out.replace("function onKill(e,owner='p1'){","function onKill(e,owner='p1'){necroNaturalRaise(e,owner);");
 out=out.replace('const chaseP=duoEnemyTarget(e);enemiesRuntime.updateChaseMotion(e,chaseP,','const chaseP=necroEnemyTarget(e)||duoEnemyTarget(e);enemiesRuntime.updateChaseMotion(e,chaseP,');
 out=out.replace('separateEnemies();resolvePlayerMobCollisions();','updateNecromancer(dt);separateEnemies();resolvePlayerMobCollisions();');
 out=out.replace('function tierAura(e,img,w,h,isBoss){','function tierAura(e,img,w,h,isBoss){if(e.necroAlly)return;');
 out=out.replace('function bossVariantAura(e,img,w,h){','function bossVariantAura(e,img,w,h){if(e.necroAlly)return;');
 out=out.replace("function drawEnemy(e,p){const c=types[e.type],isBoss=!!c.boss;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='#0008';","function drawEnemy(e,p){const c=types[e.type],isBoss=!!c.boss;ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle=e.necroAlly?'rgba(34,197,94,.34)':'#0008';");
 out=out.replace("ctx.shadowColor=isBoss?'#ef4444':c.c;ctx.shadowBlur=isBoss?(perfMode>=2?8:perfMode===1?14:24):0;drawOgreSkin(e,isBoss);","ctx.shadowColor=e.necroAlly?'transparent':(isBoss?'#ef4444':c.c);ctx.shadowBlur=e.necroAlly?0:(isBoss?(perfMode>=2?8:perfMode===1?14:24):0);drawOgreSkin(e,isBoss);");
 if(out.includes('drawLivePlusGhostAllies();drawPlayer();'))out=out.replace('drawLivePlusGhostAllies();drawPlayer();','drawLivePlusGhostAllies();drawNecromancer();drawPlayer();');
 else if(out.includes('drawDuoPlayer();drawPlayer();'))out=out.replace('drawDuoPlayer();drawPlayer();','drawDuoPlayer();drawNecromancer();drawPlayer();');
 return out;
}
window.CaosNecromancerCompanion=Object.freeze({apply,version:'0.3.0',marker:RUNTIME_MARKER,skinSource:'game-mob-renderer',fx:'off'});
})();