(()=>{'use strict';
if(window.CaosNecromancerCompanion)return;
const RUNTIME_MARKER='CAOS_NECROMANCER_V0_2';
function apply(source){
 if(typeof source!=='string'||source.includes(RUNTIME_MARKER))return source;
 if(!source.includes("function onKill(e,owner='p1'){")||!source.includes('function command(d){')||!source.includes('function drawEnemy(e,p){'))return source;
 const inject=`/*${RUNTIME_MARKER}*/
let necroEnabled=false,necroSummons=[],necroSeq=0,necroKillMeter=0,necroSoulLevel=1,necroSoulXp=0,necroSoulPoints=0,necroSoulKills=0;
let necroConfig={maxSummons:3,everyKills:25,hpScale:5,damageScale:.55,aggroPct:12};
let necroUpgrades={life:0,damage:0,regen:0,armor:0},necroHudReady=false,necroLastHudAt=0;
function necroClamp(v,a,b){return Math.max(a,Math.min(b,v))}
function necroXpNeed(){return Math.max(1,Math.round(18*Math.pow(1.28,Math.max(0,necroSoulLevel-1))))}
function necroBonuses(){return{life:1+necroUpgrades.life*.10,damage:1+necroUpgrades.damage*.08,regen:necroUpgrades.regen*.35,armor:Math.min(.65,necroUpgrades.armor*.04)}}
function necroEnsureHud(){if(necroHudReady)return;const stage=$('stage');if(!stage)return;necroHudReady=true;const wrap=document.createElement('div');wrap.id='necroHud';wrap.style.cssText='position:absolute;z-index:7;left:12px;bottom:74px;font:900 10px -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#e9d5ff;pointer-events:auto';wrap.innerHTML='<button id="necroHudBtn" style="border:1px solid #6d28d9;background:#0f0a1d;color:#e9d5ff;border-radius:10px;padding:7px 9px;font-weight:950;box-shadow:0 5px 18px #0008">☠ 0</button><div id="necroPanel" style="display:none;margin-top:6px;width:210px;padding:9px;border:1px solid #5b21b6;border-radius:12px;background:#090611ef;box-shadow:0 10px 30px #000b"><div style="font-size:9px;letter-spacing:.12em;color:#c4b5fd">NECROMANTE</div><div id="necroPanelStats" style="margin:6px 0 8px;color:#ddd6fe;font-size:9px;line-height:1.45"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px"><button data-necro-up="life">VIDA</button><button data-necro-up="damage">DANO</button><button data-necro-up="regen">REGEN</button><button data-necro-up="armor">ARMOR</button></div></div>';stage.appendChild(wrap);const panel=wrap.querySelector('#necroPanel'),btn=wrap.querySelector('#necroHudBtn');btn.onclick=()=>panel.style.display=panel.style.display==='none'?'block':'none';for(const b of panel.querySelectorAll('[data-necro-up]')){b.style.cssText='padding:6px;border:1px solid #4338ca;border-radius:8px;background:#11102a;color:#ddd6fe;font-size:8px;font-weight:950';b.onclick=()=>necroSpend(b.dataset.necroUp,1)}}
function necroRefreshHud(force=false){const now=performance.now();if(!force&&now<necroLastHudAt)return;necroLastHudAt=now+250;necroEnsureHud();const btn=$('necroHudBtn'),stats=$('necroPanelStats');if(btn)btn.textContent='☠ '+necroSoulPoints+' · '+necroSummons.length+'/'+necroConfig.maxSummons;if(stats)stats.innerHTML=(necroEnabled?'ATIVO':'DESATIVADO')+' · Alma Nv '+necroSoulLevel+'<br>XP '+Math.floor(necroSoulXp)+'/'+necroXpNeed()+' · Kills '+necroSoulKills+'<br>Vida +'+(necroUpgrades.life*10)+'% · Dano +'+(necroUpgrades.damage*8)+'%<br>Regen '+(necroUpgrades.regen*.35).toFixed(2)+'/s · Armor '+(necroUpgrades.armor*4)+'%'}
function necroRecalc(s,heal=false){const b=necroBonuses(),old=s.max||1,ratio=necroClamp((s.hp||old)/old,0,1),baseMax=Math.max(20,(s.necroSourceMax||20)*necroConfig.hpScale+(player.maxLife||100)*.65);s.max=Math.round(baseMax*b.life);s.hp=heal?s.max:Math.max(1,Math.round(s.max*ratio));s.necroDamage=Math.max(1,((s.necroSourceDamage||1)*necroConfig.damageScale+(player.damage||1)*.30)*b.damage);return s}
function necroRaiseFromEnemy(e,{forced=false,nearPlayer=false}={}){if(!e||(!necroEnabled&&!forced)||necroSummons.length>=necroConfig.maxSummons)return null;const now=performance.now(),bossMob=!!types[e.type]?.boss,slot=necroSummons.length,angle=(slot/Math.max(1,necroConfig.maxSummons))*Math.PI*2-Math.PI/2,spawnX=nearPlayer?player.x+Math.cos(angle)*95:e.x,spawnY=nearPlayer?player.y+Math.sin(angle)*95:e.y,s={id:'necro-'+(++necroSeq),type:e.type,tier:e.tier??0,evolution:e.evolution||1,r:e.r||14,speed:e.speed||types[e.type]?.s||70,x:spawnX,y:spawnY,hp:1,max:1,damage:e.damage||1,xp:0,dead:false,t:e.t||0,seed:e.seed||Math.random()*99,attackAt:0,attackFlash:0,facing:e.facing||'down',skinVariant:e.skinVariant||0,aiPhase:e.aiPhase||0,mvx:0,mvy:0,speedMul:1,necroSourceMax:Math.max(1,e.max||e.hp||types[e.type]?.h||20),necroSourceDamage:Math.max(1,e.damage||types[e.type]?.d||1),necroBoss:bossMob,necroKills:0,necroNextAttack:now+350,necroLastDamageAt:0,necroBorn:now};necroRecalc(s,true);necroSummons.push(s);toast('☠ ERGA-SE · '+(types[e.type]?.name||'SOMBRA'));necroRefreshHud(true);return s}
function necroNaturalRaise(e,owner){if(!necroEnabled||owner==='necro'||necroSummons.length>=necroConfig.maxSummons)return;if(types[e.type]?.boss){necroRaiseFromEnemy(e);return}necroKillMeter++;if(necroKillMeter>=necroConfig.everyKills){necroKillMeter=0;necroRaiseFromEnemy(e)}}
function necroNearestEnemy(s){let best=null,bd=720*720;for(const e of enemies){if(e.dead)continue;const dx=e.x-s.x,dy=e.y-s.y,d=dx*dx+dy*dy;if(d<bd){bd=d;best=e}}return best}
function necroRecordKill(s,e){s.necroKills++;necroSoulKills++;necroSoulXp+=types[e.type]?.boss?5:e.tier===2?3:e.tier===1?2:1;while(necroSoulXp>=necroXpNeed()){necroSoulXp-=necroXpNeed();necroSoulLevel++;necroSoulPoints++;toast('☠ ALMA NV '+necroSoulLevel+' · +1 PONTO')}necroRefreshHud(true)}
function necroDamageShadow(s,raw){if(!s||s.dead)return;const amount=Math.max(1,(Number(raw)||0)*(1-necroBonuses().armor));s.hp=Math.max(0,s.hp-amount);s.necroLastDamageAt=performance.now();if(s.hp<=0){s.dead=true;toast('☠ UMA SOMBRA CAIU')}}
function necroSpend(key,levels=1,free=false){if(!Object.prototype.hasOwnProperty.call(necroUpgrades,key))return false;let n=Math.max(1,Math.min(20,+levels||1)),spent=0;while(n-->0&&(free||necroSoulPoints>0)){if(!free)necroSoulPoints--;necroUpgrades[key]++;spent++}if(spent){for(const s of necroSummons)if(!s.dead)necroRecalc(s,false);necroRefreshHud(true)}return spent>0}
function updateNecromancer(dt){necroEnsureHud();if(!necroEnabled&&necroSummons.length===0){necroRefreshHud();return}const now=performance.now(),bonus=necroBonuses();for(const s of necroSummons){if(s.dead)continue;s.t+=dt;if(bonus.regen>0&&now-s.necroLastDamageAt>1800)s.hp=Math.min(s.max,s.hp+bonus.regen*dt);const target=necroNearestEnemy(s);if(target){const dx=target.x-s.x,dy=target.y-s.y,d=Math.hypot(dx,dy)||1;s.facing=Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up');if(d>s.r+target.r+12){const sp=Math.min(145,Math.max(68,s.speed*.78));s.x+=dx/d*sp*dt;s.y+=dy/d*sp*dt;s.speedMul=1}else{s.speedMul=0;if(now>=s.necroNextAttack){s.necroNextAttack=now+(s.necroBoss?520:680);hurtEnemy(target,s.necroDamage,'necro');target.attackFlash=.12;if(target.hp<=0&&!target.dead){target.dead=true;necroRecordKill(s,target);onKill(target,'necro')}}}}else{const seq=Number(String(s.id).replace('necro-',''))||1,a=seq*Math.PI*.75,tx=player.x+Math.cos(a)*105,ty=player.y+Math.sin(a)*105,dx=tx-s.x,dy=ty-s.y,d=Math.hypot(dx,dy)||1;if(d>22){s.x+=dx/d*75*dt;s.y+=dy/d*75*dt}}}
 if(necroConfig.aggroPct>0&&necroSummons.length){for(const e of enemies){if(e.dead)continue;let target=null,bd=Infinity;for(const s of necroSummons){if(s.dead)continue;const d=Math.hypot(e.x-s.x,e.y-s.y);if(d<bd){bd=d;target=s}}if(!target||bd>e.r+target.r+16)continue;if(Math.random()<(necroConfig.aggroPct/100)*dt*2.2)necroDamageShadow(target,e.damage)}}necroSummons=necroSummons.filter(s=>!s.dead);necroRefreshHud()}
function drawNecromancer(){if(!necroSummons.length)return;for(const s of necroSummons){const p=world(s.x,s.y);ctx.save();ctx.globalAlpha=.82;ctx.filter='hue-rotate(225deg) saturate(1.45) brightness(.72)';drawEnemy(s,p);ctx.filter='none';ctx.globalAlpha=.95;ctx.strokeStyle='#a855f7';ctx.shadowColor='#7e22ce';ctx.shadowBlur=14;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,s.r+7,0,Math.PI*2);ctx.stroke();ctx.restore()}}
function necroForcedRaise(d){necroEnabled=true;const qty=Math.max(1,Math.min(12,+d.amount||1));for(let i=0;i<qty&&necroSummons.length<necroConfig.maxSummons;i++){const before=enemies.length,tier=d.tier==='2'||d.tier===2||d.tier==='corrupted'?2:d.tier==='1'||d.tier===1||d.tier==='elite'?1:null,mob=String(d.mob||'');if(mob==='colossus'||mob==='voidlord')boss(mob,tier);else spawn(mob||null,tier);if(enemies.length>before){const e=enemies[enemies.length-1];necroRaiseFromEnemy(e,{forced:true,nearPlayer:true});e.dead=true}}enemies=enemies.filter(e=>!e.dead);necroRefreshHud(true)}
function necromancerCommand(d){const c=d?.command;if(!c||!String(c).startsWith('necro_'))return false;if(c==='necro_config'){if(Object.prototype.hasOwnProperty.call(d,'enabled'))necroEnabled=!!d.enabled;necroConfig.maxSummons=Math.max(1,Math.min(12,+d.maxSummons||necroConfig.maxSummons));necroConfig.everyKills=Math.max(1,Math.min(250,+d.everyKills||necroConfig.everyKills));necroConfig.hpScale=Math.max(1,Math.min(20,+d.hpScale||necroConfig.hpScale));necroConfig.damageScale=Math.max(.1,Math.min(5,+d.damageScale||necroConfig.damageScale));necroConfig.aggroPct=Math.max(0,Math.min(100,Number.isFinite(+d.aggroPct)?+d.aggroPct:necroConfig.aggroPct));if(d.clear)necroSummons=[];while(necroSummons.length>necroConfig.maxSummons)necroSummons.pop();for(const s of necroSummons)necroRecalc(s,false);toast('☠ NECROMANTE · '+(necroEnabled?'ATIVO':'DESATIVADO'))}else if(c==='necro_raise')necroForcedRaise(d);else if(c==='necro_toggle'){necroEnabled=!!d.value}else if(c==='necro_clear'){necroSummons=[]}else if(c==='necro_points'){necroSoulPoints+=Math.max(1,Math.min(100,+d.amount||1))}else if(c==='necro_upgrade')necroSpend(String(d.upgrade||'life'),Math.max(1,Math.min(20,+d.levels||1)),true);necroRefreshHud(true);return true}
window.__caosNecromancer={skinSource:'game-mob-renderer',snapshot:()=>({enabled:necroEnabled,skinSource:'game-mob-renderer',config:{...necroConfig},summons:necroSummons.map(s=>({id:s.id,type:s.type,tier:s.tier,hp:s.hp,max:s.max,damage:s.necroDamage,kills:s.necroKills,boss:s.necroBoss,x:s.x,y:s.y})),soulLevel:necroSoulLevel,soulXp:necroSoulXp,soulXpNeed:necroXpNeed(),soulPoints:necroSoulPoints,totalKills:necroSoulKills,upgrades:{...necroUpgrades}})};
`;
 let out=source.replace('function command(d){',inject+'function command(d){');
 out=out.replace("function onKill(e,owner='p1'){","function onKill(e,owner='p1'){necroNaturalRaise(e,owner);");
 out=out.replace('separateEnemies();resolvePlayerMobCollisions();','updateNecromancer(dt);separateEnemies();resolvePlayerMobCollisions();');
 out=out.replace('const c=d?.command;',"const c=d?.command;necromancerCommand(d);");
 if(out.includes('drawLivePlusGhostAllies();drawPlayer();'))out=out.replace('drawLivePlusGhostAllies();drawPlayer();','drawLivePlusGhostAllies();drawNecromancer();drawPlayer();');
 else if(out.includes('drawDuoPlayer();drawPlayer();'))out=out.replace('drawDuoPlayer();drawPlayer();','drawDuoPlayer();drawNecromancer();drawPlayer();');
 return out;
}
window.CaosNecromancerCompanion=Object.freeze({apply,version:'0.2.0',marker:RUNTIME_MARKER,skinSource:'game-mob-renderer'});
})();