import {createNecromancerPrototype,assertNecromancerPrototype} from './necromancer.mjs';assertNecromancerPrototype();
const c=document.getElementById('c'),x=c.getContext('2d'),soul=document.getElementById('soul'),panel=document.getElementById('panel'),stats=document.getElementById('stats');let W=0,H=0,last=performance.now(),spawn=0;const player={x:0,y:0,r:18,maxLife:100,damage:12},mobs=[],necro=createNecromancerPrototype();
function resize(){const d=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;c.width=W*d;c.height=H*d;x.setTransform(d,0,0,d,0,0);player.x=W/2;player.y=H/2}addEventListener('resize',resize);resize();
function addMob(){const a=Math.random()*Math.PI*2,d=Math.max(W,H)*.42,boss=Math.random()<.04;mobs.push({x:player.x+Math.cos(a)*d,y:player.y+Math.sin(a)*d,r:boss?24:11,hp:boss?180:30,max:boss?180:30,damage:boss?14:5,speed:boss?25:40,type:boss?'boss':'ogre',tier:boss?3:0,boss})}for(let i=0;i<22;i++)addMob();
document.getElementById('raise').onclick=()=>{const e=mobs.splice(Math.floor(Math.random()*mobs.length),1)[0];if(e)necro.raise(e,player)};soul.onclick=()=>panel.classList.toggle('show');panel.onclick=e=>{const k=e.target?.dataset?.up;if(k)necro.spendPoint(k,player)};
function nearest(a,list){let b=null,bd=Infinity;for(const q of list){const d=(q.x-a.x)**2+(q.y-a.y)**2;if(d<bd){bd=d;b=q}}return b}
function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;spawn-=dt;if(spawn<=0&&mobs.length<35){addMob();spawn=.35}const shadows=necro.snapshot().summons;
 for(const m of mobs){const target=Math.random()<.12&&shadows.length?nearest(m,shadows):player,dx=target.x-m.x,dy=target.y-m.y,d=Math.hypot(dx,dy)||1;m.x+=dx/d*m.speed*dt;m.y+=dy/d*m.speed*dt;if(target.id&&d<m.r+target.r+4)necro.damage(target.id,m.damage*dt*1.8)}
 for(const sh of shadows){const m=nearest(sh,mobs);if(!m)continue;const dx=m.x-sh.x,dy=m.y-sh.y,d=Math.hypot(dx,dy)||1;if(d>sh.r+m.r+8){const nx=sh.x+dx/d*85*dt,ny=sh.y+dy/d*85*dt;necro.move(sh.id,nx,ny)}else{m.hp-=sh.damage*dt*1.5;if(m.hp<=0){mobs.splice(mobs.indexOf(m),1);necro.recordKill(sh.id);addMob()}}}necro.update(dt);necro.removeDead();draw();requestAnimationFrame(frame)}
function draw(){x.fillStyle='#070913';x.fillRect(0,0,W,H);x.strokeStyle='#18213b';for(let g=0;g<W;g+=48){x.beginPath();x.moveTo(g,0);x.lineTo(g,H);x.stroke()}for(let g=0;g<H;g+=48){x.beginPath();x.moveTo(0,g);x.lineTo(W,g);x.stroke()}x.fillStyle='#67e8f9';x.beginPath();x.arc(player.x,player.y,player.r,0,7);x.fill();for(const m of mobs){x.fillStyle=m.boss?'#ef4444':'#f97316';x.beginPath();x.arc(m.x,m.y,m.r,0,7);x.fill()}const s=necro.snapshot();for(const sh of s.summons){x.save();x.shadowBlur=16;x.shadowColor='#a855f7';x.fillStyle='#7e22ce';x.beginPath();x.arc(sh.x,sh.y,sh.r+2,0,7);x.fill();x.restore();x.fillStyle='#111827';x.fillRect(sh.x-18,sh.y-sh.r-10,36,4);x.fillStyle='#c084fc';x.fillRect(sh.x-18,sh.y-sh.r-10,36*sh.life/sh.maxLife,4)}soul.textContent=`☠ ${s.soulPoints}`;stats.textContent=`Nv ${s.soulLevel} · XP ${Math.floor(s.soulXp)}/${s.soulXpNeed} · Invocados ${s.summons.length}/${s.maxSummons} · Kills ${s.totalSoulKills} · Vida +${s.upgrades.life*10}% · Dano +${s.upgrades.damage*8}%`}
requestAnimationFrame(frame);