const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const NECROMANCER_V0=Object.freeze({maxSummons:3,baseHpMultiplier:5,playerHpShare:.65,baseDamageMultiplier:.55,playerDamageShare:.30,soulXpPerKill:1,soulXpBase:18,soulXpGrowth:1.28,upgrades:Object.freeze({life:10,damage:8,regen:.35,armor:4})});
const need=(l,c)=>Math.max(1,Math.round(c.soulXpBase*Math.pow(c.soulXpGrowth,Math.max(0,l-1))));
const pub=s=>({id:s.id,type:s.type,tier:s.tier,boss:s.boss,x:s.x,y:s.y,r:s.r,life:s.life,maxLife:s.maxLife,damage:s.damage,kills:s.kills,dead:s.dead,createdAt:s.createdAt,sourceMax:s.sourceMax});
export function createNecromancerPrototype(options={}){const cfg={...NECROMANCER_V0,...options},state={summons:[],soulLevel:1,soulXp:0,soulPoints:0,totalSoulKills:0,upgrades:{life:0,damage:0,regen:0,armor:0},seq:0};
 const bonuses=()=>({lifeMul:1+state.upgrades.life*cfg.upgrades.life/100,damageMul:1+state.upgrades.damage*cfg.upgrades.damage/100,regenPerSecond:state.upgrades.regen*cfg.upgrades.regen,armorReduction:clamp(state.upgrades.armor*cfg.upgrades.armor/100,0,.65)});
 function recalc(s,p={}){const b=bonuses(),ratio=clamp(s.life/(s.maxLife||1),0,1),base=Math.max(20,s.sourceMax*cfg.baseHpMultiplier+(p.maxLife||100)*cfg.playerHpShare);s.maxLife=Math.round(base*b.lifeMul);s.life=Math.max(1,Math.round(s.maxLife*ratio));s.damage=Math.max(1,(s.sourceDamage*cfg.baseDamageMultiplier+(p.damage||1)*cfg.playerDamageShare)*b.damageMul);return s}
 function raise(e,p={}){if(!e||state.summons.length>=cfg.maxSummons)return null;const s={id:`shadow-${++state.seq}`,type:e.type||'normal',tier:e.tier??0,boss:!!e.boss||e.max>=100,x:e.x||0,y:e.y||0,r:e.r||14,sourceMax:Math.max(1,e.max||e.hp||20),sourceDamage:Math.max(1,e.damage||1),life:1,maxLife:1,damage:1,kills:0,dead:false,createdAt:performance.now(),lastDamageAt:0};recalc(s,p);s.life=s.maxLife;state.summons.push(s);return pub(s)}
 function move(id,x,y){const s=state.summons.find(q=>q.id===id&&!q.dead);if(!s)return false;s.x=x;s.y=y;return true}
 function damage(id,raw){const s=state.summons.find(q=>q.id===id&&!q.dead);if(!s)return null;const amount=Math.max(1,(Number(raw)||0)*(1-bonuses().armorReduction));s.life=Math.max(0,s.life-amount);s.lastDamageAt=performance.now();if(s.life<=0)s.dead=true;return{shadow:pub(s),damage:amount}}
 function recordKill(id,{soulXp=cfg.soulXpPerKill}={}){const s=state.summons.find(q=>q.id===id&&!q.dead);if(!s)return false;s.kills++;state.totalSoulKills++;state.soulXp+=Math.max(0,soulXp);while(state.soulXp>=need(state.soulLevel,cfg)){state.soulXp-=need(state.soulLevel,cfg);state.soulLevel++;state.soulPoints++}return true}
 function spendPoint(k,p={}){if(state.soulPoints<=0||!(k in state.upgrades))return false;state.soulPoints--;state.upgrades[k]++;state.summons.filter(s=>!s.dead).forEach(s=>recalc(s,p));return true}
 function update(dt){const b=bonuses(),now=performance.now();for(const s of state.summons)if(!s.dead&&b.regenPerSecond>0&&now-s.lastDamageAt>1800)s.life=Math.min(s.maxLife,s.life+b.regenPerSecond*dt)}
 function removeDead(){const d=state.summons.filter(s=>s.dead).map(pub);state.summons=state.summons.filter(s=>!s.dead);return d}
 const snapshot=()=>({soulLevel:state.soulLevel,soulXp:state.soulXp,soulXpNeed:need(state.soulLevel,cfg),soulPoints:state.soulPoints,totalSoulKills:state.totalSoulKills,upgrades:{...state.upgrades},summons:state.summons.map(pub),maxSummons:cfg.maxSummons});
 return Object.freeze({raise,move,damage,recordKill,spendPoint,update,removeDead,snapshot})}
export function assertNecromancerPrototype(){const n=createNecromancerPrototype({soulXpBase:2,soulXpGrowth:1}),s=n.raise({type:'ogre',max:20,damage:4},{maxLife:100,damage:10});if(!s||s.maxLife<=20)throw Error('Necromancer V0 raise');n.recordKill(s.id);n.recordKill(s.id);if(n.snapshot().soulPoints!==1)throw Error('Necromancer V0 soul');return true}