import fs from 'node:fs';
function patch(path,fn){const before=fs.readFileSync(path,'utf8'),after=fn(before);if(after===before)throw Error(path+': migration made no change');fs.writeFileSync(path,after)}
function one(src,from,to,label){if(src.includes(to))return src;const n=src.split(from).length-1;if(n!==1)throw Error(label+': expected one legacy match, got '+n);return src.replace(from,to)}

patch('src/game.js',src=>{
 src=one(src,"const types={wraith:{name:'Ogro Espectro',r:15,s:96,h:3,d:2,x:7,c:'#7c3aed'},reaper:{name:'Ogro Ceifador',r:21,s:67,h:8,d:4,x:18,c:'#0e7490'},infected:{name:'Ogro Infectado',r:17,s:76,h:5,d:3,x:10,c:'#4d7c0f'},crawler:{name:'Ogro das Sombras',r:16,s:124,h:4,d:2,x:9,c:'#1e293b'},eye:{name:'Ogro Observador',r:16,s:86,h:5,d:2,x:11,c:'#b91c1c'},brute:{name:'Ogro Brutamonte',r:24,s:54,h:14,d:5,x:24,c:'#92400e'},colossus:{name:'Ogro Colosso',r:42,s:42,h:100,d:8,x:150,c:'#991b1b',boss:1},voidlord:{name:'Ogro do Vazio',r:39,s:55,h:100,d:7,x:170,c:'#312e81',boss:1}};","const types=window.CaosMobs.createSoloMobTypes();",'mob catalog');
 src=one(src,"function enemyTier(){const r=Math.random();let corrupt=0,elite=0;if(level>=90){corrupt=.34;elite=.42}else if(level>=80){corrupt=.28;elite=.38}else if(level>=60){corrupt=.20;elite=.34}else if(level>=40){corrupt=.14;elite=.28}else{corrupt=level>=30?.12:level>=20?.08:level>=10?.035:0;elite=level>=30?.24:level>=15?.18:level>=5?.10:0}if(r<corrupt)return 2;if(r<corrupt+elite)return 1;return 0}","function enemyTier(){return window.CaosMobs.enemyTier(level)}",'enemy tier');
 src=one(src,"function enemyEvolution(tier){if(tier===1&&level>=40){const chance=level>=80?.90:level>=60?.65:level>=50?.35:.15;return Math.random()<chance?2:1}if(tier===2&&level>=60){const chance=level>=90?1:level>=80?.70:level>=70?.45:.20;return Math.random()<chance?2:1}return 1}","function enemyEvolution(tier){return window.CaosMobs.enemyEvolution(tier,level)}",'enemy evolution');
 src=one(src,"function bossTier(forced=null){if(forced===1||forced==='1'||forced==='elite')return 1;if(forced===2||forced==='2'||forced==='corrupted')return 2;if(forced===3||forced==='3'||forced==='normal')return 3;const r=Math.random();return r<.01?2:r<.07?1:3}","function bossTier(forced=null){return window.CaosMobs.bossTier(forced)}",'boss tier');
 src=one(src,"function furyProfile(stage){stage=Math.max(1,Math.min(10,stage||1));const speed={1:[.50,.80,5000],2:[.40,.60,5000],3:[.20,.40,5000],4:[.10,.30,4500],5:[0,.10,4000]};if(stage<=5){const [lo,hi,duration]=speed[stage],bonus=lo+Math.random()*(hi-lo);return{speedMul:1+bonus,resist:0,duration,label:'+'+Math.round(bonus*100)+'% VEL'}}const resist=[0,0,0,0,0,0,.05,.10,.15,.20,.25][stage],duration=stage===6?4000:stage===7?4000:stage===8?3500:3000;return{speedMul:1,resist,duration,label:'+'+Math.round(resist*100)+'% RESIST'}}","function furyProfile(stage){return window.CaosCombat.furyProfile(stage)}",'fury profile');
 src=one(src,"function furyResist(e){return performance.now()<(e?.furyUntil||0)?Math.max(0,Math.min(.5,e.furyResist||0)):0}","function furyResist(e){return window.CaosCombat.furyResist(e)}",'fury resist');
 src=one(src,"function hurtEnemy(e,amount,kind='normal'){if(!e||e.dead)return 0;const dealt=Math.max(0,(+amount||0)*(1-furyResist(e)));e.hp-=dealt;addDamageFx(e,dealt,kind);return dealt}","function hurtEnemy(e,amount,kind='normal'){const dealt=window.CaosCombat.applyEnemyDamage(e,amount);if(dealt>0)addDamageFx(e,dealt,kind);return dealt}",'damage');
 const old="const dir=playerFacing(player.aim),m=muzzleLocal(dir),pl=skillLv.pierce||0,il=skillLv.ice||0,xl=skillLv.explosive||0,bs=berserkerState();let pierceLeft=0,ice=false,explosive=false;if(xl){explosiveShotCounter++;const every=[0,14,13,12,11,10][xl];if(explosiveShotCounter>=every){explosiveShotCounter=0;explosive=true}}if(!explosive&&il){iceShotCounter++;if(iceShotCounter>=10){iceShotCounter=0;ice=true}}if(!explosive&&pl){pierceShotCounter++;const every=[0,12,11,10,9,8][pl];if(pierceShotCounter>=every){pierceShotCounter=0;pierceLeft=[0,2,3,4,5,7][pl]}}";
 const neu="const dir=playerFacing(player.aim),m=muzzleLocal(dir),bs=berserkerState(),traits=window.CaosCombat.projectileTraits({pierce:skillLv.pierce||0,ice:skillLv.ice||0,explosive:skillLv.explosive||0},{pierce:pierceShotCounter,ice:iceShotCounter,explosive:explosiveShotCounter}),pierceLeft=traits.pierceLeft,ice=traits.ice,explosive=traits.explosive;pierceShotCounter=traits.counters.pierce;iceShotCounter=traits.counters.ice;explosiveShotCounter=traits.counters.explosive;";
 return one(src,old,neu,'projectile traits');
});

patch('scripts/check-game.mjs',src=>one(src,"game=read('src/game.js')+'\\n'+read('src/core/skills.mjs')","game=read('src/game.js')+'\\n'+read('src/core/skills.mjs')+'\\n'+read('src/core/mobs.mjs')+'\\n'+read('src/core/combat.mjs')",'check-game aggregate'));

patch('scripts/check-architecture.mjs',src=>{
 src=one(src,"} from '../src/core/skills.mjs';","} from '../src/core/skills.mjs';\nimport { assertMobDomain } from '../src/core/mobs.mjs';\nimport { assertCombatDomain } from '../src/core/combat.mjs';",'architecture imports');
 src=one(src,"const skillsSource = read('src/core/skills.mjs');","const skillsSource = read('src/core/skills.mjs');\nconst mobsSource = read('src/core/mobs.mjs');\nconst combatSource = read('src/core/combat.mjs');\nconst soloContractView = solo+'\\n'+mobsSource+'\\n'+combatSource;",'architecture sources');
 src=src.replace("[['solo', solo], ['multiplayer server', mpServer]]","[['solo', soloContractView], ['multiplayer server', mpServer]]");
 src=src.replaceAll("if (!solo.includes(sig))","if (!soloContractView.includes(sig))");
 src=one(src,"// Phase 2: Skills are a real domain now, not an inline catalog in game.js.","try { assertMobDomain(); ok('mob domain behavior validates'); } catch (error) { fail(error.message); }\ntry { assertCombatDomain(); ok('combat domain behavior validates'); } catch (error) { fail(error.message); }\nfor (const token of ['window.CaosMobs.createSoloMobTypes','window.CaosCombat.applyEnemyDamage','window.CaosCombat.projectileTraits']) solo.includes(token)?ok('domain bridge present: '+token):fail('domain bridge missing: '+token);\n\n// Phase 2: Skills are a real domain now, not an inline catalog in game.js.",'architecture guards');
 return src;
});
console.log('Phase 3 migration applied safely');
