import fs from 'node:fs';
const p='src/game.js';let s=fs.readFileSync(p,'utf8');
function one(from,to,label){if(s.includes(to))return;const n=s.split(from).length-1;if(n!==1)throw Error(`${label}: expected 1 match, got ${n}`);s=s.replace(from,to)}
one("meteorConfig={interval:1.7,warning:1.8,radius:92,playerDamage:18,mobDamage:20,batch:1}","meteorConfig={...window.CaosEvents.METEOR_DEFAULTS}",'meteor defaults');
one("function addDamageFx(e,amount,kind='normal'){if(!e||!Number.isFinite(amount)||amount<=0)return;const now=performance.now(),last=damageFx.length?damageFx[damageFx.length-1]:null;if(last&&last.e===e&&now-last.at<115&&last.kind===kind){last.amount+=amount;last.at=now;return}damageFx.push({e,amount,kind,at:now,x:e.x,y:e.y});if(damageFx.length>48)damageFx.splice(0,damageFx.length-48)}","function addDamageFx(e,amount,kind='normal'){window.CaosEffects.coalesceDamageFx(damageFx,{entity:e,amount,kind,now:performance.now()})}",'damage fx');
one("function clampEventNumber(v,min,max,fallback){v=Number(v);return Number.isFinite(v)?Math.max(min,Math.min(max,v)):fallback}","function clampEventNumber(v,min,max,fallback){return window.CaosEvents.clampEventNumber(v,min,max,fallback)}",'event clamp');
one("function applyMeteorConfig(d={},persist=true){meteorConfig.interval=clampEventNumber(d.interval,.45,12,meteorConfig.interval);meteorConfig.warning=clampEventNumber(d.warning,.6,5,meteorConfig.warning);meteorConfig.radius=clampEventNumber(d.radius,45,180,meteorConfig.radius);meteorConfig.playerDamage=clampEventNumber(d.playerDamage,1,80,meteorConfig.playerDamage);meteorConfig.mobDamage=clampEventNumber(d.mobDamage,1,100,meteorConfig.mobDamage);meteorConfig.batch=Math.round(clampEventNumber(d.batch,1,25,meteorConfig.batch));if(persist)saveMeteorConfig()}","function applyMeteorConfig(d={},persist=true){meteorConfig=window.CaosEvents.normalizeMeteorConfig(d,meteorConfig);if(persist)saveMeteorConfig()}",'meteor config');
one("function scheduleMeteor(){const halfW=Math.max(170,W*.43),halfH=Math.max(170,H*.43),near=Math.random()<.28,spread=near?110:1,x=near?player.x+(Math.random()*2-1)*spread:player.x+(Math.random()*2-1)*halfW,y=near?player.y+(Math.random()*2-1)*spread:player.y+(Math.random()*2-1)*halfH;meteors.push({x,y,r:meteorConfig.radius,warningLeft:meteorConfig.warning,warningTotal:meteorConfig.warning,hit:false,life:0});if(meteors.length>90)meteors.splice(0,meteors.length-90)}","function scheduleMeteor(){window.CaosEffects.pushTimedFx(meteors,window.CaosEvents.createMeteorSchedule({player,W,H,config:meteorConfig}),{max:90})}",'meteor schedule');
one("function meteorKiller(m){return{eventName:'CHUVA DE METEORO',type:null,tier:0,x:m.x,y:m.y,r:m.r,dead:false}}","function meteorKiller(m){return window.CaosEvents.meteorKiller(m)}",'meteor killer');
fs.writeFileSync(p,s);console.log('Phase 4 migration applied');
