import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8'), exists=p=>fs.existsSync(p);
let failed=false;const ok=m=>console.log('OK:',m),fail=m=>{failed=true;console.error('FAIL:',m)};
const version=JSON.parse(read('version.json')).version,tag=version.replace(/\./g,''),index=read('index.html'),panel=read('painel.html'),game=read('src/game.js'),panelJs=read('src/panel.js'),mapRuntime=read('src/map-runtime.js');
if(!index.includes(version))fail('HTML do jogo fora da versao '+version);else ok('versao sincronizada '+version);
if(!panel.includes(version))fail('painel fora da versao '+version);else ok('painel versionado');
if(!index.includes(`src/game.js?v=${tag}`))fail('cache tag game.js incorreta');else ok('cache tag game.js '+tag);
if(!panel.includes(`src/panel.js?v=${tag}`))fail('cache tag panel.js incorreta');else ok('cache tag panel.js '+tag);
if(!panel.includes(`src/panel.css?v=${tag}`))fail('cache tag panel.css incorreta');else ok('cache tag panel.css '+tag);
if(!panel.includes('mobileVersion'))fail('versao mobile ausente');else ok('versao visivel no mobile');
if(!panelJs.includes("fetch('./version.json'"))fail('painel nao consulta version.json');else ok('painel consulta version.json');
if(!panelJs.includes('VERSION MISMATCH'))fail('painel nao compara versao');else ok('painel compara jogo x painel');
if(!game.includes('startButton.onclick'))fail('handler do PLAY ausente');else ok('handler do PLAY');
if(!game.includes("target.up=ordered.slice(0,4);target.down=ordered.slice(4,8);target.left=ordered.slice(8,12);target.right=ordered.slice(12,16)"))fail('mapeamento Colosso incorreto');else ok('Colosso 01-04 UP, 05-08 DOWN, 09-12 LEFT, 13-16 RIGHT');
if(game.includes("if(type==='colossus'&&(dir==='up'||dir==='down'))"))fail('inversao dupla de boss voltou');else ok('sem inversao dupla no render');
if(!game.includes('armorReduction:0'))fail('reset de Armadura ausente');else ok('reset de Armadura');
for(const p of ['assets/bosses/Ogroboss1.zip','assets/bosses/Ogro2.0Boss.zip'])exists(p)?ok(p):fail('ausente '+p);
if(!game.includes("case 'like':"))fail('curtidas TikTok nao tratadas');else ok('curtidas TikTok tratadas');
if(!game.includes('bossamount'))fail('quantidade de boss nao enviada');else ok('quantidade de boss enviada');
if(!game.includes('amount:bossAmount'))fail('quantidade de boss nao aplicada');else ok('quantidade de boss aplicada');
if(!game.includes('tryPhoenix'))fail('dano fatal admin nao tratado');else ok('dano fatal admin tratado');
if(!game.includes('MAX_ENEMIES=320'))fail('anti-lag MOB ausente');else ok('anti-lag MOB ativo');
if(game.includes('cloudPatchGameplay'))fail('Cloud muta gameplay');else ok('Cloud nao muta gameplay');
if(panelJs.includes('legacyInject'))fail('painel legado injetado');else ok('Painel nativo sem injecao legada');
if(!exists('assets/mobs/Ogro Elite/frame_001.png')||!exists('assets/mobs/Ogro Elite/frame_032.png'))fail('pasta Ogro Elite incompleta');else ok('pasta Ogro Elite pronta');
if(!game.includes("gameplayMode='classic'"))fail('Classico nao e padrao');else ok('Classico por padrao');
if(!game.includes("gameplayMode==='sweep'"))fail('Varredura ausente');else ok('Varredura presente');
if(!game.includes("gameplayMode==='hardcore'"))fail('Hardcore ausente');else ok('Hardcore presente');
if(!game.includes('Math.PI/3'))fail('cone Varredura nao e 120 graus');else ok('cone Varredura 120 graus');
if(!game.includes("gameplayMode==='sweep'&&autoFire"))fail('Varredura pode atirar sem alvo');else ok('Varredura nao atira sem alvo');
if(!game.includes('gameplaymode'))fail('comando gameplaymode ausente');else ok('comando gameplaymode');
if(!game.includes('gameplayMode,'))fail('telemetria gameplay ausente');else ok('telemetria gameplay');
if(!panelJs.includes("command:'gameplaymode'"))fail('painel nao envia gameplaymode');else ok('painel envia gameplaymode');
if(!panelJs.includes('gameplaySelect'))fail('painel nao sincroniza gameplay');else ok('painel sincroniza gameplay');
if(!game.includes('cropAlphaFrame'))fail('arma nao normaliza margens');else ok('arma normaliza margens transparentes');
if(game.includes('01711'))fail('cache legado 01711');else ok('sem cache legado 01711');
if(!game.includes("const VERSION='"))fail('cache de assets nao deriva da versao');else ok('cache de assets deriva da versao');
if(!game.includes('ratio=iw/Math.max(1,ih)'))fail('weapon ratio nao preservado');else ok('weapon canvas ratio preservado');
if(!game.includes('eliteOgreFrames'))fail('pack Ogro Elite ausente');else ok('pack Ogro Elite configurado');
if(!game.includes("loadDirectPngSequence('./assets/mobs/Ogro Elite',32"))fail('32 frames Elite nao carregados');else ok('32 frames Elite carregados');
if(!game.includes('e.tier===1&&eliteOgreReady'))fail('tier Elite nao usa skin');else ok('tier Elite usa skin Ogro Elite');
if(game.includes('MOB_SCALE_LEGACY'))fail('escala visual legada presente');else ok('escala visual legada removida');
if(!game.includes('normal:62,elite:86,bossScale:3.55'))fail('regua visual incorreta');else ok('regua visual normal 62 / elite 86 / boss x3.55');
if(!game.includes('MOB_VISUAL_HEIGHT.elite'))fail('Elite sem escala dedicada');else ok('Elite usa escala visual dedicada');
if(!game.includes('BOSS_VARIANTS'))fail('Boss raros ausentes');else ok('Boss Elite/Corrompido balanceados');
if(!game.includes('r<.01?2:r<.07?1:3'))fail('chance Boss 93/6/1 incorreta');else ok('Boss natural 93/6/1');
if(!game.includes('forcedTier'))fail('Boss nao aceita tier forcado');else ok('Boss aceita tier forcado');
if(!game.includes('bossVariantAura'))fail('aura Boss raro ausente');else ok('aura de Boss raro');
if(!game.includes('CORROMPIDO'))fail('rotulo Boss raro ausente');else ok('rotulo Elite/Corrompido no Boss');
if(!game.includes('bosstier'))fail('Admin nao controla tier do Boss');else ok('Admin controla tier do Boss');
if(!panelJs.includes('bossTier'))fail('painel nao envia tier de Boss');else ok('painel envia tier de Boss');
if(!index.includes(`src/map-runtime.js?v=${tag}`))fail('map-runtime cache incorreto');else ok('map-runtime cache '+tag);
if(!game.includes("map:'snow-frost-puzzle'"))fail('mapa ativo nao e snow-frost-puzzle');else ok('mapa ativo snow-frost-puzzle');
if(!mapRuntime.includes("active:'snow-frost'"))fail('runtime Snow Frost ausente');else ok('runtime Snow Frost Puzzle');
if(!mapRuntime.includes("seed:'ICE-BMFSXT'"))fail('seed Snow Frost incorreto');else ok('seed Snow Frost ICE-BMFSXT');
for(const p of ['assets/Map/dense-forest/tiles/tile_001.png','assets/Map/dense-forest/tiles/tile_010.png','assets/Map/dense-forest/decals/decal_015.png','assets/Map/dense-forest/obstacles/obstacle_021.png'])exists(p)?ok('map asset '+p):fail('ausente '+p);
for(const p of ['field','wasteland','extras-uploaded'])exists('assets/Map/'+p)?fail('mapa antigo presente: '+p):ok('mapa antigo removido: '+p);
exists('assets/CAOS_LIVE_WORLDS_FINAL_CORRIGIDO.zip')?fail('ZIP antigo ainda presente'):ok('ZIP extraido e removido');
const worlds=['dense-forest','cave-mines','desert-canyon','ruined-city','shadow-corruption','snow-frost'];
if(!worlds.every(w=>exists('assets/Map/'+w)))fail('mundos novos incompletos');else ok('6 mundos novos organizados');
for(const p of ['map-lab.html','src/map-lab.js'])exists(p)?ok('map lab '+p):fail('ausente '+p);
const mapLab=read('map-lab.html'),mapLabJs=read('src/map-lab.js');
if(!mapLab.includes(`src/map-lab.js?v=${tag}`))fail('map lab cache incorreto');else ok('map lab cache '+tag);
if(!mapLabJs.includes('mask'))fail('autotile mask ausente');else ok('map lab autotile mask');
if(!mapLabJs.includes('bridge'))fail('ponte contextual ausente');else ok('map lab ponte contextual');
if(!mapLabJs.includes('snow-frost'))fail('Map Lab nao usa Snow Frost');else ok('map lab usa Snow Frost Puzzle real');
if(!mapLabJs.includes('CHUNK'))fail('Map Lab sem chunks');else ok('Map Lab em chunks Snow Frost');
if(!mapLabJs.includes('variant'))fail('variacoes chunks ausentes');else ok('variacoes de chunks ativas');
if(!mapLabJs.includes('N')||!mapLabJs.includes('E')||!mapLabJs.includes('S')||!mapLabJs.includes('W'))fail('validacao N/E/S/W ausente');else ok('validacao N/E/S/W ativa');
const mf=JSON.parse(read('assets/Map/snow-frost/manifest.json'));
if(mf.format!==3)fail('manifest Snow Frost formato incorreto');else ok('manifest Snow Frost formato 3');
if(!Array.isArray(mf.chunks)||mf.chunks.length!==32)fail('Snow Frost nao tem 32 chunks');else ok('32 chunks Snow Frost');
for(const p of ['assets/Map/snow-frost/chunks/mask_00_closed_v01.png','assets/Map/snow-frost/chunks/mask_05_straight_ns_v02.png','assets/Map/snow-frost/chunks/mask_10_straight_ew_v02.png','assets/Map/snow-frost/chunks/mask_15_cross_v02.png'])exists(p)?ok('snow puzzle '+p):fail('ausente '+p);
exists('CAOS_LIVE_SNOW_FROST_PUZZLE_FINAL.zip')?fail('ZIP Snow Frost ainda presente'):ok('ZIP Snow Frost extraido e removido');
if(!mapRuntime.includes('MAP_N=6,DENSITY=.85,VARIANT=.32'))fail('runtime puzzle parametros incorretos');else ok('runtime puzzle 6x6 85/32');
if(!mapRuntime.includes('manifest.json'))fail('runtime nao carrega manifest');else ok('runtime carrega manifest Snow Frost');
if(!mapRuntime.includes('resolveCollisions'))fail('colisoes Snow Frost ausentes');else ok('colisoes Snow Frost integradas');
for(const p of ['duo.html','src/duo.js'])exists(p)?ok('duo '+p):fail('ausente '+p);
const duoHtml=read('duo.html'),duoJs=read('src/duo.js');
if(!duoHtml.includes(version))fail('duo HTML fora da versao');else ok('duo HTML versionado');
if(!duoHtml.includes(`src/duo.js?v=${tag}`))fail('cache duo.js incorreto');else ok('cache duo.js '+tag);
if(!duoHtml.includes(`src/map-runtime.js?v=${tag}`))fail('duo map runtime fora da versao');else ok('duo usa map runtime sincronizado');
if(!game.includes('duoPlayer='))fail('estado P2 ausente');else ok('estado P2 no host');
if(!game.includes("d?.type==='duo-hello'"))fail('handshake P2 ausente');else ok('handshake P2');
if(!game.includes("d?.type==='duo-input'"))fail('input P2 ausente');else ok('input P2');
if(!game.includes("type:'duo-snapshot'"))fail('snapshot P2 ausente');else ok('snapshot P2');
if(!game.includes("owner:'p2'"))fail('tiro P2 ausente');else ok('tiro P2 autoritativo');
if(!index.includes('duoInviteBtn'))fail('atalho P2 ausente');else ok('atalho P2 no jogo');
if(!mapRuntime.includes('cfg.extraPlayers?.()'))fail('P2 sem colisao do mapa');else ok('P2 usa colisoes do mapa');
if(!duoJs.includes("peer.connect('chaos-live-'+room.toLowerCase()")) fail('P2 nao usa mesma sala PeerJS'); else ok('P2 usa mesmo codigo da sala');
if(process.exitCode) process.exit(process.exitCode);

// v0.17.26 · duo aggro
if(!game.includes('function duoEnemyTarget(e)')) fail('aggro nearest-player ausente'); else ok('aggro escolhe player mais proximo');
if(!game.includes("toast('P2 CAIU · REVIVE 5s')")) fail('queda/revive P2 ausente'); else ok('P2 recebe dano e revive');
if(!game.includes('chaseP=duoEnemyTarget(e)')) fail('mobs nao perseguem P2'); else ok('mobs perseguem P1/P2');
if(process.exitCode) process.exit(process.exitCode);

// v0.17.27+ · visual parity; v0.17.28 permits lazy/nonessential packs
const duoHtmlV27=read('duo.html'),duoJsV27=read('src/duo.js');
if(!duoHtmlV27.includes('jszip@3.10.1')) fail('Duo sem JSZip para bosses'); else ok('Duo carrega JSZip');
for(const token of ["loadFrames('assets/player-armed',32","loadFrames('assets/weapons',32","loadFrames('assets/mobs/Ogro',32","loadFrames('assets/mobs/Ogro Elite',32"]) if(!duoJsV27.includes(token)) fail('Duo sem pack necessario: '+token); else ok('Duo pack necessario '+token);
if(!game.includes('playerArmedReady=false')) fail('Host nao controla readiness armado'); else ok('Host espera player armado');
if(!game.includes('playerV2Ready&&playerArmedReady&&weaponV2Ready')) fail('Host libera arena antes da arma'); else ok('Host espera arma antes de entrar');
if(!game.includes('moving:player.moving,walk:player.walk,shotFlash:player.shotFlash')) fail('snapshot P1 sem animacao'); else ok('snapshot P1 com animacao');
if(!game.includes('moving:duoPlayer.moving,walk:duoPlayer.walk,shotFlash:duoPlayer.shotFlash')) fail('snapshot P2 sem animacao'); else ok('snapshot P2 com animacao');
if(!game.includes('t:e.t,speedMul:e.speedMul||1')) fail('snapshot mobs sem frame temporal'); else ok('snapshot mobs animado');
if(!mapRuntime.includes('cfg.extraPlayers?.()')) fail('P2 sem colisao do mapa'); else ok('P2 usa colisao do mapa');
if(failed)process.exit(1);
