import fs from 'node:fs';
const replace=(p,a,b)=>{let s=fs.readFileSync(p,'utf8');if(s.includes(b)&&!s.includes(a))return;const n=s.split(a).length-1;if(n<1)throw Error(`${p}: missing ${a}`);s=s.replaceAll(a,b);fs.writeFileSync(p,s)};
replace('version.json','"version": "0.17.43"','"version": "0.17.44"');
replace('version.json','"build": "solo-persistent-meteor-admin-config"','"build": "modular-runtime-cache-hotfix"');
replace('index.html','Caos Live v0.17.43','Caos Live v0.17.44');
replace('index.html','v0.17.43 · NOVAS SKILLS + FÚRIA','v0.17.44 · RUNTIME HOTFIX');
replace('index.html','id="startVersion">v0.17.43','id="startVersion">v0.17.44');
replace('index.html','src/firebase-ranking.js?v=01743','src/firebase-ranking.js?v=01744');
replace('index.html','src/map-runtime.js?v=01743','src/map-runtime.js?v=01744');
replace('index.html','src/core/game-bootstrap.mjs?v=01743','src/core/game-bootstrap.mjs?v=01744');
replace('painel.html','Caos Admin v0.17.43','Caos Admin v0.17.44');
replace('painel.html','src/styles/panel.css?v=01743','src/styles/panel.css?v=01744');
replace('painel.html','id="panelVersion" class="topVersion">v0.17.43','id="panelVersion" class="topVersion">v0.17.44');
replace('painel.html','index.html?v=01743','index.html?v=01744');
replace('painel.html','src/panel.js?v=01743','src/panel.js?v=01744');
replace('map-lab.html','id="version">v0.17.43','id="version">v0.17.44');
replace('map-lab.html','src/map-lab.js?v=01743','src/map-lab.js?v=01744');
replace('duo.html','Caos Live Duo v0.17.43','Caos Live Duo v0.17.44');
replace('duo.html','src/firebase-ranking.js?v=01743','src/firebase-ranking.js?v=01744');
replace('duo.html','src/map-runtime.js?v=01743','src/map-runtime.js?v=01744');
replace('duo.html','src/duo.js?v=01743','src/duo.js?v=01744');
replace('src/game.js',"const VERSION='0.17.43'","const VERSION='0.17.44'");
replace('src/core/game-bootstrap.mjs',"(match?.[1] || '01743').replace(/\\./g, '')","(match?.[1] || '01744').replace(/\\./g, '')");
const arch='scripts/check-architecture.mjs';let a=fs.readFileSync(arch,'utf8');const old="if (!bootstrap.includes(\"await import(`../game.js?v=${tag}`)\")) fail('bootstrap does not start gameplay after core');\nelse ok('bootstrap starts gameplay after core');";const neu="if (!bootstrap.includes('await loadClassic(`src/game.js?v=${tag}`)')) fail('bootstrap does not start classic gameplay runtime after core');\nelse ok('bootstrap starts classic gameplay runtime after core');\nif (!bootstrap.includes('await loadClassic(`src/multiplayer-entry.js?v=${tag}`)')) fail('bootstrap does not start multiplayer entry after gameplay');\nelse ok('bootstrap starts multiplayer entry after gameplay');";if(a.includes(old))a=a.replace(old,neu);else if(!a.includes("bootstrap starts classic gameplay runtime after core"))throw Error('architecture bootstrap guard missing');fs.writeFileSync(arch,a);
console.log('0.17.44 hotfix applied');