(()=>{'use strict';
const VERSION='0.17.25',$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d',{alpha:false});let W=0,H=0,dpr=1,peer=null,conn=null,retry=null,room='',snapshotAt=0;const keys={},input={dx:0,dy:0},me={x:84,y:0,r:18,life:100,maxLife:100,aim:0,down:false},host={x:0,y:0,life:100,maxLife:100,aim:0},enemies=[],bullets=[];let level=1,pointer=null;
const playerImg=new Image(),ogreImg=new Image(),eliteImg=new Image();playerImg.src='assets/player-armed/Posearma1.png?v=01725';ogreImg.src='assets/mobs/Ogro/frame_001.png?v=01725';eliteImg.src='assets/mobs/Ogro Elite/frame_001.png?v=01725';
function resize(){const r=canvas.getBoundingClientRect();W=Math.max(320,r.width|0);H=Math.max(320,r.height|0);dpr=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr)}addEventListener('resize',resize,{passive:true});resize();
function world(x,y){return{x:x-me.x+W/2,y:y-me.y+H/2}}function hash(x,y,s=0){let n=Math.imul(x,374761393)+Math.imul(y,668265263)+Math.imul(s,1442695041);n^=n>>>13;n=Math.imul(n,1274126177);return((n^(n>>>16))>>>0)/4294967295}
if(window.CaosMap)window.CaosMap.init({version:VERSION,ctx,viewport:()=>({W,H}),player:()=>me,enemies:()=>enemies,hash,world});
function setStatus(t,ok=false){$('status').textContent=t;$('status').style.borderColor=ok?'#22c55e':'#35546b'}
function sanitize(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}
function connectRoom(code){room=sanitize(code);if(room.length!==8){setStatus('CÓDIGO INVÁLIDO');return}$('room').value=room;$('roomLabel').textContent='SALA '+room+' · P2';sessionStorage.setItem('caos-duo-room',room);clearTimeout(retry);try{conn?.close();peer?.destroy()}catch{}setStatus('CONECTANDO…');peer=new Peer(undefined,{debug:0});peer.on('open',()=>{conn=peer.connect('chaos-live-'+room.toLowerCase(),{reliable:true});conn.on('open',()=>{setStatus('P2 CONECTADO',true);$('join').classList.add('hide');conn.send({type:'duo-hello',role:'player2',version:VERSION})});conn.on('data',onData);conn.on('close',()=>retryConnect());conn.on('error',()=>retryConnect())});peer.on('error',()=>retryConnect())}
function retryConnect(){setStatus('RECONECTANDO…');clearTimeout(retry);retry=setTimeout(()=>room&&connectRoom(room),2400)}
function onData(d){if(!d||d.type!=='duo-snapshot')return;snapshotAt=performance.now();if(d.p2)Object.assign(me,d.p2);if(d.p1)Object.assign(host,d.p1);enemies.length=0;for(const e of d.enemies||[])enemies.push(e);bullets.length=0;for(const b of d.bullets||[])bullets.push(b);level=d.level||1;$('life').textContent=Math.max(0,Math.round(me.life))+'/'+Math.round(me.maxLife||100);$('level').textContent='LV '+level;$('down').classList.toggle('show',!!me.down)}
function readInput(){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(pointer){dx=pointer.x-W/2;dy=pointer.y-H/2;if(Math.hypot(dx,dy)<18)dx=dy=0}const n=Math.hypot(dx,dy)||1;input.dx=dx/n;input.dy=dy/n;if(!dx&&!dy)input.dx=input.dy=0}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=1);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}canvas.onpointerdown=e=>{pointer=pos(e);canvas.setPointerCapture(e.pointerId);e.preventDefault()};canvas.onpointermove=e=>{if(pointer){pointer=pos(e);e.preventDefault()}};canvas.onpointerup=canvas.onpointercancel=()=>pointer=null;
setInterval(()=>{readInput();if(conn?.open)try{conn.send({type:'duo-input',dx:input.dx,dy:input.dy,ts:Date.now()})}catch{}},33);
function drawSoldier(p,label,center=false){const q=center?{x:W/2,y:H/2}:world(p.x,p.y);ctx.save();ctx.translate(q.x,q.y);if(playerImg.complete&&playerImg.naturalWidth){const h=68,w=h*playerImg.naturalWidth/playerImg.naturalHeight;ctx.globalAlpha=p.down?.38:1;ctx.drawImage(playerImg,-w/2,-h*.70,w,h)}else{ctx.fillStyle=label==='P2'?'#38bdf8':'#a78bfa';ctx.beginPath();ctx.arc(0,0,17,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.font='900 10px sans-serif';ctx.textAlign='center';ctx.fillStyle=label==='P2'?'#a5f3fc':'#ddd6fe';ctx.fillText(label,0,-42);ctx.restore()}
function drawEnemy(e){const q=world(e.x,e.y),boss=e.max>=100,img=e.tier===1?eliteImg:ogreImg,h=boss?112:e.tier===1?78:58;if(q.x<-130||q.y<-130||q.x>W+130||q.y>H+130)return;ctx.save();ctx.translate(q.x,q.y);if(!boss&&img.complete&&img.naturalWidth){const w=h*img.naturalWidth/img.naturalHeight;ctx.drawImage(img,-w/2,-h*.72,w,h)}else{ctx.fillStyle=boss?'#991b1b':e.tier===2?'#ef4444':'#475569';ctx.beginPath();ctx.arc(0,0,boss?38:18,0,7);ctx.fill()}if(e.hp<e.max||boss){ctx.fillStyle='#24080d';ctx.fillRect(-28,-45,56,5);ctx.fillStyle='#fb7185';ctx.fillRect(-28,-45,56*Math.max(0,e.hp/e.max),5)}ctx.restore()}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);if(!(window.CaosMap&&window.CaosMap.drawGround&&window.CaosMap.drawGround())){ctx.fillStyle='#d8e8ef';ctx.fillRect(0,0,W,H)}for(const b of bullets){const q=world(b.x,b.y);ctx.fillStyle=b.owner==='p2'?'#67e8f9':'#fef08a';ctx.beginPath();ctx.arc(q.x,q.y,3,0,7);ctx.fill()}for(const e of enemies)drawEnemy(e);drawSoldier(host,'P1');drawSoldier(me,'P2',true);if(performance.now()-snapshotAt>1500&&conn?.open)setStatus('SINAL DO HOST LENTO');requestAnimationFrame(draw)}requestAnimationFrame(draw);
$('connect').onclick=()=>connectRoom($('room').value);$('room').addEventListener('keydown',e=>{if(e.key==='Enter')connectRoom($('room').value)});const params=new URLSearchParams(location.search),initial=sanitize(params.get('sala')||params.get('duo')||sessionStorage.getItem('caos-duo-room')||'');if(initial){$('room').value=initial;connectRoom(initial)}
})();
