(()=>{'use strict';
const VERSION='0.17.27',$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d',{alpha:false});let W=0,H=0,dpr=1,peer=null,conn=null,retry=null,room='',snapshotAt=0;const keys={},input={dx:0,dy:0},me={x:84,y:0,r:18,life:100,maxLife:100,aim:0,down:false,moving:false,walk:0,shotFlash:0},host={x:0,y:0,life:100,maxLife:100,aim:0,down:false,moving:false,walk:0,shotFlash:0},enemies=[],bullets=[];let level=1,pointer=null;
const mk8=()=>({up:[],ur:[],right:[],dr:[],down:[],dl:[],left:[],ul:[]}),mk4=()=>({up:[],down:[],right:[],left:[]});
const playerBaseFrames=mk8(),playerArmedFrames=mk8(),playerWeaponFrames=mk8(),ogreFrames=mk8(),eliteOgreFrames=mk8(),bossColossusFrames=mk4(),bossVoidFrames=mk4();
let playerReady=false,armedReady=false,weaponReady=false,ogreReady=false,eliteReady=false,bossColossusReady=false,bossVoidReady=false;
const fallbackWeapon=new Image();fallbackWeapon.src='assets/weapons/assault-rifle-01.png?v=01727';
function mapPlayer32(arr,target){if(arr.length<32)return false;target.down=arr.slice(0,4);target.dr=arr.slice(4,8);target.right=arr.slice(8,12);target.ur=arr.slice(12,16);target.up=arr.slice(16,20);target.ul=arr.slice(20,24);target.left=arr.slice(24,28);target.dl=arr.slice(28,32);return true}
function mapMob32(arr,target){if(arr.length<32)return false;target.down=[arr[0],arr[8],arr[16],arr[24]];target.dr=[arr[1],arr[9],arr[17],arr[25]];target.right=[arr[2],arr[10],arr[18],arr[26]];target.ur=[arr[3],arr[11],arr[19],arr[27]];target.up=[arr[4],arr[12],arr[20],arr[28]];target.ul=[arr[5],arr[13],arr[21],arr[29]];target.left=[arr[6],arr[14],arr[22],arr[30]];target.dl=[arr[7],arr[15],arr[23],arr[31]];return true}
async function cropAlpha(img){try{const c=document.createElement('canvas'),x=c.getContext('2d',{willReadFrequently:true});c.width=img.naturalWidth||img.width;c.height=img.naturalHeight||img.height;x.drawImage(img,0,0);const d=x.getImageData(0,0,c.width,c.height).data;let minX=c.width,minY=c.height,maxX=-1,maxY=-1;for(let y=0;y<c.height;y++)for(let xx=0;xx<c.width;xx++)if(d[(y*c.width+xx)*4+3]>12){minX=Math.min(minX,xx);maxX=Math.max(maxX,xx);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}if(maxX<0)return img;const p=2,x0=Math.max(0,minX-p),y0=Math.max(0,minY-p),x1=Math.min(c.width-1,maxX+p),y1=Math.min(c.height-1,maxY+p),o=document.createElement('canvas');o.width=x1-x0+1;o.height=y1-y0+1;o.getContext('2d').drawImage(c,x0,y0,o.width,o.height,0,0,o.width,o.height);return o}catch{return img}}
function loadImg(src,crop=false){return new Promise((ok,fail)=>{const im=new Image();im.onload=async()=>ok(crop?await cropAlpha(im):im);im.onerror=()=>fail(Error(src));im.src=src+'?v=01727'})}
async function loadFrames(folder,count,namer,crop=false){const jobs=[];for(let i=1;i<=count;i++)jobs.push(loadImg(`${folder}/${namer(i)}`,crop));return Promise.all(jobs)}
async function loadBoss(path,target,kind){try{if(typeof JSZip==='undefined')return false;const r=await fetch(path+'?v=01727',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const z=await JSZip.loadAsync(await r.arrayBuffer()),names=Object.keys(z.files).filter(n=>/\.png$/i.test(n)&&!z.files[n].dir).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),arr=[];for(const n of names){const blob=await z.files[n].async('blob'),url=URL.createObjectURL(blob),im=new Image();await new Promise((ok,fail)=>{im.onload=ok;im.onerror=fail;im.src=url});arr.push(await cropAlpha(im))}if(arr.length<16)return false;if(kind==='colossus'){target.up=arr.slice(0,4);target.down=arr.slice(4,8);target.left=arr.slice(8,12);target.right=arr.slice(12,16)}else{target.up=arr.slice(0,4);target.down=arr.slice(4,8);target.right=arr.slice(8,12);target.left=arr.slice(12,16)}return true}catch(e){console.warn('DUO BOSS ASSET',path,e);return false}}
(async()=>{try{const [base,armed,weapons,mobs,elite]=await Promise.all([
 loadFrames('assets/player',32,i=>'frame_'+String(i).padStart(3,'0')+'.png'),
 loadFrames('assets/player-armed',32,i=>'Posearma'+i+'.png'),
 loadFrames('assets/weapons',32,i=>'frame_'+String(i).padStart(3,'0')+'.png',true),
 loadFrames('assets/mobs/Ogro',32,i=>'frame_'+String(i).padStart(3,'0')+'.png',true),
 loadFrames('assets/mobs/Ogro Elite',32,i=>'frame_'+String(i).padStart(3,'0')+'.png',true)
 ]);playerReady=mapPlayer32(base,playerBaseFrames);armedReady=mapPlayer32(armed,playerArmedFrames);weaponReady=mapPlayer32(weapons,playerWeaponFrames);ogreReady=mapMob32(mobs,ogreFrames);eliteReady=mapMob32(elite,eliteOgreFrames);console.log('DUO FULL ASSETS READY',{playerReady,armedReady,weaponReady,ogreReady,eliteReady})}catch(e){console.error('DUO ASSET LOAD ERROR',e)}
 const [c,v]=await Promise.all([loadBoss('assets/bosses/Ogroboss1.zip',bossColossusFrames,'colossus'),loadBoss('assets/bosses/Ogro2.0Boss.zip',bossVoidFrames,'void')]);bossColossusReady=c;bossVoidReady=v})();
function resize(){const r=canvas.getBoundingClientRect();W=Math.max(320,r.width|0);H=Math.max(320,r.height|0);dpr=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.floor(W*dpr);canvas.height=Math.floor(H*dpr)}addEventListener('resize',resize,{passive:true});resize();
function world(x,y){return{x:x-me.x+W/2,y:y-me.y+H/2}}function hash(x,y,s=0){let n=Math.imul(x,374761393)+Math.imul(y,668265263)+Math.imul(s,1442695041);n^=n>>>13;n=Math.imul(n,1274126177);return((n^(n>>>16))>>>0)/4294967295}
if(window.CaosMap)window.CaosMap.init({version:VERSION,ctx,viewport:()=>({W,H}),player:()=>me,enemies:()=>enemies,hash,world});
function setStatus(t,ok=false){$('status').textContent=t;$('status').style.borderColor=ok?'#22c55e':'#35546b'}
function sanitize(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}
function connectRoom(code){room=sanitize(code);if(room.length!==8){setStatus('CÓDIGO INVÁLIDO');return}$('room').value=room;$('roomLabel').textContent='SALA '+room+' · P2';sessionStorage.setItem('caos-duo-room',room);clearTimeout(retry);try{conn?.close();peer?.destroy()}catch{}setStatus('CONECTANDO…');peer=new Peer(undefined,{debug:0});peer.on('open',()=>{conn=peer.connect('chaos-live-'+room.toLowerCase(),{reliable:true});conn.on('open',()=>{setStatus('P2 CONECTADO',true);$('join').classList.add('hide');conn.send({type:'duo-hello',role:'player2',version:VERSION})});conn.on('data',onData);conn.on('close',()=>retryConnect());conn.on('error',()=>retryConnect())});peer.on('error',()=>retryConnect())}
function retryConnect(){setStatus('RECONECTANDO…');clearTimeout(retry);retry=setTimeout(()=>room&&connectRoom(room),2400)}
function onData(d){if(!d||d.type!=='duo-snapshot')return;snapshotAt=performance.now();if(d.p2)Object.assign(me,d.p2);if(d.p1)Object.assign(host,d.p1);enemies.length=0;for(const e of d.enemies||[])enemies.push(e);bullets.length=0;for(const b of d.bullets||[])bullets.push(b);level=d.level||1;$('life').textContent=Math.max(0,Math.round(me.life))+'/'+Math.round(me.maxLife||100);$('level').textContent='LV '+level;$('down').classList.toggle('show',!!me.down)}
function readInput(){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(pointer){dx=pointer.x-W/2;dy=pointer.y-H/2;if(Math.hypot(dx,dy)<18)dx=dy=0}const n=Math.hypot(dx,dy)||1;input.dx=dx/n;input.dy=dy/n;if(!dx&&!dy)input.dx=input.dy=0}
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=1);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}canvas.onpointerdown=e=>{pointer=pos(e);canvas.setPointerCapture(e.pointerId);e.preventDefault()};canvas.onpointermove=e=>{if(pointer){pointer=pos(e);e.preventDefault()}};canvas.onpointerup=canvas.onpointercancel=()=>pointer=null;
setInterval(()=>{readInput();if(conn?.open)try{conn.send({type:'duo-input',dx:input.dx,dy:input.dy,ts:Date.now()})}catch{}},33);
function playerFacing(a){const oct=Math.round((((a%(Math.PI*2))+Math.PI*2)%(Math.PI*2))/(Math.PI/4))%8;return ['right','dr','down','dl','left','ul','up','ur'][oct]}
const WEAPON_LAYOUT={down:{x:2,y:-1,maxW:38,maxH:58,flip:false},dr:{x:16,y:-6,maxW:62,maxH:38,flip:false},right:{x:20,y:-5,maxW:70,maxH:34,flip:true},ur:{x:15,y:-13,maxW:60,maxH:38,flip:false},up:{x:0,y:-19,maxW:38,maxH:58,flip:false},ul:{x:-15,y:-13,maxW:60,maxH:38,flip:false},left:{x:-20,y:-5,maxW:70,maxH:34,flip:false},dl:{x:-16,y:-6,maxW:62,maxH:38,flip:false}};
function weaponImage(dir,frame){const a=playerWeaponFrames[dir]?.length?playerWeaponFrames[dir]:playerWeaponFrames.down;return(a?.[frame%Math.max(1,a.length)]||a?.[0]||fallbackWeapon)}
function drawWeapon(dir,frame,bob){const wi=weaponImage(dir,frame);if(!wi||(!(wi.width||wi.naturalWidth)))return;const q=WEAPON_LAYOUT[dir]||WEAPON_LAYOUT.down,iw=wi.naturalWidth||wi.width||1,ih=wi.naturalHeight||wi.height||1,ratio=iw/Math.max(1,ih);let ww=q.maxW,wh=ww/Math.max(.05,ratio);if(wh>q.maxH){wh=q.maxH;ww=wh*ratio}ctx.save();ctx.translate(q.x,q.y+bob);if(q.flip)ctx.scale(-1,1);ctx.drawImage(wi,-ww/2,-wh/2,ww,wh);ctx.restore()}
function drawMuzzle(p,dir,bob){if(!(p.shotFlash>0))return;const m={right:{x:46,y:-5},dr:{x:38,y:23},down:{x:5,y:35},dl:{x:-38,y:23},left:{x:-46,y:-5},ul:{x:-36,y:-30},up:{x:0,y:-46},ur:{x:36,y:-30}}[dir]||{x:0,y:0};ctx.save();ctx.globalCompositeOperation='screen';ctx.fillStyle='#fff7b2';ctx.shadowColor='#f59e0b';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(m.x,m.y+bob,4.2,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawSoldier(p,label,center=false){const q=center?{x:W/2,y:H/2}:world(p.x,p.y),dir=playerFacing(p.aim||0),frame=p.moving?Math.floor(p.walk||0)%4:0,pack=armedReady?playerArmedFrames:playerBaseFrames,arr=pack[dir]?.length?pack[dir]:pack.down,img=arr?.[frame%Math.max(1,arr.length)]||arr?.[0],bob=p.moving?Math.sin((p.walk||0)*Math.PI*.5)*.8:0;ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#0009';ctx.beginPath();ctx.ellipse(0,24,22,7,0,0,Math.PI*2);ctx.fill();const behind=['up','ur','ul'].includes(dir);ctx.globalAlpha=p.down?.38:1;if(behind)drawWeapon(dir,frame,bob);if(img){const h=label==='P2'?72:68,w=Math.min(72,h*((img.naturalWidth||img.width||1)/Math.max(1,img.naturalHeight||img.height||1)));ctx.drawImage(img,-w/2,35+bob-h,w,h)}else{ctx.fillStyle=label==='P2'?'#38bdf8':'#a78bfa';ctx.beginPath();ctx.arc(0,0,17,0,7);ctx.fill()}if(!behind)drawWeapon(dir,frame,bob);ctx.globalAlpha=1;drawMuzzle(p,dir,bob);ctx.font='900 10px sans-serif';ctx.textAlign='center';ctx.fillStyle=label==='P2'?'#a5f3fc':'#ddd6fe';ctx.fillText(label,0,-44);ctx.restore()}
function bossFrame(e){const pack=e.type==='colossus'?bossColossusFrames:bossVoidFrames,ready=e.type==='colossus'?bossColossusReady:bossVoidReady,dir=e.facing||'down',arr=pack[dir]?.length?pack[dir]:pack.down;if(!ready||!arr?.length)return null;return arr[(e.speedMul===0?0:Math.floor((e.t||0)/.15))%arr.length]}
function drawEnemy(e){const q=world(e.x,e.y),boss=e.max>=100||e.type==='colossus'||e.type==='voidlord';if(q.x<-150||q.y<-150||q.x>W+150||q.y>H+150)return;let img=null,h=58;if(boss){img=bossFrame(e);h=145}else{const pack=e.tier===1&&eliteReady?eliteOgreFrames:ogreFrames,dir=e.facing||'down',arr=pack[dir]?.length?pack[dir]:pack.down;if((e.tier===1?eliteReady:ogreReady)&&arr?.length)img=arr[(e.speedMul===0?0:Math.floor((e.t||0)/.135))%arr.length];h=e.tier===1?82:60}ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,boss?32:17,boss?42:19,boss?11:6,0,0,Math.PI*2);ctx.fill();if(img){const ratio=(img.naturalWidth||img.width||1)/Math.max(1,img.naturalHeight||img.height||1),w=h*ratio;ctx.drawImage(img,-w/2,-h*.72,w,h)}else{ctx.fillStyle=boss?'#991b1b':e.tier===2?'#ef4444':'#475569';ctx.beginPath();ctx.arc(0,0,boss?38:18,0,7);ctx.fill()}if(e.hp<e.max||boss||e.tier>0){const bw=boss?86:56,by=boss?-72:-45;ctx.fillStyle='#24080d';ctx.fillRect(-bw/2,by,bw,5);ctx.fillStyle=e.tier===2?'#ef4444':e.tier===1?'#a855f7':boss?'#f59e0b':'#fb7185';ctx.fillRect(-bw/2,by,bw*Math.max(0,e.hp/e.max),5)}ctx.restore()}
function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);if(!(window.CaosMap&&window.CaosMap.drawGround&&window.CaosMap.drawGround())){ctx.fillStyle='#d8e8ef';ctx.fillRect(0,0,W,H)}for(const b of bullets){const q=world(b.x,b.y);ctx.fillStyle=b.owner==='p2'?'#67e8f9':'#fef08a';ctx.beginPath();ctx.arc(q.x,q.y,3,0,7);ctx.fill()}for(const e of enemies)drawEnemy(e);drawSoldier(host,'P1');drawSoldier(me,'P2',true);if(performance.now()-snapshotAt>1500&&conn?.open)setStatus('SINAL DO HOST LENTO');requestAnimationFrame(draw)}requestAnimationFrame(draw);
$('connect').onclick=()=>connectRoom($('room').value);$('room').addEventListener('keydown',e=>{if(e.key==='Enter')connectRoom($('room').value)});const params=new URLSearchParams(location.search),initial=sanitize(params.get('sala')||params.get('duo')||sessionStorage.getItem('caos-duo-room')||'');if(initial){$('room').value=initial;connectRoom(initial)}
})();
