(()=>{'use strict';
const $=id=>document.getElementById(id);
const CLOUD_HEALTH='https://game-f202.onrender.com/health';
const PROBE_MS=10000,EVENT_WARN_MS=70000,EVENT_DEAD_MS=115000,RESCUE_COOLDOWN_MS=45000;
let liveSince=0,timer=null,lastOn=false,lastPayload='',gameConn=null,lastEventAt=Date.now(),lastLike='',cloudHealthy=false,lastCloudProbe=0,lastRescue=0,probeBusy=false;

// Caixa-preta da Live: somente observabilidade. Nao muda reconnect, watchdog ou regras.
const diag={incidents:[],lastEvent:'—',lastEventAt:0,lastMode:'—',lastReason:'—',reconnects:0,zombies:0,wsState:'OFFLINE',lastPacketAt:0,likeTimes:[],lastConnectedAt:0};
function cleanUser(v=''){v=String(v||'').trim();if(!v)return '—';return '@'+v.replace(/^@/,'')}
function fmt(ms){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function txt(id){return String($(id)?.textContent||'').trim()}
function liveSnapshot(){const status=txt('cloudStatus'),badge=txt('liveBadge'),dot=txt('cloudDot'),input=$('cloudUser')?.value||'';const connector=/ONLINE|LIVE/i.test(dot)||/autenticado|conectada|curtidas|enviou|comentou/i.test(status);const recentEvent=lastEventAt&&Date.now()-lastEventAt<30000;const on=/TIKTOK LIVE CONECTADA/i.test(status)||(/LIVE CONECTADA/i.test(badge)&&/LIVE/i.test(dot))||(connector&&recentEvent);let user=input;const m=status.match(/@([^\s·]+)/);if(m)user=m[1];return{on,user:String(user||'').replace(/^@/,'').trim().slice(0,32),status,badge,dot}}

function incident(level,title,detail=''){
 const now=Date.now(),last=diag.incidents[0];
 if(last&&last.title===title&&last.detail===detail&&now-last.at<12000)return;
 diag.incidents.unshift({at:now,level,title,detail});
 diag.incidents=diag.incidents.slice(0,80);renderDiag();
}
function burstContext(){const now=Date.now();diag.likeTimes=diag.likeTimes.filter(t=>now-t<10000);return diag.likeTimes.length>=8?` · contexto: ${diag.likeTimes.length} pacotes de like nos últimos 10s`:''}
function markDiagEvent(kind,d={}){diag.lastEvent=kind;diag.lastEventAt=Date.now();diag.lastPacketAt=Date.now();if(d.mode)diag.lastMode=d.mode;if(kind==='like'){diag.likeTimes.push(Date.now());diag.likeTimes=diag.likeTimes.filter(t=>Date.now()-t<10000)}}
function handleCloudPacket(d={}){
 diag.lastPacketAt=Date.now();
 if(['like','chat','gift','follow','share'].includes(d.type)){markDiagEvent(d.type,d);return}
 if(d.type==='pong'){diag.wsState='OK';if(d.mode)diag.lastMode=d.mode;return renderDiag()}
 if(d.type==='error'){diag.lastReason=String(d.message||'erro do Connector');incident('err','ERRO DO CONNECTOR',diag.lastReason+burstContext());return}
 if(d.type==='status'){
   const st=String(d.status||'').toLowerCase();if(d.mode)diag.lastMode=d.mode;if(d.reason)diag.lastReason=String(d.reason);
   if(st==='connected'){diag.lastConnectedAt=Date.now();diag.wsState='OK';incident('ok','TIKTOK CONECTADA',`modo ${d.mode||diag.lastMode||'—'}${d.username?' · @'+d.username:''}`)}
   else if(st==='reconnecting'){diag.reconnects++;incident('warn',`RECONEXÃO #${diag.reconnects}`,`${d.reason||'motivo não informado'}${d.attempt?' · tentativa '+d.attempt:''}${burstContext()}`)}
   else if(st==='zombie'){diag.zombies++;incident('err',`SESSÃO ZUMBI #${diag.zombies}`,`${d.reason||'watchdog'}${burstContext()}`)}
   else if(st==='disconnected')incident('err','TIKTOK DESCONECTADA',`${d.reason||'evento disconnected recebido'}${burstContext()}`);
   else if(st==='offline')incident('warn','LIVE INFORMADA OFFLINE',d.reason||'TikTok informou Live offline');
   else if(st==='fallback')incident('warn','FALLBACK LEGACY','Connector moderno falhou; tentando modo legado');
   renderDiag();return;
 }
 if(d.type==='debug'){
   const ev=String(d.event||'');if(d.mode)diag.lastMode=d.mode;
   if(/LIKE RECEBIDO/i.test(ev)){markDiagEvent('like',d);return}
   if(/CHAT RECEBIDO/i.test(ev)){markDiagEvent('chat',d);return}
   if(/GIFT RECEBIDO/i.test(ev)){markDiagEvent('gift',d);return}
   if(/FOLLOW RECEBIDO/i.test(ev)){markDiagEvent('follow',d);return}
   if(/SHARE RECEBIDO/i.test(ev)){markDiagEvent('share',d);return}
   if(/SESSÃO ZUMBI/i.test(ev)){diag.zombies++;diag.lastReason=d.reason||'watchdog';incident('err',`SESSÃO ZUMBI #${diag.zombies}`,`${diag.lastReason}${d.eventAge!=null?' · sem eventos '+Math.round(d.eventAge/1000)+'s':''}${burstContext()}`)}
   else if(/RECONEXÃO AGENDADA/i.test(ev)){diag.reconnects++;diag.lastReason=d.reason||'reconexão';incident('warn',`RECONEXÃO #${diag.reconnects}`,`${diag.lastReason}${d.attempt?' · tentativa '+d.attempt:''}${burstContext()}`)}
   else if(/WATCHDOG TIKTOK FALHOU/i.test(ev)){diag.lastReason=d.detail||'probe falhou';incident('err','PROBE TIKTOK FALHOU',`${diag.lastReason}${d.failures?' · falhas '+d.failures:''}${burstContext()}`)}
   else if(/ERRO TIKTOK/i.test(ev)){diag.lastReason=d.detail||'erro TikTok';incident('err','ERRO TIKTOK',`${diag.lastReason}${burstContext()}`)}
   else if(/WATCHDOG TIKTOK OK/i.test(ev))diag.lastReason='watchdog ok';
   renderDiag();
 }
}

function installCloudTap(){
 if(window.__caosDiagWebSocketPatched)return;window.__caosDiagWebSocketPatched=true;
 const Native=window.WebSocket;if(!Native)return;
 class DiagWebSocket extends Native{
   constructor(url,protocols){super(url,protocols);const target=String(url||'');if(!/game-f202\.onrender\.com/i.test(target))return;
     diag.wsState='CONECTANDO';renderDiag();
     this.addEventListener('open',()=>{diag.wsState='OK';incident('ok','CLOUD WEBSOCKET ONLINE','Canal painel ↔ Connector aberto');renderDiag()});
     this.addEventListener('close',e=>{diag.wsState='FECHADO';incident('err','CLOUD WEBSOCKET FECHOU',`código ${e.code||'—'}${e.reason?' · '+e.reason:''}${burstContext()}`);renderDiag()});
     this.addEventListener('error',()=>{diag.wsState='ERRO';incident('err','ERRO NO CLOUD WEBSOCKET','Falha detectada no canal painel ↔ Connector');renderDiag()});
     this.addEventListener('message',e=>{try{handleCloudPacket(JSON.parse(e.data))}catch{}});
   }
 }
 Object.defineProperties(DiagWebSocket,{CONNECTING:{value:Native.CONNECTING},OPEN:{value:Native.OPEN},CLOSING:{value:Native.CLOSING},CLOSED:{value:Native.CLOSED}});
 window.WebSocket=DiagWebSocket;
}

function hookPanelConnection(){if(typeof Peer==='undefined'||!Peer.prototype?.connect||Peer.prototype.connect.__caosLiveHook)return;const original=Peer.prototype.connect;function hooked(...args){const c=original.apply(this,args),target=String(args[0]||'');if(target.startsWith('chaos-live-')){gameConn=c;lastPayload='';c.on?.('open',()=>{gameConn=c;lastPayload='';sendGameLiveState(true)});c.on?.('close',()=>{if(gameConn===c)gameConn=null});c.on?.('error',()=>{if(gameConn===c&&!c.open)gameConn=null})}return c}hooked.__caosLiveHook=true;Peer.prototype.connect=hooked}
function ensure(){if($('tiktokLiveMonitor'))return;const anchor=document.querySelector('.automationsCard');if(!anchor)return;const el=document.createElement('section');el.id='tiktokLiveMonitor';el.className='card liveMonitorCard';el.innerHTML=`<div class="liveMonitorHead"><div><span class="eyebrow">SAÚDE DA LIVE</span><h2>Cloud + TikTok</h2></div><span id="liveMonitorBadge" class="liveMonitorBadge off"><i></i> AGUARDANDO</span></div><div class="liveDiagTabs"><button id="liveDiagStatusTab" class="active" type="button">STATUS</button><button id="liveDiagIncidentTab" type="button">INCIDENTES <span id="liveDiagCount">0</span></button></div><div id="liveDiagStatusPane"><div class="liveMonitorGrid"><div class="liveMonitorMain"><small>CONTA</small><b id="liveMonitorUser">—</b><span id="liveMonitorHint">Aguardando conexão</span></div><div><small>CLOUD / RENDER</small><b id="liveMonitorCloud">OFFLINE</b><span id="liveMonitorCloudHint">Sem heartbeat</span></div><div><small>TIKTOK LIVE</small><b id="liveMonitorTikTok">OFF</b><span id="liveMonitorTikTokHint">Não conectada</span></div><div><small>EVENTOS</small><b id="liveMonitorEvents">AGUARDANDO</b><span id="liveMonitorEventsHint">Nenhum sinal</span></div><div><small>DURAÇÃO</small><b id="liveMonitorTime">00:00</b></div><div><small>CURTIDAS</small><b id="liveMonitorLikes">0</b></div></div><div class="liveMonitorFoot"><span>AUTO RESCUE</span><b id="liveMonitorRescue">ATIVO · monitora Cloud e TikTok separadamente</b></div></div><div id="liveDiagIncidentPane" hidden><div class="liveDiagSummary"><div><small>CLOUD WS</small><b id="diagWs">OFFLINE</b></div><div><small>MODO</small><b id="diagMode">—</b></div><div><small>ÚLTIMO EVENTO</small><b id="diagLastEvent">—</b></div><div><small>RECONEXÕES</small><b id="diagReconnects">0</b></div><div><small>ZUMBIS</small><b id="diagZombies">0</b></div><div><small>ÚLTIMA CAUSA</small><b id="diagReason">—</b></div></div><div class="liveDiagActions"><span>Caixa-preta técnica · não altera a conexão</span><button id="liveDiagClear" type="button">LIMPAR</button></div><div id="liveDiagList" class="liveDiagList"><div class="liveDiagEmpty">Nenhum incidente registrado nesta sessão.</div></div></div>`;anchor.parentNode.insertBefore(el,anchor);installStyles();wireDiagTabs();renderDiag()}
function installStyles(){if($('liveHealthExtraStyles'))return;const s=document.createElement('style');s.id='liveHealthExtraStyles';s.textContent=`#tiktokLiveMonitor .liveMonitorGrid>div b.ok{color:#79e6a5}#tiktokLiveMonitor .liveMonitorGrid>div b.warn{color:#f7d67b}#tiktokLiveMonitor .liveMonitorGrid>div b.err{color:#ff9ba9}#tiktokLiveMonitor .liveMonitorGrid>div span{display:block;margin-top:3px;color:#78849c;font-size:9px}.liveMonitorBadge.warn{color:#f7d67b;border-color:#725819;background:#241b06}.liveMonitorBadge.err{color:#ff9ba9;border-color:#7d2c3d;background:#2a0b13}.liveDiagTabs{display:flex;gap:8px;margin:14px 0}.liveDiagTabs button{flex:1;border:1px solid #26334d;background:#09101d;color:#9aa8c4;border-radius:12px;padding:11px;font-weight:800;letter-spacing:.08em}.liveDiagTabs button.active{border-color:#7c3aed;background:#22113d;color:#fff}.liveDiagTabs span{font-size:10px;opacity:.75}.liveDiagSummary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.liveDiagSummary>div{border:1px solid #26334d;background:#080e19;border-radius:14px;padding:12px}.liveDiagSummary small{display:block;color:#7f8ca8;font-size:9px;letter-spacing:.12em;margin-bottom:6px}.liveDiagSummary b{display:block;color:#edf2ff;font-size:12px;overflow-wrap:anywhere}.liveDiagActions{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:14px 0 9px;color:#78849c;font-size:10px}.liveDiagActions button{border:1px solid #5c2a3a;background:#1d0b12;color:#ff9bac;border-radius:10px;padding:8px 12px;font-weight:800}.liveDiagList{display:flex;flex-direction:column;gap:8px;max-height:420px;overflow:auto}.liveDiagItem{border:1px solid #26334d;background:#080e19;border-radius:13px;padding:11px}.liveDiagItem.ok{border-left:3px solid #37c978}.liveDiagItem.warn{border-left:3px solid #d9a62e}.liveDiagItem.err{border-left:3px solid #df5269}.liveDiagItemHead{display:flex;justify-content:space-between;gap:10px}.liveDiagItemHead b{font-size:11px;color:#eef3ff}.liveDiagItemHead time{font-size:9px;color:#69758e}.liveDiagItem p{margin:5px 0 0;color:#8b97b0;font-size:10px;line-height:1.4}.liveDiagEmpty{padding:18px;border:1px dashed #26334d;border-radius:13px;color:#78849c;text-align:center;font-size:10px}`;document.head.appendChild(s)}
function wireDiagTabs(){const a=$('liveDiagStatusTab'),b=$('liveDiagIncidentTab'),sa=$('liveDiagStatusPane'),sb=$('liveDiagIncidentPane');if(a)a.onclick=()=>{a.classList.add('active');b?.classList.remove('active');if(sa)sa.hidden=false;if(sb)sb.hidden=true};if(b)b.onclick=()=>{b.classList.add('active');a?.classList.remove('active');if(sa)sa.hidden=true;if(sb)sb.hidden=false};if($('liveDiagClear'))$('liveDiagClear').onclick=()=>{diag.incidents=[];renderDiag()}}
function renderDiag(){if(!$('liveDiagList'))return;if($('diagWs'))$('diagWs').textContent=diag.wsState;if($('diagMode'))$('diagMode').textContent=diag.lastMode||'—';if($('diagLastEvent'))$('diagLastEvent').textContent=diag.lastEventAt?`${diag.lastEvent} · há ${Math.max(0,Math.round((Date.now()-diag.lastEventAt)/1000))}s`:'—';if($('diagReconnects'))$('diagReconnects').textContent=String(diag.reconnects);if($('diagZombies'))$('diagZombies').textContent=String(diag.zombies);if($('diagReason'))$('diagReason').textContent=diag.lastReason||'—';if($('liveDiagCount'))$('liveDiagCount').textContent=String(diag.incidents.length);const box=$('liveDiagList');if(!diag.incidents.length){box.innerHTML='<div class="liveDiagEmpty">Nenhum incidente registrado nesta sessão.</div>';return}box.innerHTML=diag.incidents.map(x=>`<div class="liveDiagItem ${x.level}"><div class="liveDiagItemHead"><b>${escapeHtml(x.title)}</b><time>${new Date(x.at).toLocaleTimeString('pt-BR')}</time></div>${x.detail?`<p>${escapeHtml(x.detail)}</p>`:''}</div>`).join('')}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setHealth(id,value,kind,hint=''){const b=$(id),h=$(id+'Hint');if(b){b.textContent=value;b.className=kind||''}if(h)h.textContent=hint}
async function probeCloud(){if(probeBusy)return;probeBusy=true;try{const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),4500);const r=await fetch(CLOUD_HEALTH+'?ts='+Date.now(),{cache:'no-store',signal:ctl.signal});clearTimeout(to);if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();cloudHealthy=!!j.ok;lastCloudProbe=Date.now()}catch{cloudHealthy=false}finally{probeBusy=false}}
function sendGameLiveState(force=false){if(!gameConn?.open)return false;const snap=liveSnapshot(),payload=JSON.stringify({liveStatus:snap.on?'on':'off',liveUser:snap.user});if(!force&&payload===lastPayload)return true;try{gameConn.send({type:'command',command:'ping',liveStatus:snap.on?'on':'off',liveUser:snap.user});lastPayload=payload;return true}catch{return false}}
function markEvent(){const like=txt('likeTotal'),evt=txt('liveStatus'),status=txt('cloudStatus');if(like!==lastLike||/Último comentário|Último evento|💬|🎁|curtida|coment|follow|seguiu|share|compart/i.test(evt+' '+status))lastEventAt=Date.now();lastLike=like}
function cleanupNoise(){const log=$('log');if(!log)return;const seen=new Set();[...log.children].forEach(p=>{const raw=String(p.textContent||''),body=raw.replace(/^\d{2}:\d{2}:\d{2}\s+—\s+/,'');if(!/Jogo v[\d.]+ ≠ Painel v[\d.]+|Heartbeat expirou; reconectando/i.test(body))return;const key=body.replace(/\d+/g,'#');if(seen.has(key))p.remove();else seen.add(key)})}
function clickSafe(id){const el=$(id);if(!el||el.disabled)return false;el.click();return true}
function rescue(reason){const now=Date.now();if(now-lastRescue<RESCUE_COOLDOWN_MS)return;lastRescue=now;const r=$('liveMonitorRescue');if(r)r.textContent='RECUPERANDO · '+reason;incident('warn','AUTO RESCUE ACIONADO',reason+burstContext());const dot=txt('cloudDot').toUpperCase();if(!cloudHealthy||dot==='OFFLINE'||dot==='ERRO'){clickSafe('cloudConnect');setTimeout(()=>clickSafe('tiktokConnect'),5000)}else{clickSafe('tiktokDisconnect');setTimeout(()=>clickSafe('tiktokConnect'),1800)}setTimeout(()=>{if(r)r.textContent='ATIVO · monitora Cloud e TikTok separadamente'},8000)}
function sync(){ensure();markEvent();cleanupNoise();const snap=liveSnapshot(),input=$('cloudUser')?.value||'',age=Date.now()-lastEventAt,expected=!!String(input).replace(/^@/,'').trim();if(snap.on&&!lastOn){liveSince=Date.now();lastOn=true}if(!snap.on&&lastOn){lastOn=false;liveSince=0}
 if($('liveMonitorUser'))$('liveMonitorUser').textContent=snap.on?cleanUser(snap.user):cleanUser(input);
 if($('liveMonitorLikes'))$('liveMonitorLikes').textContent=txt('likeTotal')||'0';if($('liveMonitorTime'))$('liveMonitorTime').textContent=snap.on&&liveSince?fmt(Date.now()-liveSince):'00:00';
 if(cloudHealthy)setHealth('liveMonitorCloud','OK','ok','Heartbeat há '+Math.max(0,Math.round((Date.now()-lastCloudProbe)/1000))+'s');else setHealth('liveMonitorCloud','SEM RESPOSTA','err','Render/Cloud não respondeu');
 if(snap.on)setHealth('liveMonitorTikTok','CONECTADA','ok','Sessão confirmada pelo painel');else if(expected&&cloudHealthy)setHealth('liveMonitorTikTok','NÃO CONFIRMADA','warn','Cloud ok; TikTok sem confirmação');else setHealth('liveMonitorTikTok','OFF','err','Live não conectada');
 if(snap.on&&age<EVENT_WARN_MS)setHealth('liveMonitorEvents','RECEBENDO','ok','Último sinal há '+Math.round(age/1000)+'s');else if(snap.on&&age<EVENT_DEAD_MS)setHealth('liveMonitorEvents','SEM ATIVIDADE','warn','Sem evento há '+Math.round(age/1000)+'s');else if(snap.on){setHealth('liveMonitorEvents','POSSÍVEL TRAVA','err','Sem evento há '+Math.round(age/1000)+'s');rescue('TikTok sem eventos por '+Math.round(age/1000)+'s')}else setHealth('liveMonitorEvents','AGUARDANDO','',expected?'Aguardando Live':'Informe o @');
 const badge=$('liveMonitorBadge');if(badge){let label='AGUARDANDO',cls='off';if(cloudHealthy&&snap.on&&age<EVENT_WARN_MS){label='TUDO OK';cls='on'}else if(cloudHealthy&&(snap.on||expected)){label='ATENÇÃO';cls='warn'}else if(expected){label='FALHA';cls='err'}badge.className='liveMonitorBadge '+cls;badge.innerHTML=`<i></i> ${label}`}
 if($('liveMonitorHint'))$('liveMonitorHint').textContent=cloudHealthy&&snap.on?'Cloud e TikTok operacionais':'Verifique os indicadores abaixo';sendGameLiveState();renderDiag()}
function watch(){installCloudTap();hookPanelConnection();ensure();document.getElementById('diagCard')?.remove();lastLike=txt('likeTotal');['cloudStatus','liveBadge','cloudDot','likeTotal','liveStatus','log'].forEach(id=>{const el=$(id);if(el)new MutationObserver(sync).observe(el,{childList:true,subtree:true,characterData:true,attributes:true})});$('cloudUser')?.addEventListener('input',sync);probeCloud();setInterval(probeCloud,PROBE_MS);timer=setInterval(()=>{sync();sendGameLiveState(true)},2000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){probeCloud();sync()}});window.addEventListener('online',()=>{probeCloud();setTimeout(sync,500)});sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();