(()=>{'use strict';
const $=id=>document.getElementById(id);
const CLOUD_HEALTH='https://game-f202.onrender.com/health';
const PROBE_MS=10000,EVENT_WARN_MS=70000,EVENT_DEAD_MS=115000,RESCUE_COOLDOWN_MS=45000;
let liveSince=0,timer=null,lastOn=false,lastPayload='',gameConn=null,lastEventAt=Date.now(),lastLike='',cloudHealthy=false,lastCloudProbe=0,lastRescue=0,probeBusy=false;
function cleanUser(v=''){v=String(v||'').trim();if(!v)return '—';return '@'+v.replace(/^@/,'')}
function fmt(ms){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function txt(id){return String($(id)?.textContent||'').trim()}
function liveSnapshot(){const status=txt('cloudStatus'),badge=txt('liveBadge'),dot=txt('cloudDot'),input=$('cloudUser')?.value||'';const connector=/ONLINE|LIVE/i.test(dot)||/autenticado|conectada|curtidas|enviou|comentou/i.test(status);const recentEvent=lastEventAt&&Date.now()-lastEventAt<30000;const on=/TIKTOK LIVE CONECTADA/i.test(status)||(/LIVE CONECTADA/i.test(badge)&&/LIVE/i.test(dot))||(connector&&recentEvent);let user=input;const m=status.match(/@([^\s·]+)/);if(m)user=m[1];return{on,user:String(user||'').replace(/^@/,'').trim().slice(0,32),status,badge,dot}}
function hookPanelConnection(){if(typeof Peer==='undefined'||!Peer.prototype?.connect||Peer.prototype.connect.__caosLiveHook)return;const original=Peer.prototype.connect;function hooked(...args){const c=original.apply(this,args),target=String(args[0]||'');if(target.startsWith('chaos-live-')){gameConn=c;lastPayload='';c.on?.('open',()=>{gameConn=c;lastPayload='';sendGameLiveState(true)});c.on?.('close',()=>{if(gameConn===c)gameConn=null});c.on?.('error',()=>{if(gameConn===c&&!c.open)gameConn=null})}return c}hooked.__caosLiveHook=true;Peer.prototype.connect=hooked}
function ensure(){if($('tiktokLiveMonitor'))return;const anchor=document.querySelector('.automationsCard');if(!anchor)return;const el=document.createElement('section');el.id='tiktokLiveMonitor';el.className='card liveMonitorCard';el.innerHTML=`<div class="liveMonitorHead"><div><span class="eyebrow">SAÚDE DA LIVE</span><h2>Cloud + TikTok</h2></div><span id="liveMonitorBadge" class="liveMonitorBadge off"><i></i> AGUARDANDO</span></div><div class="liveMonitorGrid"><div class="liveMonitorMain"><small>CONTA</small><b id="liveMonitorUser">—</b><span id="liveMonitorHint">Aguardando conexão</span></div><div><small>CLOUD / RENDER</small><b id="liveMonitorCloud">OFFLINE</b><span id="liveMonitorCloudHint">Sem heartbeat</span></div><div><small>TIKTOK LIVE</small><b id="liveMonitorTikTok">OFF</b><span id="liveMonitorTikTokHint">Não conectada</span></div><div><small>EVENTOS</small><b id="liveMonitorEvents">AGUARDANDO</b><span id="liveMonitorEventsHint">Nenhum sinal</span></div><div><small>DURAÇÃO</small><b id="liveMonitorTime">00:00</b></div><div><small>CURTIDAS</small><b id="liveMonitorLikes">0</b></div></div><div class="liveMonitorFoot"><span>AUTO RESCUE</span><b id="liveMonitorRescue">ATIVO · monitora Cloud e TikTok separadamente</b></div>`;anchor.parentNode.insertBefore(el,anchor);installStyles()}
function installStyles(){if($('liveHealthExtraStyles'))return;const s=document.createElement('style');s.id='liveHealthExtraStyles';s.textContent=`#tiktokLiveMonitor .liveMonitorGrid>div b.ok{color:#79e6a5}#tiktokLiveMonitor .liveMonitorGrid>div b.warn{color:#f7d67b}#tiktokLiveMonitor .liveMonitorGrid>div b.err{color:#ff9ba9}#tiktokLiveMonitor .liveMonitorGrid>div span{display:block;margin-top:3px;color:#78849c;font-size:9px}.liveMonitorBadge.warn{color:#f7d67b;border-color:#725819;background:#241b06}.liveMonitorBadge.err{color:#ff9ba9;border-color:#7d2c3d;background:#2a0b13}`;document.head.appendChild(s)}
function setHealth(id,value,kind,hint=''){const b=$(id),h=$(id+'Hint');if(b){b.textContent=value;b.className=kind||''}if(h)h.textContent=hint}
async function probeCloud(){if(probeBusy)return;probeBusy=true;try{const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),4500);const r=await fetch(CLOUD_HEALTH+'?ts='+Date.now(),{cache:'no-store',signal:ctl.signal});clearTimeout(to);if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();cloudHealthy=!!j.ok;lastCloudProbe=Date.now()}catch{cloudHealthy=false}finally{probeBusy=false}}
function sendGameLiveState(force=false){if(!gameConn?.open)return false;const snap=liveSnapshot(),payload=JSON.stringify({liveStatus:snap.on?'on':'off',liveUser:snap.user});if(!force&&payload===lastPayload)return true;try{gameConn.send({type:'command',command:'ping',liveStatus:snap.on?'on':'off',liveUser:snap.user});lastPayload=payload;return true}catch{return false}}
function markEvent(){const like=txt('likeTotal'),evt=txt('liveStatus'),status=txt('cloudStatus');if(like!==lastLike||/Último comentário|Último evento|💬|🎁|curtida|coment|follow|seguiu|share|compart/i.test(evt+' '+status))lastEventAt=Date.now();lastLike=like}
function cleanupNoise(){const log=$('log');if(!log)return;const seen=new Set();[...log.children].forEach(p=>{const raw=String(p.textContent||''),body=raw.replace(/^\d{2}:\d{2}:\d{2}\s+—\s+/,'');if(!/Jogo v[\d.]+ ≠ Painel v[\d.]+|Heartbeat expirou; reconectando/i.test(body))return;const key=body.replace(/\d+/g,'#');if(seen.has(key))p.remove();else seen.add(key)})}
function clickSafe(id){const el=$(id);if(!el||el.disabled)return false;el.click();return true}
function rescue(reason){const now=Date.now();if(now-lastRescue<RESCUE_COOLDOWN_MS)return;lastRescue=now;const r=$('liveMonitorRescue');if(r)r.textContent='RECUPERANDO · '+reason;const dot=txt('cloudDot').toUpperCase();if(!cloudHealthy||dot==='OFFLINE'||dot==='ERRO'){clickSafe('cloudConnect');setTimeout(()=>clickSafe('tiktokConnect'),5000)}else{clickSafe('tiktokDisconnect');setTimeout(()=>clickSafe('tiktokConnect'),1800)}setTimeout(()=>{if(r)r.textContent='ATIVO · monitora Cloud e TikTok separadamente'},8000)}
function sync(){ensure();markEvent();cleanupNoise();const snap=liveSnapshot(),input=$('cloudUser')?.value||'',age=Date.now()-lastEventAt,expected=!!String(input).replace(/^@/,'').trim();if(snap.on&&!lastOn){liveSince=Date.now();lastOn=true}if(!snap.on&&lastOn){lastOn=false;liveSince=0}
 if($('liveMonitorUser'))$('liveMonitorUser').textContent=snap.on?cleanUser(snap.user):cleanUser(input);
 if($('liveMonitorLikes'))$('liveMonitorLikes').textContent=txt('likeTotal')||'0';if($('liveMonitorTime'))$('liveMonitorTime').textContent=snap.on&&liveSince?fmt(Date.now()-liveSince):'00:00';
 if(cloudHealthy)setHealth('liveMonitorCloud','OK','ok','Heartbeat há '+Math.max(0,Math.round((Date.now()-lastCloudProbe)/1000))+'s');else setHealth('liveMonitorCloud','SEM RESPOSTA','err','Render/Cloud não respondeu');
 if(snap.on)setHealth('liveMonitorTikTok','CONECTADA','ok','Sessão confirmada pelo painel');else if(expected&&cloudHealthy)setHealth('liveMonitorTikTok','NÃO CONFIRMADA','warn','Cloud ok; TikTok sem confirmação');else setHealth('liveMonitorTikTok','OFF','err','Live não conectada');
 if(snap.on&&age<EVENT_WARN_MS)setHealth('liveMonitorEvents','RECEBENDO','ok','Último sinal há '+Math.round(age/1000)+'s');else if(snap.on&&age<EVENT_DEAD_MS)setHealth('liveMonitorEvents','SEM ATIVIDADE','warn','Sem evento há '+Math.round(age/1000)+'s');else if(snap.on){setHealth('liveMonitorEvents','POSSÍVEL TRAVA','err','Sem evento há '+Math.round(age/1000)+'s');rescue('TikTok sem eventos por '+Math.round(age/1000)+'s')}else setHealth('liveMonitorEvents','AGUARDANDO','',expected?'Aguardando Live':'Informe o @');
 const badge=$('liveMonitorBadge');if(badge){let label='AGUARDANDO',cls='off';if(cloudHealthy&&snap.on&&age<EVENT_WARN_MS){label='TUDO OK';cls='on'}else if(cloudHealthy&&(snap.on||expected)){label='ATENÇÃO';cls='warn'}else if(expected){label='FALHA';cls='err'}badge.className='liveMonitorBadge '+cls;badge.innerHTML=`<i></i> ${label}`}
 if($('liveMonitorHint'))$('liveMonitorHint').textContent=cloudHealthy&&snap.on?'Cloud e TikTok operacionais':'Verifique os indicadores abaixo';sendGameLiveState()}
function watch(){hookPanelConnection();ensure();document.getElementById('diagCard')?.remove();lastLike=txt('likeTotal');['cloudStatus','liveBadge','cloudDot','likeTotal','liveStatus','log'].forEach(id=>{const el=$(id);if(el)new MutationObserver(sync).observe(el,{childList:true,subtree:true,characterData:true,attributes:true})});$('cloudUser')?.addEventListener('input',sync);probeCloud();setInterval(probeCloud,PROBE_MS);timer=setInterval(()=>{sync();sendGameLiveState(true)},2000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){probeCloud();sync()}});window.addEventListener('online',()=>{probeCloud();setTimeout(sync,500)});sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();