(()=>{'use strict';
const $=id=>document.getElementById(id);
let liveSince=0,timer=null,lastOn=false,lastPayload='';let gameConn=null;
function cleanUser(v=''){v=String(v||'').trim();if(!v)return '—';return '@'+v.replace(/^@/,'')}
function fmt(ms){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`}
function liveSnapshot(){const status=$('cloudStatus')?.textContent||'',badge=$('liveBadge')?.textContent||'',dot=$('cloudDot')?.textContent||'',input=$('cloudUser')?.value||'';const on=/TIKTOK LIVE CONECTADA/i.test(status)||(/LIVE CONECTADA/i.test(badge)&&/LIVE/i.test(dot));let user=input;const m=status.match(/@([^\s·]+)/);if(m)user=m[1];return{on,user:String(user||'').replace(/^@/,'').trim().slice(0,32),status,badge,dot}}
function hookPanelConnection(){if(typeof Peer==='undefined'||!Peer.prototype?.connect||Peer.prototype.connect.__caosLiveHook)return;const original=Peer.prototype.connect;function hooked(...args){const c=original.apply(this,args),target=String(args[0]||'');if(target.startsWith('chaos-live-')){gameConn=c;lastPayload='';c.on?.('open',()=>{gameConn=c;lastPayload='';sendGameLiveState(true)});c.on?.('close',()=>{if(gameConn===c)gameConn=null});c.on?.('error',()=>{if(gameConn===c&&!c.open)gameConn=null})}return c}hooked.__caosLiveHook=true;Peer.prototype.connect=hooked}
function ensure(){if($('tiktokLiveMonitor'))return;const anchor=document.querySelector('.automationsCard');if(!anchor)return;const el=document.createElement('section');el.id='tiktokLiveMonitor';el.className='card liveMonitorCard';el.innerHTML=`<div class="liveMonitorHead"><div><span class="eyebrow">TIKTOK LIVE</span><h2>Status da transmissão</h2></div><span id="liveMonitorBadge" class="liveMonitorBadge off"><i></i> LIVE OFF</span></div><div class="liveMonitorGrid"><div class="liveMonitorMain"><small>CONTA</small><b id="liveMonitorUser">—</b><span id="liveMonitorHint">Aguardando conexão com uma Live</span></div><div><small>DURAÇÃO</small><b id="liveMonitorTime">00:00</b></div><div><small>CURTIDAS</small><b id="liveMonitorLikes">0</b></div><div><small>CONNECTOR</small><b id="liveMonitorCloud">OFFLINE</b></div></div><div class="liveMonitorFoot"><span>ÚLTIMO EVENTO</span><b id="liveMonitorEvent">Nenhum evento recebido.</b></div>`;anchor.parentNode.insertBefore(el,anchor)}
function sendGameLiveState(force=false){if(!gameConn?.open)return false;const snap=liveSnapshot(),payload=JSON.stringify({liveStatus:snap.on?'on':'off',liveUser:snap.user});if(!force&&payload===lastPayload)return true;try{gameConn.send({type:'command',command:'ping',liveStatus:snap.on?'on':'off',liveUser:snap.user});lastPayload=payload;return true}catch{return false}}
function sync(){ensure();const snap=liveSnapshot(),on=snap.on,input=$('cloudUser')?.value||'';if(on&&!lastOn){liveSince=Date.now();lastOn=true}if(!on&&lastOn){lastOn=false;liveSince=0}const b=$('liveMonitorBadge');if(b){b.className='liveMonitorBadge '+(on?'on':'off');b.innerHTML=`<i></i> ${on?'LIVE ON':'LIVE OFF'}`}if($('liveMonitorUser'))$('liveMonitorUser').textContent=on?cleanUser(snap.user):cleanUser(input);if($('liveMonitorHint'))$('liveMonitorHint').textContent=on?'Transmissão conectada e recebendo eventos':'Aguardando confirmação da TikTok Live';if($('liveMonitorLikes'))$('liveMonitorLikes').textContent=$('likeTotal')?.textContent||'0';if($('liveMonitorCloud')){$('liveMonitorCloud').textContent=/ONLINE|LIVE/i.test(snap.dot)?snap.dot:'OFFLINE';$('liveMonitorCloud').classList.toggle('ok',/ONLINE|LIVE/i.test(snap.dot))}if($('liveMonitorEvent'))$('liveMonitorEvent').textContent=$('liveStatus')?.textContent||'Nenhum evento recebido.';if($('liveMonitorTime'))$('liveMonitorTime').textContent=on&&liveSince?fmt(Date.now()-liveSince):'00:00';sendGameLiveState()}
function loadScript(src){return new Promise((ok,fail)=>{if(document.querySelector(`script[data-diag="${src}"]`))return ok();const s=document.createElement('script');s.src=src;s.dataset.diag=src;s.onload=ok;s.onerror=fail;document.body.appendChild(s)})}
async function bootDiagnostics(){
  if($('diagCard'))return;
  const card=document.createElement('section');card.id='diagCard';card.className='card';card.innerHTML=`<div class="sectionTitle"><div><span class="eyebrow">DIAGNÓSTICO DE PARTIDA</span><h2>Última partida</h2></div><span class="miniStatus">CROSS-DEVICE</span></div><p class="hint">A última partida é temporária. Se acontecer um bug, salve para ela não ser substituída pela próxima.</p><div id="diagLatest" class="net leftNet"><b>CARREGANDO...</b></div><textarea id="diagNote" maxlength="300" placeholder="Nota: ex. mira travou no LV5" style="width:100%;min-height:72px;margin-top:10px;padding:11px;border-radius:10px;background:#080b19;color:#fff;border:1px solid #343861"></textarea><div class="grid compactGrid" style="margin-top:9px"><button id="diagSave" class="good">💾 SALVAR PARTIDA</button><button id="diagRefresh" class="blue">↻ ATUALIZAR</button></div><div id="diagStatus" class="net leftNet" style="margin-top:9px">Inicializando diagnóstico...</div><h3>Partidas protegidas</h3><div id="diagSaved" class="net leftNet">Carregando...</div>`;
  const anchor=document.querySelector('.historyCard')||document.querySelector('#controls');anchor?.parentNode?.insertBefore(card,anchor);
  try{await loadScript('https://www.gstatic.com/firebasejs/12.16.0/firebase-app-compat.js');await loadScript('https://www.gstatic.com/firebasejs/12.16.0/firebase-auth-compat.js');await loadScript('https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore-compat.js');await loadScript('src/firebase-ranking.js?v=01745');await loadScript('src/admin-diagnostics.js?v=1')}catch(e){if($('diagStatus'))$('diagStatus').textContent='Falha ao carregar diagnóstico: '+String(e?.message||e)}
}
function watch(){hookPanelConnection();ensure();bootDiagnostics();['cloudStatus','liveBadge','cloudDot','likeTotal','liveStatus'].forEach(id=>{const el=$(id);if(el)new MutationObserver(sync).observe(el,{childList:true,subtree:true,characterData:true,attributes:true})});$('cloudUser')?.addEventListener('input',sync);timer=setInterval(()=>{sync();sendGameLiveState(true)},2000);sync()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();