(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#canvas'),ctx=canvas.getContext('2d'),wrap=$('#wrap');
const TYPE={forest:0,dirt:1,water:2,trail:3,bridge:4};
const COLORS=['#315f2b','#7b5a32','#277089','#b78a48','#8d6b43'];
const NAMES=['floresta','terra','água','trilha','ponte'];
const ROLE={0:'isolado',1:'fim N',2:'fim E',3:'curva NE',4:'fim S',5:'reta NS',6:'curva ES',7:'T NES',8:'fim W',9:'curva WN',10:'reta EW',11:'T NEW',12:'curva SW',13:'T NSW',14:'T ESW',15:'centro'};
const state={n:32,grid:[],seed:'CAOS-001',zoom:1,panX:0,panY:0,drag:false,lastX:0,lastY:0,tiles:[],props:[],ready:false,stats:null};
function hashStr(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function H(x,y,s=0){let h=hashStr(state.seed);h^=Math.imul(x+0x9e3779b9,0x85ebca6b);h^=Math.imul(y+0xc2b2ae35,0x27d4eb2d);h^=s;h=Math.imul(h^(h>>>16),0x7feb352d);h=Math.imul(h^(h>>>15),0x846ca68b);return ((h^(h>>>16))>>>0)/4294967296}
function idx(x,y){return y*state.n+x} function inside(x,y){return x>=0&&y>=0&&x<state.n&&y<state.n}
function get(x,y){return inside(x,y)?state.grid[idx(x,y)]:TYPE.forest} function set(x,y,t){if(inside(x,y))state.grid[idx(x,y)]=t}
function circle(cx,cy,r,t,noise=.15){for(let y=Math.floor(cy-r-1);y<=Math.ceil(cy+r+1);y++)for(let x=Math.floor(cx-r-1);x<=Math.ceil(cx+r+1);x++){if(!inside(x,y))continue;const d=Math.hypot(x-cx,y-cy);if(d<r*(.82+H(x,y,91)*.36)&&H(x,y,92)>noise)set(x,y,t)}}
function generate(){state.n=+$('#size').value;state.seed=$('#seed').value.trim()||'CAOS-001';state.grid=new Array(state.n*state.n).fill(TYPE.forest);const water=+$('#water').value/100,clear=+$('#clearings').value/100,trails=+$('#trails').value;
 const area=state.n*state.n,wb=Math.max(1,Math.round(area*water/70)),cb=Math.max(1,Math.round(area*clear/85));
 for(let i=0;i<cb;i++)circle(2+H(i,1,10)*(state.n-4),2+H(i,2,11)*(state.n-4),2+H(i,3,12)*4,TYPE.dirt,.08);
 for(let i=0;i<wb;i++)circle(2+H(i,4,20)*(state.n-4),2+H(i,5,21)*(state.n-4),1.7+H(i,6,22)*3.7,TYPE.water,.06);
 for(let p=0;p<trails;p++)carveTrail(p);
 for(let pass=0;pass<2;pass++){const copy=state.grid.slice();for(let y=1;y<state.n-1;y++)for(let x=1;x<state.n-1;x++){const t=copy[idx(x,y)];if(t===TYPE.trail||t===TYPE.bridge)continue;let same=0;for(const [dx,dy] of [[0,-1],[1,0],[0,1],[-1,0]])if(copy[idx(x+dx,y+dy)]===t)same++;if(same===0)state.grid[idx(x,y)]=TYPE.forest}}
 state.stats=analyze();fit();draw();renderStats()}
function carveTrail(p){const horizontal=p%2===0;let x=horizontal?0:Math.floor(2+H(p,3,30)*(state.n-4)),y=horizontal?Math.floor(2+H(p,4,31)*(state.n-4)):0;const target=state.n-1;let guard=0;while(guard++<state.n*4){const old=get(x,y);set(x,y,old===TYPE.water?TYPE.bridge:TYPE.trail);if((horizontal&&x>=target)||(!horizontal&&y>=target))break;const r=H(x+p*17,y+p*31,32);if(horizontal){x++;if(r<.23&&y>1)y--;else if(r>.77&&y<state.n-2)y++}else{y++;if(r<.23&&x>1)x--;else if(r>.77&&x<state.n-2)x++}}}
function maskFor(x,y){const t=get(x,y);if(t===TYPE.bridge){let m=0;if([TYPE.trail,TYPE.bridge].includes(get(x,y-1)))m|=1;if([TYPE.trail,TYPE.bridge].includes(get(x+1,y)))m|=2;if([TYPE.trail,TYPE.bridge].includes(get(x,y+1)))m|=4;if([TYPE.trail,TYPE.bridge].includes(get(x-1,y)))m|=8;return m}
 let m=0;if(get(x,y-1)===t)m|=1;if(get(x+1,y)===t)m|=2;if(get(x,y+1)===t)m|=4;if(get(x-1,y)===t)m|=8;return m}
function analyze(){const byType=Array.from({length:5},()=>new Map()),counts=new Array(5).fill(0);for(let y=0;y<state.n;y++)for(let x=0;x<state.n;x++){const t=get(x,y),m=maskFor(x,y);counts[t]++;byType[t].set(m,(byType[t].get(m)||0)+1)}
 const roleSet=new Set();let special=0;for(let t=0;t<5;t++)for(const [m,c] of byType[t]){roleSet.add(t+':'+m);if(m!==15)special+=c}
 let covered=0;for(let t=0;t<5;t++)covered+=byType[t].get(15)||0;const score=Math.round(covered/(state.n*state.n)*100);
 return{byType,counts,roles:roleSet.size,special,covered,score}}
function resize(){const r=wrap.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));ctx.setTransform(d,0,0,d,0,0);draw()}
function fit(){const r=wrap.getBoundingClientRect(),cell=Math.min((r.width-60)/state.n,(r.height-60)/state.n);state.zoom=Math.max(.25,Math.min(2.4,cell/32));state.panX=0;state.panY=0}
function draw(){if(!state.grid.length)return;const r=wrap.getBoundingClientRect(),cell=32*state.zoom,total=state.n*cell,ox=r.width/2-total/2+state.panX,oy=r.height/2-total/2+state.panY;ctx.clearRect(0,0,r.width,r.height);ctx.fillStyle='#071007';ctx.fillRect(0,0,r.width,r.height);const showArt=$('#art').checked,showTypes=$('#types').checked,showGrid=$('#grid').checked,showMasks=$('#masks').checked,showErr=$('#errors').checked,showObj=$('#objects').checked;
 for(let y=0;y<state.n;y++)for(let x=0;x<state.n;x++){const t=get(x,y),px=ox+x*cell,py=oy+y*cell,m=maskFor(x,y);if(px+cell<0||py+cell<0||px>r.width||py>r.height)continue;
   if(showArt&&state.tiles.length){const im=state.tiles[Math.floor(H(x,y,404)*state.tiles.length)%state.tiles.length];ctx.drawImage(im,px-1,py-1,cell+2,cell+2)}else{ctx.fillStyle=COLORS[t];ctx.fillRect(px,py,cell+.5,cell+.5)}
   if(showTypes&&showArt){ctx.fillStyle=COLORS[t]+'55';ctx.fillRect(px,py,cell,cell)}
   if(showErr&&m!==15&&t!==TYPE.bridge){ctx.strokeStyle='rgba(251,113,133,.65)';ctx.lineWidth=Math.max(1,1.2*state.zoom);ctx.strokeRect(px+1,py+1,cell-2,cell-2)}
   if(showGrid){ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=.7;ctx.strokeRect(px,py,cell,cell)}
   if(showMasks&&cell>20){ctx.fillStyle='#fff';ctx.font=`${Math.max(8,9*state.zoom)}px monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(String(m),px+cell/2,py+cell/2)}
 }
 if(showObj&&state.props.length)drawObjects(ox,oy,cell);
}
function drawObjects(ox,oy,cell){const density=+$('#density').value/100;for(let y=1;y<state.n-1;y++)for(let x=1;x<state.n-1;x++){const t=get(x,y);if(t!==TYPE.forest&&t!==TYPE.dirt)continue;if(H(x,y,701)>density)continue;let nearPath=false;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)if([TYPE.trail,TYPE.bridge,TYPE.water].includes(get(x+xx,y+yy)))nearPath=true;if(nearPath&&H(x,y,702)<.78)continue;const im=state.props[Math.floor(H(x,y,703)*state.props.length)%state.props.length],h=cell*(.55+H(x,y,704)*.5),ratio=im.naturalWidth/Math.max(1,im.naturalHeight),w=h*ratio,px=ox+(x+.5)*cell,py=oy+(y+.58)*cell;ctx.drawImage(im,px-w/2,py-h*.72,w,h)}}
function renderStats(){const s=state.stats;$('#cells').textContent=state.n*state.n;$('#roles').textContent=s.roles;$('#missing').textContent=s.special;$('#score').textContent=s.score+'%';const issues=$('#issues');issues.innerHTML='';const add=(c,t)=>issues.insertAdjacentHTML('beforeend',`<div class="issue ${c}">${t}</div>`);add('bad',`O pack atual tem <b>10 tiles genéricos</b>, mas o mapa gerado pediu <b>${s.roles} combinações tipo+máscara</b>.`);add('warn',`<b>${s.special}</b> células precisam de borda, canto, reta, T ou peça isolada — hoje não há metadados que garantam o encaixe.`);add('good','A macrogeração já separa floresta, clareiras, água, trilhas e pontes. O próximo passo é produzir/classificar as peças correspondentes às máscaras mais usadas.');
 const list=$('#maskList');list.innerHTML='';for(let t=0;t<5;t++){const arr=[...s.byType[t]].sort((a,b)=>b[1]-a[1]).slice(0,6);for(const [m,c] of arr)list.insertAdjacentHTML('beforeend',`<div class="maskItem"><b>${NAMES[t]}</b> · ${m}<br>${ROLE[m]} · ${c}x</div>`)}}
function loadAssets(){const loads=[];for(let i=1;i<=10;i++){const im=new Image();im.src=`assets/Map/dense-forest/tiles/tile_${String(i).padStart(3,'0')}.png?v=01721`;loads.push(new Promise(r=>{im.onload=()=>r(im);im.onerror=()=>r(null)}))}Promise.all(loads).then(a=>{state.tiles=a.filter(Boolean);buildLibrary();$('#status').textContent=`${state.tiles.length}/10 tiles · ${state.props.length}/21 objetos`;state.ready=true;draw()});
 const pl=[];for(let i=1;i<=21;i++){const im=new Image();im.src=`assets/Map/dense-forest/obstacles/obstacle_${String(i).padStart(3,'0')}.png?v=01721`;pl.push(new Promise(r=>{im.onload=()=>r(im);im.onerror=()=>r(null)}))}Promise.all(pl).then(a=>{state.props=a.filter(Boolean);$('#status').textContent=`${state.tiles.length}/10 tiles · ${state.props.length}/21 objetos`;draw()})}
function buildLibrary(){const el=$('#tileLibrary');el.innerHTML='';state.tiles.forEach((im,i)=>{const d=document.createElement('div');d.className='tileThumb';d.innerHTML=`<img src="${im.src}"><em>T${String(i+1).padStart(2,'0')}</em>`;el.appendChild(d)})}
function bindRange(id,out,suffix=''){const e=$(id),o=$(out);e.addEventListener('input',()=>{o.textContent=e.value+suffix;draw()})}bindRange('#water','#waterV','%');bindRange('#clearings','#clearV','%');bindRange('#trails','#trailV');bindRange('#density','#densityV','%');
$('#generate').onclick=generate;$('#random').onclick=()=>{$('#seed').value='CAOS-'+Math.random().toString(36).slice(2,8).toUpperCase();generate()};['#grid','#types','#masks','#errors','#objects','#art'].forEach(id=>$(id).addEventListener('change',draw));
$('#zin').onclick=()=>{state.zoom=Math.min(3,state.zoom*1.18);draw()};$('#zout').onclick=()=>{state.zoom=Math.max(.18,state.zoom/1.18);draw()};$('#reset').onclick=()=>{fit();draw()};
wrap.addEventListener('pointerdown',e=>{state.drag=true;state.lastX=e.clientX;state.lastY=e.clientY;wrap.setPointerCapture(e.pointerId)});wrap.addEventListener('pointermove',e=>{if(!state.drag)return;state.panX+=e.clientX-state.lastX;state.panY+=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;draw()});wrap.addEventListener('pointerup',()=>state.drag=false);wrap.addEventListener('pointercancel',()=>state.drag=false);wrap.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.18,Math.min(3,state.zoom*(e.deltaY>0?.9:1.1)));draw()},{passive:false});
window.addEventListener('resize',resize);loadAssets();generate();resize();
})();