(()=>{'use strict';
const SERVER='https://caos-live-game-server-va.onrender.com';
const btn=document.getElementById('multiplayerBtn'),overlay=document.getElementById('multiplayerWake'),status=document.getElementById('multiplayerWakeStatus'),time=document.getElementById('multiplayerWakeTime'),cancel=document.getElementById('multiplayerWakeCancel'),retry=document.getElementById('multiplayerWakeRetry');
if(!btn||!overlay)return;let controller=null,timer=0,started=0,cancelled=false;
function show(){overlay.classList.add('show')}function hide(){overlay.classList.remove('show')}function setStatus(t){if(status)status.textContent=t}function setTime(){if(time&&started)time.textContent=Math.max(0,Math.floor((Date.now()-started)/1000))+'s'}
function playerName(){const input=document.getElementById('playerName'),name=String(input?.value||localStorage.getItem('caos-player-name')||'Daniel').trim().slice(0,18)||'Daniel';try{localStorage.setItem('caos-player-name',name);localStorage.setItem('caosPlayerName',name)}catch{}return name}
async function pingOnce(){controller?.abort();controller=new AbortController();const kill=setTimeout(()=>controller.abort(),7000);try{const r=await fetch(SERVER+'/health?ts='+Date.now(),{cache:'no-store',signal:controller.signal});clearTimeout(kill);if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();return d?.ok===true}catch(e){clearTimeout(kill);return false}}
async function wake(){cancelled=false;started=Date.now();show();retry.style.display='none';setStatus('ACORDANDO SERVIDOR MULTIPLAYER...');clearInterval(timer);timer=setInterval(setTime,500);setTime();for(let attempt=1;attempt<=18&&!cancelled;attempt++){const ok=await pingOnce();if(ok&&!cancelled){setStatus('SERVIDOR ONLINE ✓ · ENTRANDO...');clearInterval(timer);const u=new URL(SERVER+'/multiplayer');u.searchParams.set('name',playerName());u.searchParams.set('server',SERVER);setTimeout(()=>location.href=u.toString(),250);return}setStatus(attempt<3?'INICIANDO RENDER...':'SERVIDOR ESTÁ ACORDANDO · TENTATIVA '+attempt);await new Promise(r=>setTimeout(r,1800))}if(cancelled)return;clearInterval(timer);setStatus('DEMOROU MAIS QUE O NORMAL. TENTE NOVAMENTE.');retry.style.display='block'}
btn.addEventListener('click',wake);cancel?.addEventListener('click',()=>{cancelled=true;controller?.abort();clearInterval(timer);hide()});retry?.addEventListener('click',wake);
})();
