(()=>{'use strict';
const ONLINE_VERSION='0.17.37-online.1',BASE_SOLO='0.17.37',TAG='01737o1',$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d',{alpha:false});
const ui={join:$('join'),status:$('status'),room:$('room'),roomLabel:$('roomLabel'),name:$('name'),create:$('create'),connect:$('connect'),role:$('role'),snap:$('snap'),level:$('level'),xp:$('xp'),kills:$('kills'),mobs:$('mobs'),hp:$('hp'),ping:$('ping'),fps:$('fps'),xpFill:$('xpFill'),joy:$('joy'),knob:$('knob'),invite:$('invite'),inviteBox:$('inviteBox'),inviteLink:$('inviteLink'),copy:$('copy'),leave:$('leave'),down:$('down'),downText:$('downText'),downFill:$('downFill'),skillPick:$('skillPick'),skillChoices:$('skillChoices'),gameOver:$('gameOver'),overKills:$('overKills'),overTime:$('overTime'),restart:$('restart')};
const params=new URLSearchParams(location.search),players=new Map(),enemies=new Map(),bullets=new Map(),keys=new Set(),rtts=[],snapIntervals=[],input={dx:0,dy:0},joy={active:false,pointerId:null,dx:0,dy:0};
const mk8=()=>({up:[],ur:[],right:[],dr:[],down:[],dl:[],left:[],ul:[]}),mk4=()=>({up:[],down:[],right:[],left:[]});
const sprites={player:mk8(),weapon:mk8(),normal:mk8(),elite1:mk8(),elite2:mk8(),corrupt1:mk8(),corrupt2:mk8(),boss1:mk4(),boss2:mk4()};
const ready={player:false,weapon:false,normal:false,elite1:false,elite2:false,corrupt1:false,corrupt2:false,boss1:false,boss2:false};
const MOB_HEIGHT={normal:62,elite1:86,elite2:94,corrupt1:108,corrupt2:118,bossScale:3.55},TYPE_RADIUS=[15,21,17,16,16,24,42,39];
const WL={down:{x:2,y:-1,maxW:38,maxH:58,flip:false},dr:{x:16,y:-6,maxW:62,maxH:38,flip:false},right:{x:20,y:-5,maxW:70,maxH:34,flip:true},ur:{x:15,y:-13,maxW:60,maxH:38,flip:false},up:{x:0,y:-19,maxW:38,maxH:58,flip:false},ul:{x:-15,y:-13,maxW:60,maxH:38,flip:false},left:{x:-20,y:-5,maxW:70,maxH:34,flip:false},dl:{x:-16,y:-6,maxW:62,maxH:38,flip:false}};
let ws=null,room='',myId='',myRole='',joined=false,manualClose=false,reconnectTimer=0,seq=0,pendingStop=0,lastFrame=performance.now(),fpsFrames=0,fpsAt=performance.now(),lastSnapAt=0,meta={totalKills:0,totalXp:0,wave:1,mobs:0,gameOver:false,durationMs:0,medDrop:null},world={width:3072,height:3072},skillKey='',map={cells:[],images:new Map(),ready:false,chunkSize:512,gridSize:6},serverVersion='';
const SESSION_KEY='caos-mp-session';let session=sessionStorage.getItem(SESSION_KEY)||crypto.randomUUID().replaceAll('-','');sessionStorage.setItem(SESSION_KEY,session);
ui.name.value=params.get('name')||localStorage.getItem('caosPlayerName')||localStorage.getItem('caos-player-name')||'';ui.room.value=cleanRoom(params.get('room')||'');
function cleanRoom(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}
function randomRoom(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',data=new Uint32Array(8);crypto.getRandomValues(data);return[...data].map(n=>chars[n%chars.length]).join('')}
function setStatus(text,ok=false){ui.status.textContent=text;ui.status.classList.toggle('ok',ok)}
function serverWs(){const raw=params.get('server')||location.origin;let u=new URL(raw,location.href);if(u.protocol==='https:')u.protocol='wss:';else if(u.protocol==='http:')u.protocol='ws:';if(!/^wss?:$/.test(u.protocol))u.protocol='wss:';u.pathname='/game';u.search='';u.hash='';return u.toString()}
function send(o){if(ws?.readyState===WebSocket.OPEN)try{ws.send(JSON.stringify(o))}catch{}}
function safeTarget(e){return e?.target instanceof Element&&!!e.target.closest('input,textarea,button,select,[contenteditable="true"]')}
function fmtTime(ms){const s=Math.max(0,Math.floor((ms||0)/1000)),m=Math.floor(s/60);return String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function playerSpeed(p){return 255*(1+((p?.skills?.speed||0)*.10))}
function openConnection(create=false,reconnecting=false){if(ws?.readyState===WebSocket.OPEN||ws?.readyState===WebSocket.CONNECTING)return;room=cleanRoom(create?randomRoom():ui.room.value);if(room.length<4){setStatus('CÓDIGO PRECISA TER 4 A 8 CARACTERES');ui.room.focus();return}ui.room.value=room;const name=String(ui.name.value||'PLAYER').replace(/[<>]/g,'').trim().slice(0,18)||'PLAYER';ui.name.value=name;try{localStorage.setItem('caosPlayerName',name);localStorage.setItem('caos-player-name',name)}catch{}manualClose=false;setStatus(reconnecting?'RECONECTANDO...':'CONECTANDO AO SERVIDOR...');let url;try{url=serverWs()}catch{return setStatus('ENDEREÇO DO SERVIDOR INVÁLIDO')}ws=new WebSocket(url);ws.addEventListener('open',()=>{setStatus('SERVIDOR ONLINE · ENTRANDO...');send({type:'join',room,name,session,clientVersion:ONLINE_VERSION,baseSolo:BASE_SOLO})});ws.addEventListener('message',({data})=>{try{handle(JSON.parse(data))}catch(e){console.warn('MP MESSAGE',e)}});ws.addEventListener('error',()=>{if(!joined)setStatus('SEM RESPOSTA DO SERVIDOR')});ws.addEventListener('close',()=>{const was=joined;joined=false;ws=null;if(!manualClose&&was){setStatus('CONEXÃO CAIU · RECONECTANDO...');clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>openConnection(false,true),1400)}else if(!manualClose)setStatus('SERVIDOR OFFLINE OU ACORDANDO')})}
function handle(m){if(m.type==='hello'){serverVersion=m.version||'';return setStatus('SERVIDOR RESPONDEU...')}if(m.type==='welcome'){joined=true;myId=m.id;myRole=m.role;session=m.session||session;sessionStorage.setItem(SESSION_KEY,session);room=m.room;world=m.world||world;serverVersion=m.version||serverVersion;const p=m.player;players.set(myId,{...p,x:p.x,y:p.y,tx:p.x,ty:p.y,local:true});ui.roomLabel.textContent='SALA '+room;ui.role.textContent=myRole==='p1'?'PLAYER 1':'PLAYER 2';ui.join.classList.remove('show');setStatus(m.reconnected?'RECONECTADO ✓':'MULTIPLAYER ONLINE ✓',true);if(m.map)prepareMap(m.map);updateInvite();return}if(m.type==='presence'){if(joined){const live=(m.players||[]).filter(p=>p.connected).map(p=>`${p.role?.toUpperCase()}:${p.name}`).join(' · ');setStatus(live||'AGUARDANDO JOGADOR',true)}return}if(m.type==='snapshot')return applySnapshot(m);if(m.type==='pong'){const rtt=Math.max(0,performance.now()-Number(m.clientTime||0));if(!Number.isFinite(rtt)||rtt>5000)return;rtts.push(rtt);if(rtts.length>20)rtts.shift();ui.ping.textContent=Math.round(rtts.reduce((a,b)=>a+b,0)/rtts.length)+'ms';return}if(m.type==='error'){setStatus(m.message||m.code||'ERRO');if(!joined){manualClose=true;ws?.close()}}}
function applySnapshot(m){const now=performance.now();if(lastSnapAt){snapIntervals.push(now-lastSnapAt);if(snapIntervals.length>30)snapIntervals.shift();const avg=snapIntervals.reduce((a,b)=>a+b,0)/snapIntervals.length;ui.snap.textContent='SNAP '+(1000/avg).toFixed(1)+'Hz'}lastSnapAt=now;meta=m.meta||meta;const liveP=new Set();for(const s of m.players||[]){liveP.add(s.id);let p=players.get(s.id);if(!p){p={...s,x:s.x,y:s.y,tx:s.x,ty:s.y,local:s.id===myId};players.set(s.id,p)}const oldX=p.x,oldY=p.y;Object.assign(p,s);p.x=oldX;p.y=oldY;p.tx=s.x;p.ty=s.y;if(s.id===myId){if(pendingStop&&s.ack>=pendingStop)pendingStop=0;const dx=s.x-p.x,dy=s.y-p.y,d=Math.hypot(dx,dy);if(d>150){p.x=s.x;p.y=s.y}else if(d>3){const stopped=Math.hypot(input.dx,input.dy)<.02,k=stopped?.18:.07;p.x+=dx*k;p.y+=dy*k}}}for(const id of [...players.keys()])if(id!==myId&&!liveP.has(id))players.delete(id);const liveE=new Set();for(const a of m.enemies||[]){const[id,x,y,hp,maxHp,vx,vy,typeIndex,walk,tier,boss,evolution=1,radius]=a;liveE.add(id);let e=enemies.get(id);if(!e){e={id,x,y,tx:x,ty:y};enemies.set(id,e)}Object.assign(e,{hp,maxHp,vx,vy,typeIndex,walk,tier,boss:!!boss,evolution:evolution||1,r:radius||TYPE_RADIUS[typeIndex]||16});e.tx=x;e.ty=y}for(const id of [...enemies.keys()])if(!liveE.has(id))enemies.delete(id);const liveB=new Set();for(const a of m.bullets||[]){const[id,x,y,vx,vy,ownerRole,flash]=a;liveB.add(id);let b=bullets.get(id);if(!b){b={id,x,y,tx:x,ty:y};bullets.set(id,b)}Object.assign(b,{vx,vy,ownerRole,flash:!!flash});b.tx=x;b.ty=y}for(const id of [...bullets.keys()])if(!liveB.has(id))bullets.delete(id);refreshUi();refreshSkill();if(meta.gameOver){ui.overKills.textContent=String(meta.totalKills||0);ui.overTime.textContent=fmtTime(meta.durationMs);ui.gameOver.classList.add('show')}else ui.gameOver.classList.remove('show')}
function refreshUi(){const me=players.get(myId);if(!me)return;ui.level.textContent=String(me.level||1);ui.xp.textContent=`${Math.floor(me.xp||0)}/${me.xpNeed||60}`;ui.kills.textContent=String(me.kills||0);ui.mobs.textContent=String(meta.mobs??enemies.size);ui.hp.textContent=`${Math.max(0,Math.round(me.hp||0))}/${Math.round(me.maxHp||100)}`;ui.xpFill.style.width=Math.max(0,Math.min(100,(me.xp||0)/Math.max(1,me.xpNeed||60)*100))+'%';if(me.down){ui.down.classList.add('show');ui.downText.textContent=(me.revive||0)>0?'REVIVENDO · '+Math.round((me.revive||0)*100)+'%':'VOCÊ CAIU · APROXIME SEU PARCEIRO';ui.downFill.style.width=Math.round((me.revive||0)*100)+'%'}else ui.down.classList.remove('show')}
function refreshSkill(){const me=players.get(myId),list=me?.choices||[],key=list.map(x=>x.id+':'+x.level).join('|');if(!list.length){skillKey='';ui.skillPick.classList.remove('show');return}if(key===skillKey&&ui.skillPick.classList.contains('show'))return;skillKey=key;ui.skillChoices.innerHTML='';for(const s of list){const b=document.createElement('button');b.className='skill';b.innerHTML=`<em>${String(s.rarity||'').toUpperCase()} · LV ${s.level||1}</em><b>${s.icon||'✦'} ${escapeHtml(s.name||s.id)}</b><small>${escapeHtml(s.desc||'')}</small>`;b.onclick=()=>{send({type:'skill-choice',skill:s.id});ui.skillPick.classList.remove('show')};ui.skillChoices.appendChild(b)}ui.skillPick.classList.add('show')}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function prepareMap(info){map.chunkSize=info.chunkSize||512;map.gridSize=info.gridSize||6;map.cells=info.cells||[];map.images.clear();map.ready=false;await Promise.all(map.cells.map(c=>new Promise(resolve=>{const im=new Image();im.onload=()=>{map.images.set(c.id,im);resolve()};im.onerror=()=>resolve();im.src=c.file+'?v='+TAG})));map.ready=map.cells.length>0&&map.images.size>0}
function loadImg(src){return new Promise(resolve=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src})}
async function loadSafe(folder,count,namer){const out=[];for(let i=1;i<=count;i++)out.push(await loadImg(`${folder}/${namer(i)}?v=${TAG}`));const good=out.map((x,i)=>x?i:-1).filter(i=>i>=0);if(!good.length)return null;for(let i=0;i<out.length;i++)if(!out[i]){let pick=good[0],dist=Math.abs(pick-i);for(const g of good){const d=Math.abs(g-i);if(d<dist){pick=g;dist=d}}out[i]=out[pick]}return out}
function mapPlayer32(a,t){if(!a||a.length<32)return false;t.down=a.slice(0,4);t.dr=a.slice(4,8);t.right=a.slice(8,12);t.ur=a.slice(12,16);t.up=a.slice(16,20);t.ul=a.slice(20,24);t.left=a.slice(24,28);t.dl=a.slice(28,32);return true}
function mapMob32(a,t){if(!a||a.length<32)return false;t.down=[a[0],a[8],a[16],a[24]];t.dr=[a[1],a[9],a[17],a[25]];t.right=[a[2],a[10],a[18],a[26]];t.ur=[a[3],a[11],a[19],a[27]];t.up=[a[4],a[12],a[20],a[28]];t.ul=[a[5],a[13],a[21],a[29]];t.left=[a[6],a[14],a[22],a[30]];t.dl=[a[7],a[15],a[23],a[31]];return true}
async function loadBoss(path,target,voidOrder=false){try{if(typeof JSZip==='undefined')return false;const r=await fetch(path+'?v='+TAG,{cache:'force-cache'});if(!r.ok)return false;const z=await JSZip.loadAsync(await r.arrayBuffer()),names=Object.keys(z.files).filter(n=>/\.png$/i.test(n)&&!z.files[n].dir).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),arr=[];for(const n of names.slice(0,16)){const blob=await z.files[n].async('blob'),url=URL.createObjectURL(blob),im=await loadImg(url);URL.revokeObjectURL(url);if(im)arr.push(im)}if(arr.length<16)return false;target.up=arr.slice(0,4);target.down=arr.slice(4,8);if(voidOrder){target.right=arr.slice(8,12);target.left=arr.slice(12,16)}else{target.left=arr.slice(8,12);target.right=arr.slice(12,16)}return true}catch{return false}}
(async()=>{const[p,w,n,e,c,e2,c2]=await Promise.all([loadSafe('/assets/player-armed',32,i=>'Posearma'+i+'.png'),loadSafe('/assets/weapons',32,i=>'frame_'+String(i).padStart(3,'0')+'.png'),loadSafe('/assets/mobs/Ogro',32,i=>'frame_'+String(i).padStart(3,'0')+'.png'),loadSafe('/assets/mobs/Ogro Elite',32,i=>'frame_'+String(i).padStart(3,'0')+'.png'),loadSafe('/assets/mobs/Ogro Corrompido',32,i=>'frame_'+String(i).padStart(3,'0')+'.png'),loadSafe('/assets/mobs/Ogro Elite II',32,i=>'frame_'+String(i).padStart(3,'0')+'.png'),loadSafe('/assets/mobs/Ogro Corrompido II',32,i=>'frame_'+String(i).padStart(3,'0')+'.png')]);ready.player=mapPlayer32(p,sprites.player);ready.weapon=mapPlayer32(w,sprites.weapon);ready.normal=mapMob32(n,sprites.normal);ready.elite1=mapMob32(e,sprites.elite1);ready.corrupt1=mapMob32(c,sprites.corrupt1);ready.elite2=mapMob32(e2,sprites.elite2);ready.corrupt2=mapMob32(c2,sprites.corrupt2);ready.boss1=await loadBoss('/assets/bosses/Ogroboss1.zip',sprites.boss1,false);ready.boss2=await loadBoss('/assets/bosses/Ogro2.0Boss.zip',sprites.boss2,true);console.log('MP ASSETS',ready)})();
function computeInput(){let dx=0,dy=0;if(keys.has('ArrowLeft')||keys.has('KeyA'))dx--;if(keys.has('ArrowRight')||keys.has('KeyD'))dx++;if(keys.has('ArrowUp')||keys.has('KeyW'))dy--;if(keys.has('ArrowDown')||keys.has('KeyS'))dy++;if(joy.active){dx=joy.dx;dy=joy.dy}const n=Math.hypot(dx,dy);if(n>1){dx/=n;dy/=n}input.dx=dx;input.dy=dy}
function sendInput(stop=false){if(!joined)return;computeInput();const me=players.get(myId),payload={type:'input',seq:++seq,dx:input.dx,dy:input.dy,clientTime:performance.now()};if(stop&&me){payload.stop=true;payload.px=Math.round(me.x*100)/100;payload.py=Math.round(me.y*100)/100;pendingStop=seq}send(payload)}
function dir8(angle){const oct=Math.round((((angle%(Math.PI*2))+Math.PI*2)%(Math.PI*2))/(Math.PI/4))%8;return['right','dr','down','dl','left','ul','up','ur'][oct]}
function dirVec(vx,vy,fallback='down'){if(Math.hypot(vx,vy)<.1)return fallback;return dir8(Math.atan2(vy,vx))}
function worldToScreen(x,y,cx,cy){return{x:x-cx+innerWidth/2,y:y-cy+innerHeight/2}}
function drawMap(cx,cy){ctx.fillStyle='#d8e8ef';ctx.fillRect(0,0,innerWidth,innerHeight);if(!map.ready)return;const C=map.chunkSize;ctx.save();ctx.imageSmoothingEnabled=true;for(const c of map.cells){const im=map.images.get(c.id);if(!im)continue;const q=worldToScreen(c.x*C,c.y*C,cx,cy);if(q.x>C||q.y>C||q.x+C<0||q.y+C<0)continue;ctx.drawImage(im,q.x-1,q.y-1,C+2,C+2)}ctx.restore();const g=ctx.createRadialGradient(innerWidth/2,innerHeight/2,100,innerWidth/2,innerHeight/2,Math.max(innerWidth,innerHeight)*.8);g.addColorStop(0,'rgba(230,248,255,0)');g.addColorStop(1,'rgba(33,73,94,.13)');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight)}
function drawWeapon(dir,frame,bob=0){if(!ready.weapon)return;const a=sprites.weapon[dir]?.length?sprites.weapon[dir]:sprites.weapon.down,im=a[frame%Math.max(1,a.length)]||a[0];if(!im?.naturalWidth)return;const z=WL[dir]||WL.down,ratio=im.naturalWidth/Math.max(1,im.naturalHeight);let w=z.maxW,h=w/ratio;if(h>z.maxH){h=z.maxH;w=h*ratio}ctx.save();ctx.translate(z.x,z.y+bob);if(z.flip)ctx.scale(-1,1);ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore()}
function drawPlayer(p,cx,cy){const q=worldToScreen(p.x,p.y,cx,cy),me=p.id===myId,dir=dir8(p.aim||0),moving=Math.hypot(p.vx||0,p.vy||0)>3,frame=moving?Math.floor(p.walk||0)%4:0,arr=sprites.player[dir]?.length?sprites.player[dir]:sprites.player.down,img=arr?.[frame],bob=moving?Math.sin((p.walk||0)*Math.PI*.5)*.8:0;ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,24,22,7,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=p.down?.35:1;const behind=['up','ur','ul'].includes(dir);if(behind)drawWeapon(dir,frame,bob);if(ready.player&&img?.naturalWidth){const h=me?70:72,ratio=img.naturalWidth/Math.max(1,img.naturalHeight),w=Math.min(76,h*ratio);ctx.drawImage(img,-w/2,35+bob-h,w,h)}else{ctx.fillStyle=me?'#8b5cf6':'#06b6d4';ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fill()}if(!behind)drawWeapon(dir,frame,bob);ctx.globalAlpha=1;if(p.shotFlash){ctx.save();ctx.globalCompositeOperation='screen';ctx.fillStyle='#fff6b5';ctx.shadowColor='#f59e0b';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(Math.cos(p.aim||0)*31,Math.sin(p.aim||0)*31,4,0,Math.PI*2);ctx.fill();ctx.restore()}if(p.choices?.length&&!p.down){ctx.strokeStyle='#67e8f9';ctx.lineWidth=2;ctx.shadowColor='#22d3ee';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,34,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle=me?'#ddd6fe':'#a5f3fc';ctx.textAlign='center';ctx.font='900 9px sans-serif';ctx.fillText(`${p.role?.toUpperCase()||''} · ${p.name||'PLAYER'}`,0,-43);if(p.down){ctx.fillStyle='#fecaca';ctx.fillText('CAÍDO',0,48)}ctx.restore()}
function enemyPack(e){if(e.boss){return e.typeIndex===6?{pack:sprites.boss1,ok:ready.boss1}:{pack:sprites.boss2,ok:ready.boss2}}if(e.tier===2){if(e.evolution===2&&ready.corrupt2)return{pack:sprites.corrupt2,ok:true};if(ready.corrupt1)return{pack:sprites.corrupt1,ok:true}}if(e.tier===1){if(e.evolution===2&&ready.elite2)return{pack:sprites.elite2,ok:true};if(ready.elite1)return{pack:sprites.elite1,ok:true}}return{pack:sprites.normal,ok:ready.normal}}
function mobHeight(e){if(e.boss)return(e.r||TYPE_RADIUS[e.typeIndex]||40)*MOB_HEIGHT.bossScale;if(e.tier===2)return e.evolution===2?MOB_HEIGHT.corrupt2:MOB_HEIGHT.corrupt1;if(e.tier===1)return e.evolution===2?MOB_HEIGHT.elite2:MOB_HEIGHT.elite1;return MOB_HEIGHT.normal}
function drawEnemy(e,cx,cy){const q=worldToScreen(e.x,e.y,cx,cy);if(q.x<-160||q.y<-160||q.x>innerWidth+160||q.y>innerHeight+160)return;const dir=dirVec(e.vx||0,e.vy||0,'down'),{pack,ok}=enemyPack(e),arr=pack[dir]?.length?pack[dir]:pack.down,frame=Math.floor((e.walk||0))%Math.max(1,arr?.length||1),img=arr?.[frame],h=mobHeight(e);ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(0,e.boss?31:20,e.boss?40:Math.max(18,h*.22),e.boss?10:7,0,0,Math.PI*2);ctx.fill();if(ok&&img?.naturalWidth){const ratio=img.naturalWidth/Math.max(1,img.naturalHeight),side=['left','right'].includes(dir)?.84:1,w=h*ratio*side;ctx.drawImage(img,-w/2,-h*.72,w,h)}else{ctx.fillStyle=e.boss?'#991b1b':e.tier===2?'#ef4444':e.tier===1?'#a855f7':'#4d7c0f';ctx.beginPath();ctx.arc(0,0,e.boss?36:18,0,Math.PI*2);ctx.fill()}const bw=e.boss?82:e.tier===2?60:54,by=e.boss?-70:-(h*.55);ctx.fillStyle='#24080d';ctx.fillRect(-bw/2,by,bw,5);ctx.fillStyle=e.tier===2?'#ef4444':e.tier===1?'#a855f7':e.boss?'#f59e0b':'#fb7185';ctx.fillRect(-bw/2,by,bw*Math.max(0,(e.hp||0)/Math.max(1,e.maxHp||1)),5);ctx.restore()}
function drawBullet(b,cx,cy){const q=worldToScreen(b.x,b.y,cx,cy),a=Math.atan2(b.vy,b.vx);ctx.save();ctx.translate(q.x,q.y);ctx.rotate(a);ctx.fillStyle=b.flash?'#fff7a8':b.ownerRole==='p2'?'#67e8f9':'#fde68a';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=b.flash?16:9;ctx.fillRect(-5,-2,b.flash?16:12,b.flash?5:4);ctx.restore()}
function drawMed(cx,cy){if(!meta.medDrop)return;const q=worldToScreen(meta.medDrop.x,meta.medDrop.y,cx,cy);ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#ecfdf5';ctx.strokeStyle='#10b981';ctx.lineWidth=3;ctx.fillRect(-10,-10,20,20);ctx.strokeRect(-10,-10,20,20);ctx.fillStyle='#ef4444';ctx.fillRect(-3,-7,6,14);ctx.fillRect(-7,-3,14,6);ctx.restore()}
function simulate(dt){computeInput();const me=players.get(myId);if(joined&&me&&!me.down&&!me.choices?.length){const speed=playerSpeed(me);me.x+=input.dx*speed*dt;me.y+=input.dy*speed*dt;me.vx=input.dx*speed;me.vy=input.dy*speed;if(input.dx||input.dy)me.walk=(me.walk||0)+dt*9}else if(me){me.vx=me.vy=0}for(const p of players.values()){if(p.id===myId)continue;const k=1-Math.pow(.0015,dt);p.x+=(p.tx-p.x)*k;p.y+=(p.ty-p.y)*k}for(const e of enemies.values()){const k=1-Math.pow(.004,dt);e.x+=(e.tx-e.x)*k;e.y+=(e.ty-e.y)*k}for(const b of bullets.values()){const k=1-Math.pow(.0004,dt);b.x+=(b.tx-b.x)*k;b.y+=(b.ty-b.y)*k}}
function resize(){const mobile=innerWidth<=760,dpr=Math.min(devicePixelRatio||1,mobile?1.15:1.5);canvas.width=Math.max(1,Math.floor(innerWidth*dpr));canvas.height=Math.max(1,Math.floor(innerHeight*dpr));canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function frame(now){const dt=Math.min(.04,Math.max(0,(now-lastFrame)/1000));lastFrame=now;simulate(dt);const me=players.get(myId),cx=me?.x??world.width/2,cy=me?.y??world.height/2;ctx.setTransform(canvas.width/innerWidth,0,0,canvas.height/innerHeight,0,0);drawMap(cx,cy);drawMed(cx,cy);for(const b of bullets.values())drawBullet(b,cx,cy);for(const e of enemies.values())drawEnemy(e,cx,cy);for(const p of players.values())drawPlayer(p,cx,cy);fpsFrames++;if(now-fpsAt>=500){ui.fps.textContent=String(Math.round(fpsFrames*1000/(now-fpsAt)));fpsFrames=0;fpsAt=now}refreshUi();requestAnimationFrame(frame)}
setInterval(()=>sendInput(false),33);setInterval(()=>{if(joined)send({type:'ping',clientTime:performance.now()})},1500);
addEventListener('resize',resize,{passive:true});addEventListener('keydown',e=>{if(safeTarget(e)||!joined)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code);sendInput(false)}});addEventListener('keyup',e=>{if(safeTarget(e))return;if(keys.delete(e.code))sendInput(Math.hypot(input.dx,input.dy)<.01)});
function moveJoy(e){const r=ui.joy.getBoundingClientRect();let dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),max=38,n=Math.hypot(dx,dy);if(n>max){dx=dx/n*max;dy=dy/n*max}joy.dx=dx/max;joy.dy=dy/max;ui.knob.style.transform=`translate(${dx}px,${dy}px)`}
ui.joy.addEventListener('pointerdown',e=>{if(!joined)return;joy.active=true;joy.pointerId=e.pointerId;ui.joy.setPointerCapture?.(e.pointerId);moveJoy(e);sendInput(false);e.preventDefault()});ui.joy.addEventListener('pointermove',e=>{if(joy.active&&e.pointerId===joy.pointerId){moveJoy(e);e.preventDefault()}});const releaseJoy=e=>{if(joy.pointerId!==null&&e.pointerId!==joy.pointerId)return;joy.active=false;joy.pointerId=null;joy.dx=joy.dy=0;ui.knob.style.transform='translate(0,0)';sendInput(true)};ui.joy.addEventListener('pointerup',releaseJoy);ui.joy.addEventListener('pointercancel',releaseJoy);
ui.room.addEventListener('input',()=>{const pos=ui.room.selectionStart;ui.room.value=cleanRoom(ui.room.value);try{ui.room.setSelectionRange(pos,pos)}catch{}});ui.room.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();ui.room.blur();openConnection(false)}});ui.name.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();ui.room.focus()}});ui.create.onclick=()=>openConnection(true);ui.connect.onclick=()=>openConnection(false);function updateInvite(){if(!room)return;const u=new URL(location.origin+'/multiplayer');u.searchParams.set('room',room);ui.inviteLink.value=u.toString()}ui.invite.onclick=()=>{updateInvite();ui.inviteBox.classList.toggle('show')};ui.copy.onclick=async()=>{updateInvite();try{await navigator.clipboard.writeText(ui.inviteLink.value);ui.copy.textContent='COPIADO ✓';setTimeout(()=>ui.copy.textContent='COPIAR LINK',1200)}catch{ui.inviteLink.focus();ui.inviteLink.select()}};ui.leave.onclick=()=>{manualClose=true;clearTimeout(reconnectTimer);joined=false;try{ws?.close(1000,'player_left')}catch{}ws=null;players.clear();enemies.clear();bullets.clear();myId=myRole='';ui.join.classList.add('show');ui.skillPick.classList.remove('show');ui.gameOver.classList.remove('show');ui.inviteBox.classList.remove('show');ui.role.textContent='AGUARDANDO';ui.roomLabel.textContent='SEM SALA';setStatus('DESCONECTADO')};ui.restart.onclick=()=>{send({type:'restart'});ui.gameOver.classList.remove('show')};
resize();requestAnimationFrame(frame);console.log('CAOS LIVE MULTIPLAYER',{online:ONLINE_VERSION,baseSolo:BASE_SOLO});
})();
