(()=>{'use strict';
const ONLINE_VERSION='0.17.37-online.3',BASE_SOLO='0.17.37',TAG='01737o3',$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d',{alpha:false});
const ui={join:$('join'),lobby:$('lobby'),status:$('netMini'),room:$('room'),roomLabel:$('roomLabel'),name:$('name'),create:$('create'),connect:$('connect'),level:$('level'),levelPct:$('levelPct'),xp:$('xp'),life:$('life'),mobs:$('mobCount'),fps:$('fpsHud'),xpFill:$('xpFill'),p1Name:$('p1Name'),p2Name:$('p2Name'),p1Ready:$('p1Ready'),p2Ready:$('p2Ready'),lobbyCode:$('lobbyCode'),loadingText:$('loadingText'),loadingPct:$('loadingPct'),loadingFill:$('loadingFill'),startMatch:$('startMatch'),leaveLobby:$('leaveLobby'),lobbyHint:$('lobbyHint'),startCover:$('startCover'),menu:$('menu'),menuBtn:$('menuBtn'),menuRoom:$('menuRoom'),menuStatus:$('menuStatus'),leave:$('leave'),resume:$('resume'),down:$('down'),downText:$('downText'),downFill:$('downFill'),skillPick:$('skillPick'),skillChoices:$('skillChoices'),gameOver:$('gameOver'),finalText:$('finalText'),restart:$('restart')};
const params=new URLSearchParams(location.search),players=new Map(),enemies=new Map(),bullets=new Map(),keys=new Set(),rtts=[],snapIntervals=[],input={dx:0,dy:0},touch={active:false,id:null,sx:0,sy:0,dx:0,dy:0};
const mk8=()=>({up:[],ur:[],right:[],dr:[],down:[],dl:[],left:[],ul:[]}),mk4=()=>({up:[],down:[],right:[],left:[]});
const sprites={player:mk8(),weapon:mk8(),normal:mk8(),elite1:mk8(),elite2:mk8(),corrupt1:mk8(),corrupt2:mk8(),boss1:mk4(),boss2:mk4()};
const ready={player:false,weapon:false,normal:false,elite1:false,elite2:false,corrupt1:false,corrupt2:false,boss1:false,boss2:false};
const MOB_HEIGHT={normal:62,elite1:86,elite2:94,corrupt1:108,corrupt2:118,bossScale:3.55},TYPE_RADIUS=[15,21,17,16,16,24,42,39];
const WL={down:{x:2,y:-1,maxW:38,maxH:58,flip:false},dr:{x:16,y:-6,maxW:62,maxH:38,flip:false},right:{x:20,y:-5,maxW:70,maxH:34,flip:true},ur:{x:15,y:-13,maxW:60,maxH:38,flip:false},up:{x:0,y:-19,maxW:38,maxH:58,flip:false},ul:{x:-15,y:-13,maxW:60,maxH:38,flip:false},left:{x:-20,y:-5,maxW:70,maxH:34,flip:false},dl:{x:-16,y:-6,maxW:62,maxH:38,flip:false}};
let ws=null,room='',myId='',myRole='',joined=false,started=false,manualClose=false,reconnectTimer=0,seq=0,pendingStop=0,lastFrame=performance.now(),fpsFrames=0,fpsAt=performance.now(),lastSnapAt=0,firstSnapshot=false,serverVersion='',lobbyState={players:[],canStart:false,status:'waiting'},skillKey='',skillPendingKey='',skillPendingUntil=0;
let meta={totalKills:0,totalXp:0,wave:1,mobs:0,gameOver:false,durationMs:0,medDrop:null},world={width:3072,height:3072};
const map={cells:[],images:new Map(),ready:false,chunkSize:512,gridSize:6,info:null};
const loader={staticStarted:false,staticPromise:null,staticDone:false,mapDone:false,readySent:false,progress:0,text:'PREPARANDO ASSETS...'};
const SESSION_KEY='caos-mp-session-v2';let session=sessionStorage.getItem(SESSION_KEY)||crypto.randomUUID().replaceAll('-','');sessionStorage.setItem(SESSION_KEY,session);
ui.name.value=params.get('name')||localStorage.getItem('caosPlayerName')||localStorage.getItem('caos-player-name')||'';ui.room.value=cleanRoom(params.get('room')||'');
function cleanRoom(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8)}
function randomRoom(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',data=new Uint32Array(8);crypto.getRandomValues(data);return[...data].map(n=>chars[n%chars.length]).join('')}
function safeTarget(e){return e?.target instanceof Element&&!!e.target.closest('input,textarea,button,select,[contenteditable="true"]')}
function fmtTime(ms){const s=Math.max(0,Math.floor((ms||0)/1000)),m=Math.floor(s/60);return String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function setNet(text,ok=false){ui.status.textContent=text;ui.status.classList.toggle('ok',ok)}
function setLoad(pct,text){loader.progress=Math.max(loader.progress,Math.min(100,Math.round(pct)));if(text)loader.text=text;ui.loadingPct.textContent=loader.progress+'%';ui.loadingFill.style.width=loader.progress+'%';ui.loadingText.textContent=loader.text}
function serverWs(){const raw='https://caos-live-game-server-va.onrender.com';const u=new URL(raw);u.protocol='wss:';u.pathname='/game';u.search='';u.hash='';return u.toString()}
function send(o){if(ws?.readyState===WebSocket.OPEN)try{ws.send(JSON.stringify(o))}catch{}}
function showJoin(){ui.join.classList.add('show');ui.lobby.classList.remove('show');ui.menu.classList.remove('show');ui.startCover.classList.remove('show')}
function showLobby(){ui.join.classList.remove('show');ui.lobby.classList.add('show');ui.menu.classList.remove('show');ui.startCover.classList.remove('show')}
function setReadyBadge(el,p){if(!p?.connected){el.textContent='OFFLINE';el.classList.remove('ready');return}if(p.ready){el.textContent='PRONTO ✓';el.classList.add('ready')}else{el.textContent='CARREGANDO...';el.classList.remove('ready')}}
function renderLobby(){const p1=lobbyState.players.find(p=>p.role==='p1'),p2=lobbyState.players.find(p=>p.role==='p2');ui.p1Name.textContent=p1?.name||'AGUARDANDO...';ui.p2Name.textContent=p2?.name||'AGUARDANDO...';setReadyBadge(ui.p1Ready,p1);setReadyBadge(ui.p2Ready,p2);ui.lobbyCode.textContent=room||'--------';ui.menuRoom.textContent=room||'--------';if(myRole==='p1'){ui.startMatch.style.display='block';ui.startMatch.disabled=!lobbyState.canStart;ui.startMatch.textContent=lobbyState.canStart?'INICIAR PARTIDA':'AGUARDANDO OS DOIS...';ui.lobbyHint.textContent=lobbyState.canStart?'Os dois celulares terminaram o carregamento. Você pode iniciar.':'Passe somente o código para o outro jogador. A partida não começa sozinha.'}else{ui.startMatch.style.display='none';ui.lobbyHint.textContent=lobbyState.canStart?'Tudo carregado. Aguardando o Player 1 iniciar a partida.':'Carregando e aguardando o Player 1.'}}
function openConnection(create=false,reconnecting=false){if(ws?.readyState===WebSocket.OPEN||ws?.readyState===WebSocket.CONNECTING)return;room=cleanRoom(create?randomRoom():ui.room.value);if(room.length<4){setNet('CÓDIGO PRECISA TER 4 A 8 CARACTERES');ui.room.focus();return}ui.room.value=room;const name=String(ui.name.value||'PLAYER').replace(/[<>]/g,'').trim().slice(0,18)||'PLAYER';ui.name.value=name;try{localStorage.setItem('caosPlayerName',name);localStorage.setItem('caos-player-name',name)}catch{}manualClose=false;setNet(reconnecting?'SERVIDOR: RECONECTANDO...':'SERVIDOR: CONECTANDO...');let url;try{url=serverWs()}catch{return setNet('SERVIDOR: ENDEREÇO INVÁLIDO')}ws=new WebSocket(url);ws.addEventListener('open',()=>{setNet('SERVIDOR: ONLINE · ENTRANDO...');send({type:'join',room,name,session,create:!!create,clientVersion:ONLINE_VERSION,baseSolo:BASE_SOLO})});ws.addEventListener('message',({data})=>{try{handle(JSON.parse(data))}catch(e){console.warn('MP MESSAGE',e)}});ws.addEventListener('error',()=>{if(!joined)setNet('SERVIDOR: SEM RESPOSTA')});ws.addEventListener('close',()=>{const was=joined;joined=false;ws=null;if(!manualClose&&was){setNet('SERVIDOR: CONEXÃO CAIU · RECONECTANDO...');clearTimeout(reconnectTimer);reconnectTimer=setTimeout(()=>openConnection(false,true),1400)}else if(!manualClose)setNet('SERVIDOR: OFFLINE OU ACORDANDO')})}
function handle(m){if(m.type==='hello'){serverVersion=m.version||'';return setNet('SERVIDOR: RESPONDEU...')}if(m.type==='welcome'){joined=true;myId=m.id;myRole=m.role;session=m.session||session;sessionStorage.setItem(SESSION_KEY,session);room=m.room;world=m.world||world;serverVersion=m.version||serverVersion;started=m.roomState==='running';firstSnapshot=false;const p=m.player;players.set(myId,{...p,x:p.x,y:p.y,tx:p.x,ty:p.y,local:true});ui.roomLabel.textContent='MULTIPLAYER · SALA '+room;ui.menuRoom.textContent=room;lobbyState=m.lobby||lobbyState;renderLobby();if(started){ui.join.classList.remove('show');ui.lobby.classList.remove('show');ui.startCover.classList.add('show')}else showLobby();if(m.map){map.info=m.map;ensureClientReady(m.map)}setNet(m.reconnected?'SERVIDOR: RECONECTADO ✓':'SERVIDOR: SALA '+room,true);return}if(m.type==='presence'||m.type==='lobby'){lobbyState={...lobbyState,...m,players:m.players||lobbyState.players};renderLobby();if(!started)showLobby();return}if(m.type==='match-start'){started=true;firstSnapshot=false;meta={totalKills:0,totalXp:0,wave:1,mobs:0,gameOver:false,durationMs:0,medDrop:null};enemies.clear();bullets.clear();ui.lobby.classList.remove('show');ui.gameOver.classList.remove('show');ui.startCover.classList.add('show');setNet('SERVIDOR: PARTIDA INICIADA ✓',true);return}if(m.type==='snapshot')return applySnapshot(m);if(m.type==='pong'){const rtt=Math.max(0,performance.now()-Number(m.clientTime||0));if(Number.isFinite(rtt)&&rtt<5000){rtts.push(rtt);if(rtts.length>20)rtts.shift();const avg=Math.round(rtts.reduce((a,b)=>a+b,0)/rtts.length);setNet(`SERVIDOR: ${avg}ms · ${lobbyState.players.filter(p=>p.connected).length}/2 JOGADORES`,true)}return}if(m.type==='error'){setNet('ERRO: '+(m.message||m.code||'DESCONHECIDO'));if(m.code==='room_exists'){manualClose=true;try{ws?.close()}catch{}ws=null;joined=false;setTimeout(()=>openConnection(true,false),250);return}if(!joined){manualClose=true;try{ws?.close()}catch{}}}}
function applySnapshot(m){if(!started)return;const now=performance.now();if(!firstSnapshot){firstSnapshot=true;ui.startCover.classList.remove('show')}if(lastSnapAt){snapIntervals.push(now-lastSnapAt);if(snapIntervals.length>30)snapIntervals.shift()}lastSnapAt=now;meta=m.meta||meta;const liveP=new Set();for(const s of m.players||[]){liveP.add(s.id);let p=players.get(s.id);if(!p){p={...s,x:s.x,y:s.y,tx:s.x,ty:s.y,local:s.id===myId};players.set(s.id,p)}const ox=p.x,oy=p.y;Object.assign(p,s);p.x=ox;p.y=oy;p.tx=s.x;p.ty=s.y;if(s.id===myId){if(pendingStop&&s.ack>=pendingStop)pendingStop=0;const dx=s.x-p.x,dy=s.y-p.y,d=Math.hypot(dx,dy);if(d>150){p.x=s.x;p.y=s.y}else if(d>3){const stopped=Math.hypot(input.dx,input.dy)<.02,k=stopped?.18:.07;p.x+=dx*k;p.y+=dy*k}}}for(const id of [...players.keys()])if(id!==myId&&!liveP.has(id))players.delete(id);const liveE=new Set();for(const a of m.enemies||[]){const[id,x,y,hp,maxHp,vx,vy,typeIndex,walk,tier,boss,evolution=1,radius]=a;liveE.add(id);let e=enemies.get(id);if(!e){e={id,x,y,tx:x,ty:y};enemies.set(id,e)}Object.assign(e,{hp,maxHp,vx,vy,typeIndex,walk,tier,boss:!!boss,evolution:evolution||1,r:radius||TYPE_RADIUS[typeIndex]||16});e.tx=x;e.ty=y}for(const id of [...enemies.keys()])if(!liveE.has(id))enemies.delete(id);const liveB=new Set();for(const a of m.bullets||[]){const[id,x,y,vx,vy,ownerRole,flash]=a;liveB.add(id);let b=bullets.get(id);if(!b){b={id,x,y,tx:x,ty:y};bullets.set(id,b)}Object.assign(b,{vx,vy,ownerRole,flash:!!flash});b.tx=x;b.ty=y}for(const id of [...bullets.keys()])if(!liveB.has(id))bullets.delete(id);refreshUi();refreshSkill();if(meta.gameOver){ui.finalText.textContent=`${meta.totalKills||0} abates · ${fmtTime(meta.durationMs)}`;ui.gameOver.classList.add('show')}else ui.gameOver.classList.remove('show')}
function refreshUi(){const me=players.get(myId);if(!me)return;const need=Math.max(1,me.xpNeed||60),pct=Math.max(0,Math.min(100,(me.xp||0)/need*100));ui.level.textContent=String(me.level||1);ui.levelPct.textContent=Math.round(pct)+'%';ui.xp.textContent=String(Math.floor(me.xp||0));ui.life.textContent=String(Math.max(0,Math.round(me.hp||0)));ui.mobs.textContent=String(meta.mobs??enemies.size);ui.xpFill.style.width=pct+'%';if(me.down){ui.down.classList.add('show');ui.downText.textContent=(me.revive||0)>0?'REVIVENDO · '+Math.round((me.revive||0)*100)+'%':'VOCÊ CAIU · APROXIME SEU PARCEIRO';ui.downFill.style.width=Math.round((me.revive||0)*100)+'%'}else ui.down.classList.remove('show')}
function refreshSkill(){const me=players.get(myId),list=me?.choices||[],key=list.map(x=>x.id+':'+x.level).join('|'),now=performance.now();if(!list.length){skillKey='';skillPendingKey='';skillPendingUntil=0;ui.skillPick.classList.remove('show');return}if(skillPendingKey===key&&now<skillPendingUntil){ui.skillPick.classList.remove('show');return}if(key===skillKey&&ui.skillPick.classList.contains('show'))return;skillKey=key;ui.skillChoices.innerHTML='';for(const s of list){const b=document.createElement('button');b.className='skill '+(s.rarity||'common');b.innerHTML=`<span class="ico">${s.icon||'✦'}</span><b>${escapeHtml(s.name||s.id)}</b><em>${String(s.rarity||'').toUpperCase()}</em><small>${escapeHtml(s.desc||'')}</small><span class="lvl">LV ${s.level||1}</span>`;b.onclick=()=>{if(skillPendingKey===key&&performance.now()<skillPendingUntil)return;skillPendingKey=key;skillPendingUntil=performance.now()+2500;for(const x of ui.skillChoices.querySelectorAll('button'))x.disabled=true;ui.skillPick.classList.remove('show');send({type:'skill-choice',skill:s.id})};ui.skillChoices.appendChild(b)}ui.skillPick.classList.add('show')}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function loadImg(src){return new Promise(resolve=>{const im=new Image();im.decoding='async';im.onload=()=>resolve(im);im.onerror=()=>resolve(null);im.src=src})}
async function loadImgRetry(src,retries=2){for(let i=0;i<=retries;i++){const sep=src.includes('?')?'&':'?',im=await loadImg(src+sep+'try='+i);if(im)return im;if(i<retries)await new Promise(r=>setTimeout(r,180*(i+1)))}return null}
async function loadSafe(folder,count,namer){const arr=await Promise.all(Array.from({length:count},(_,k)=>loadImgRetry(`${folder}/${namer(k+1)}?v=${TAG}`,1)));const good=arr.map((x,i)=>x?i:-1).filter(i=>i>=0);if(!good.length)return null;for(let i=0;i<arr.length;i++)if(!arr[i]){let pick=good[0],dist=Math.abs(pick-i);for(const g of good){const d=Math.abs(g-i);if(d<dist){pick=g;dist=d}}arr[i]=arr[pick]}return arr}
function mapPlayer32(a,t){if(!a||a.length<32)return false;t.down=a.slice(0,4);t.dr=a.slice(4,8);t.right=a.slice(8,12);t.ur=a.slice(12,16);t.up=a.slice(16,20);t.ul=a.slice(20,24);t.left=a.slice(24,28);t.dl=a.slice(28,32);return true}
function mapMob32(a,t){if(!a||a.length<32)return false;t.down=[a[0],a[8],a[16],a[24]];t.dr=[a[1],a[9],a[17],a[25]];t.right=[a[2],a[10],a[18],a[26]];t.ur=[a[3],a[11],a[19],a[27]];t.up=[a[4],a[12],a[20],a[28]];t.ul=[a[5],a[13],a[21],a[29]];t.left=[a[6],a[14],a[22],a[30]];t.dl=[a[7],a[15],a[23],a[31]];return true}
async function optionalPack(folder,target){try{const probe=await fetch(`${folder}/frame_001.png?v=${TAG}`,{cache:'force-cache'});if(!probe.ok)return false;const a=await loadSafe(folder,32,i=>'frame_'+String(i).padStart(3,'0')+'.png');return mapMob32(a,target)}catch{return false}}
async function loadBoss(path,target,voidOrder=false){try{if(typeof JSZip==='undefined')return false;const r=await fetch(path+'?v='+TAG,{cache:'force-cache'});if(!r.ok)return false;const z=await JSZip.loadAsync(await r.arrayBuffer()),names=Object.keys(z.files).filter(n=>/\.png$/i.test(n)&&!z.files[n].dir).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),arr=[];for(const n of names.slice(0,16)){const blob=await z.files[n].async('blob'),url=URL.createObjectURL(blob),im=await loadImg(url);URL.revokeObjectURL(url);if(im)arr.push(im)}if(arr.length<16)return false;target.up=arr.slice(0,4);target.down=arr.slice(4,8);if(voidOrder){target.right=arr.slice(8,12);target.left=arr.slice(12,16)}else{target.left=arr.slice(8,12);target.right=arr.slice(12,16)}return true}catch{return false}}
function beginStaticPreload(){if(loader.staticStarted)return loader.staticPromise;loader.staticStarted=true;loader.staticPromise=(async()=>{const tasks=[['PLAYER',async()=>{const a=await loadSafe('/assets/player-armed',32,i=>'Posearma'+i+'.png');ready.player=mapPlayer32(a,sprites.player)}],['ARMA',async()=>{const a=await loadSafe('/assets/weapons',32,i=>'frame_'+String(i).padStart(3,'0')+'.png');ready.weapon=mapPlayer32(a,sprites.weapon)}],['OGRO',async()=>{const a=await loadSafe('/assets/mobs/Ogro',32,i=>'frame_'+String(i).padStart(3,'0')+'.png');ready.normal=mapMob32(a,sprites.normal)}],['ELITE',async()=>{const a=await loadSafe('/assets/mobs/Ogro Elite',32,i=>'frame_'+String(i).padStart(3,'0')+'.png');ready.elite1=mapMob32(a,sprites.elite1)}],['CORROMPIDO',async()=>{const a=await loadSafe('/assets/mobs/Ogro Corrompido',32,i=>'frame_'+String(i).padStart(3,'0')+'.png');ready.corrupt1=mapMob32(a,sprites.corrupt1)}],['BOSSES',async()=>{const b=await Promise.all([loadBoss('/assets/bosses/Ogroboss1.zip',sprites.boss1,false),loadBoss('/assets/bosses/Ogro2.0Boss.zip',sprites.boss2,true)]);ready.boss1=b[0];ready.boss2=b[1]}]];let done=0;await Promise.all(tasks.map(async([name,fn])=>{await fn();done++;setLoad(8+done/tasks.length*56,'CARREGANDO '+name+'...')}));const adv=await Promise.all([optionalPack('/assets/mobs/Ogro Elite II',sprites.elite2),optionalPack('/assets/mobs/Ogro Corrompido II',sprites.corrupt2)]);ready.elite2=adv[0];ready.corrupt2=adv[1];if(!ready.player||!ready.weapon||!ready.normal||!ready.elite1||!ready.corrupt1)throw Error('ASSETS ESSENCIAIS NÃO CARREGARAM');loader.staticDone=true;setLoad(68,'SKINS CARREGADAS ✓');return true})().catch(e=>{console.error(e);setLoad(loader.progress,'FALHA AO CARREGAR SKINS · REABRA A SALA');throw e});return loader.staticPromise}
async function prepareMap(info){map.info=info;map.chunkSize=info.chunkSize||512;map.gridSize=info.gridSize||6;map.cells=info.cells||[];map.images.clear();map.ready=false;const unique=[...new Set(map.cells.map(c=>c.file))];let done=0,failed=[];const queue=[...unique],workers=Array.from({length:Math.min(8,unique.length)},async()=>{while(queue.length){const file=queue.shift(),im=await loadImgRetry(file+'?v='+TAG,3);if(im)map.images.set(file,im);else failed.push(file);done++;setLoad(68+(done/Math.max(1,unique.length))*31,`CARREGANDO MAPA ${done}/${unique.length}...`)}});await Promise.all(workers);if(failed.length)throw Error('MAPA INCOMPLETO: '+failed.length+' ARQUIVOS');map.ready=map.cells.length>0&&map.images.size===unique.length;loader.mapDone=map.ready;setLoad(99,'MAPA E SKINS PRONTOS ✓');return map.ready}
async function ensureClientReady(info){loader.readySent=false;try{await Promise.all([beginStaticPreload(),prepareMap(info)]);setLoad(100,'PRONTO · AGUARDANDO OUTRO JOGADOR');if(!loader.readySent){loader.readySent=true;send({type:'ready',ready:true,clientVersion:ONLINE_VERSION})}}catch(e){console.error('PRELOAD',e);setLoad(loader.progress,'FALHA NO CARREGAMENTO · REENTRE NA SALA');send({type:'ready',ready:false})}}
beginStaticPreload().catch(()=>{});
function computeInput(){let dx=0,dy=0;if(keys.has('ArrowLeft')||keys.has('KeyA'))dx--;if(keys.has('ArrowRight')||keys.has('KeyD'))dx++;if(keys.has('ArrowUp')||keys.has('KeyW'))dy--;if(keys.has('ArrowDown')||keys.has('KeyS'))dy++;if(touch.active){dx=touch.dx;dy=touch.dy}const n=Math.hypot(dx,dy);if(n>1){dx/=n;dy/=n}input.dx=dx;input.dy=dy}
function sendInput(stop=false){if(!joined||!started)return;computeInput();const me=players.get(myId),payload={type:'input',seq:++seq,dx:input.dx,dy:input.dy,clientTime:performance.now()};if(stop&&me){payload.stop=true;payload.px=Math.round(me.x*100)/100;payload.py=Math.round(me.y*100)/100;pendingStop=seq}send(payload)}
function dir8(angle){const oct=Math.round((((angle%(Math.PI*2))+Math.PI*2)%(Math.PI*2))/(Math.PI/4))%8;return['right','dr','down','dl','left','ul','up','ur'][oct]}
function dirVec(vx,vy,fallback='down'){if(Math.hypot(vx,vy)<.1)return fallback;return dir8(Math.atan2(vy,vx))}
function worldToScreen(x,y,cx,cy){return{x:x-cx+innerWidth/2,y:y-cy+innerHeight/2}}
function drawMap(cx,cy){const g=ctx.createLinearGradient(0,0,0,innerHeight);g.addColorStop(0,'#9ebdca');g.addColorStop(1,'#c8dce5');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);if(!map.ready)return;const C=map.chunkSize;ctx.save();ctx.imageSmoothingEnabled=true;for(const c of map.cells){const im=map.images.get(c.file);if(!im)continue;const p=worldToScreen(c.x*C,c.y*C,cx,cy);if(p.x>C||p.y>C||p.x+C<0||p.y+C<0)continue;ctx.drawImage(im,Math.floor(p.x)-2,Math.floor(p.y)-2,C+4,C+4)}ctx.restore();const fog=ctx.createRadialGradient(innerWidth/2,innerHeight/2,100,innerWidth/2,innerHeight/2,Math.max(innerWidth,innerHeight)*.8);fog.addColorStop(0,'rgba(230,248,255,0)');fog.addColorStop(1,'rgba(33,73,94,.13)');ctx.fillStyle=fog;ctx.fillRect(0,0,innerWidth,innerHeight)}
function drawWeapon(dir,frame,bob=0){if(!ready.weapon)return;const a=sprites.weapon[dir]?.length?sprites.weapon[dir]:sprites.weapon.down,im=a[frame%Math.max(1,a.length)]||a[0];if(!im?.naturalWidth)return;const z=WL[dir]||WL.down,ratio=im.naturalWidth/Math.max(1,im.naturalHeight);let w=z.maxW,h=w/ratio;if(h>z.maxH){h=z.maxH;w=h*ratio}ctx.save();ctx.translate(z.x,z.y+bob);if(z.flip)ctx.scale(-1,1);ctx.drawImage(im,-w/2,-h/2,w,h);ctx.restore()}
function drawPlayer(p,cx,cy){const q=worldToScreen(p.x,p.y,cx,cy),me=p.id===myId,dir=dir8(p.aim||0),moving=Math.hypot(p.vx||0,p.vy||0)>3,frame=moving?Math.floor(p.walk||0)%4:0,arr=sprites.player[dir]?.length?sprites.player[dir]:sprites.player.down,img=arr?.[frame],bob=moving?Math.sin((p.walk||0)*Math.PI*.5)*.8:0;ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(0,24,22,7,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=p.down?.35:1;const behind=['up','ur','ul'].includes(dir);if(behind)drawWeapon(dir,frame,bob);if(ready.player&&img?.naturalWidth){const h=70,ratio=img.naturalWidth/Math.max(1,img.naturalHeight),w=Math.min(76,h*ratio);ctx.drawImage(img,-w/2,35+bob-h,w,h)}else{ctx.fillStyle=me?'#8b5cf6':'#06b6d4';ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.fill()}if(!behind)drawWeapon(dir,frame,bob);ctx.globalAlpha=1;if(p.shotFlash){ctx.save();ctx.globalCompositeOperation='screen';ctx.fillStyle='#fff6b5';ctx.shadowColor='#f59e0b';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(Math.cos(p.aim||0)*31,Math.sin(p.aim||0)*31,4,0,Math.PI*2);ctx.fill();ctx.restore()}if(p.choices?.length&&!p.down){ctx.strokeStyle='#67e8f9';ctx.lineWidth=2;ctx.shadowColor='#22d3ee';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,34,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0}ctx.fillStyle=me?'#ddd6fe':'#a5f3fc';ctx.textAlign='center';ctx.font='900 9px sans-serif';ctx.fillText(`${p.role?.toUpperCase()||''} · ${p.name||'PLAYER'}`,0,-43);if(p.down){ctx.fillStyle='#fecaca';ctx.fillText('CAÍDO',0,48)}ctx.restore()}
function enemyPack(e){if(e.boss)return e.typeIndex===6?{pack:sprites.boss1,ok:ready.boss1}:{pack:sprites.boss2,ok:ready.boss2};if(e.tier===2){if(e.evolution===2&&ready.corrupt2)return{pack:sprites.corrupt2,ok:true};if(ready.corrupt1)return{pack:sprites.corrupt1,ok:true}}if(e.tier===1){if(e.evolution===2&&ready.elite2)return{pack:sprites.elite2,ok:true};if(ready.elite1)return{pack:sprites.elite1,ok:true}}return{pack:sprites.normal,ok:ready.normal}}
function mobHeight(e){if(e.boss)return(e.r||TYPE_RADIUS[e.typeIndex]||40)*MOB_HEIGHT.bossScale;if(e.tier===2)return e.evolution===2?MOB_HEIGHT.corrupt2:MOB_HEIGHT.corrupt1;if(e.tier===1)return e.evolution===2?MOB_HEIGHT.elite2:MOB_HEIGHT.elite1;return MOB_HEIGHT.normal}
function drawEnemy(e,cx,cy){const q=worldToScreen(e.x,e.y,cx,cy);if(q.x<-170||q.y<-170||q.x>innerWidth+170||q.y>innerHeight+170)return;const dir=dirVec(e.vx||0,e.vy||0,'down'),{pack,ok}=enemyPack(e),arr=pack[dir]?.length?pack[dir]:pack.down,frame=Math.floor(e.walk||0)%Math.max(1,arr?.length||1),img=arr?.[frame],h=mobHeight(e);ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(0,e.boss?31:20,e.boss?40:Math.max(18,h*.22),e.boss?10:7,0,0,Math.PI*2);ctx.fill();if(ok&&img?.naturalWidth){const ratio=img.naturalWidth/Math.max(1,img.naturalHeight),side=['left','right'].includes(dir)?.84:1,w=h*ratio*side;ctx.drawImage(img,-w/2,-h*.72,w,h)}else{ctx.fillStyle=e.boss?'#991b1b':e.tier===2?'#ef4444':e.tier===1?'#a855f7':'#4d7c0f';ctx.beginPath();ctx.arc(0,0,e.boss?36:18,0,Math.PI*2);ctx.fill()}const bw=e.boss?82:e.tier===2?60:54,by=e.boss?-70:-(h*.55);ctx.fillStyle='#24080d';ctx.fillRect(-bw/2,by,bw,5);ctx.fillStyle=e.tier===2?'#ef4444':e.tier===1?'#a855f7':e.boss?'#f59e0b':'#fb7185';ctx.fillRect(-bw/2,by,bw*Math.max(0,(e.hp||0)/Math.max(1,e.maxHp||1)),5);ctx.restore()}
function drawBullet(b,cx,cy){const q=worldToScreen(b.x,b.y,cx,cy);ctx.save();ctx.fillStyle=b.flash?'#fff7ae':'#f8fafc';ctx.shadowColor=b.flash?'#f59e0b':'#67e8f9';ctx.shadowBlur=b.flash?13:6;ctx.beginPath();ctx.arc(q.x,q.y,b.flash?4:2.5,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawMed(cx,cy){if(!meta.medDrop)return;const q=worldToScreen(meta.medDrop.x,meta.medDrop.y,cx,cy);ctx.save();ctx.translate(q.x,q.y);ctx.fillStyle='#dc2626';ctx.fillRect(-13,-5,26,10);ctx.fillRect(-5,-13,10,26);ctx.restore()}
function simulate(dt){for(const p of players.values()){if(p.id===myId){if(started&&!p.down&&!p.choices){computeInput();p.x+=input.dx*255*(1+((p.skills?.speed||0)*.10))*dt;p.y+=input.dy*255*(1+((p.skills?.speed||0)*.10))*dt}continue}p.x+=(p.tx-p.x)*Math.min(1,dt*10);p.y+=(p.ty-p.y)*Math.min(1,dt*10)}for(const e of enemies.values()){e.x+=(e.tx-e.x)*Math.min(1,dt*9);e.y+=(e.ty-e.y)*Math.min(1,dt*9)}for(const b of bullets.values()){b.x+=(b.tx-b.x)*Math.min(1,dt*16);b.y+=(b.ty-b.y)*Math.min(1,dt*16)}}
function resize(){const mobile=innerWidth<=760,d=Math.min(devicePixelRatio||1,mobile?1.15:1.5);canvas.width=Math.max(1,Math.floor(innerWidth*d));canvas.height=Math.max(1,Math.floor(innerHeight*d));canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}
function frame(now){const dt=Math.min(.04,Math.max(0,(now-lastFrame)/1000));lastFrame=now;simulate(dt);const me=players.get(myId),cx=me?.x??world.width/2,cy=me?.y??world.height/2;ctx.setTransform(canvas.width/innerWidth,0,0,canvas.height/innerHeight,0,0);drawMap(cx,cy);if(started){drawMed(cx,cy);for(const b of bullets.values())drawBullet(b,cx,cy);for(const e of enemies.values())drawEnemy(e,cx,cy);for(const p of players.values())drawPlayer(p,cx,cy)}fpsFrames++;if(now-fpsAt>=500){ui.fps.textContent='FPS '+Math.round(fpsFrames*1000/(now-fpsAt));fpsFrames=0;fpsAt=now}refreshUi();requestAnimationFrame(frame)}
setInterval(()=>sendInput(false),33);setInterval(()=>{if(joined)send({type:'ping',clientTime:performance.now()})},1500);
addEventListener('resize',resize,{passive:true});addEventListener('keydown',e=>{if(safeTarget(e)||!joined||!started)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code);sendInput(false)}});addEventListener('keyup',e=>{if(safeTarget(e))return;if(keys.delete(e.code))sendInput(Math.hypot(input.dx,input.dy)<.01)});
function updateTouch(e){const max=52,dx=e.clientX-touch.sx,dy=e.clientY-touch.sy,n=Math.hypot(dx,dy);if(n>max){touch.dx=dx/n;touch.dy=dy/n}else{touch.dx=dx/max;touch.dy=dy/max}}
canvas.addEventListener('pointerdown',e=>{if(!joined||!started||ui.skillPick.classList.contains('show')||ui.menu.classList.contains('show')||ui.gameOver.classList.contains('show'))return;touch.active=true;touch.id=e.pointerId;touch.sx=e.clientX;touch.sy=e.clientY;touch.dx=touch.dy=0;canvas.setPointerCapture?.(e.pointerId);sendInput(false);e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(touch.active&&e.pointerId===touch.id){updateTouch(e);sendInput(false);e.preventDefault()}});const releaseTouch=e=>{if(touch.id!==null&&e.pointerId!==touch.id)return;touch.active=false;touch.id=null;touch.dx=touch.dy=0;sendInput(true)};canvas.addEventListener('pointerup',releaseTouch);canvas.addEventListener('pointercancel',releaseTouch);
ui.room.addEventListener('input',()=>{const pos=ui.room.selectionStart;ui.room.value=cleanRoom(ui.room.value);try{ui.room.setSelectionRange(pos,pos)}catch{}});ui.room.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();ui.room.blur();openConnection(false)}});ui.name.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();ui.room.focus()}});
ui.create.onclick=()=>{loader.progress=0;loader.mapDone=false;loader.readySent=false;setLoad(0,'CRIANDO SALA...');openConnection(true)};ui.connect.onclick=()=>{loader.progress=0;loader.mapDone=false;loader.readySent=false;setLoad(0,'ENTRANDO NA SALA...');openConnection(false)};ui.startMatch.onclick=()=>{if(myRole==='p1'&&lobbyState.canStart)send({type:'start-match'})};
function leaveRoom(){manualClose=true;clearTimeout(reconnectTimer);joined=false;started=false;try{ws?.close(1000,'player_left')}catch{}ws=null;players.clear();enemies.clear();bullets.clear();myId=myRole='';room='';lobbyState={players:[],canStart:false,status:'waiting'};ui.roomLabel.textContent='MULTIPLAYER · SEM SALA';ui.skillPick.classList.remove('show');ui.gameOver.classList.remove('show');ui.menu.classList.remove('show');ui.startCover.classList.remove('show');setNet('SERVIDOR: DESCONECTADO');showJoin()}
ui.leaveLobby.onclick=leaveRoom;ui.leave.onclick=leaveRoom;ui.menuBtn.onclick=()=>{if(!joined||!started)return;ui.menuRoom.textContent=room;ui.menuStatus.textContent=serverVersion+' · SERVIDOR DEDICADO';ui.menu.classList.add('show')};ui.resume.onclick=()=>ui.menu.classList.remove('show');ui.restart.onclick=()=>{send({type:'restart'});ui.gameOver.classList.remove('show');ui.startCover.classList.add('show')};
resize();requestAnimationFrame(frame);console.log('CAOS LIVE MULTIPLAYER',{online:ONLINE_VERSION,baseSolo:BASE_SOLO});
})();
